/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { configurationGetManagedConfig } from "../funcs/configurationGetManagedConfig.js";
import { configurationUpdateManagedConfig } from "../funcs/configurationUpdateManagedConfig.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Configuration extends ClientSDK {
  /**
   * Get Managed Configuration
   *
   * @remarks
   * Returns managed Outpost configuration values.
   *
   * This endpoint is only available for the managed version.
   * In self-hosted deployments, configuration is controlled through environment variables instead.
   */
  async getManagedConfig(
    options?: RequestOptions,
  ): Promise<components.ManagedConfig> {
    return unwrapAsync(configurationGetManagedConfig(
      this,
      options,
    ));
  }

  /**
   * Update Managed Configuration
   *
   * @remarks
   * Updates one or more managed Outpost configuration values. Null values clear the configuration and reverts to Outpost default behavior.
   *
   * This endpoint is only available for the managed version.
   * In self-hosted deployments, configuration is controlled through environment variables instead.
   *
   * Only the supported configuration keys are accepted.
   */
  async updateManagedConfig(
    request: components.ManagedConfig,
    options?: RequestOptions,
  ): Promise<components.ManagedConfig> {
    return unwrapAsync(configurationUpdateManagedConfig(
      this,
      request,
      options,
    ));
  }
}
