root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main cmd/outpost/main.go"
  bin = "tmp/main"
  delay = 100
  exclude_dir = ["examples", "dist", "docs", "website", "loadtest", "internal/portal/node_modules", "internal/portal/src"]
  include_ext = ["go"]
  include_file = ["go.mod", "go.sum", ".env"]
