root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main cmd/eventkit/main.go"
  bin = "tmp/main"
  delay = 100
  exclude_dir = ["internal/portal/node_modules"]
  include_ext = ["go"]
  include_file = ["go.mod", "go.sum", ".env"]
