name: "eventkit"

services:
  api:
    build:
      context: .
      dockerfile: configs/api.Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis
    ports:
      - "${PORT}:${PORT}"
    env_file: .env
    environment:
      REDIS_HOST: redis

  delivery:
    build:
      context: .
      dockerfile: configs/delivery.Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file: .env
    environment:
      REDIS_HOST: redis
      DISABLED: true # Temporary env variable to disable the service

  data:
    build:
      context: .
      dockerfile: configs/data.Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file: .env
    environment:
      REDIS_HOST: redis
      DISABLED: true # Temporary env variable to disable the service

  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: >
      redis-server
        --save 20 1
        --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
