/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Partial Azure Service Bus config for PATCH updates (RFC 7396 merge-patch).
 */
export type AzureServiceBusConfigUpdate = {
  /**
   * The name of the Azure Service Bus queue or topic to publish messages to.
   */
  name?: string | undefined;
};

/** @internal */
export const AzureServiceBusConfigUpdate$inboundSchema: z.ZodType<
  AzureServiceBusConfigUpdate,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
});
/** @internal */
export type AzureServiceBusConfigUpdate$Outbound = {
  name?: string | undefined;
};

/** @internal */
export const AzureServiceBusConfigUpdate$outboundSchema: z.ZodType<
  AzureServiceBusConfigUpdate$Outbound,
  z.ZodTypeDef,
  AzureServiceBusConfigUpdate
> = z.object({
  name: z.string().optional(),
});

export function azureServiceBusConfigUpdateToJSON(
  azureServiceBusConfigUpdate: AzureServiceBusConfigUpdate,
): string {
  return JSON.stringify(
    AzureServiceBusConfigUpdate$outboundSchema.parse(
      azureServiceBusConfigUpdate,
    ),
  );
}
export function azureServiceBusConfigUpdateFromJSON(
  jsonString: string,
): SafeParseResult<AzureServiceBusConfigUpdate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AzureServiceBusConfigUpdate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AzureServiceBusConfigUpdate' from JSON`,
  );
}
