/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  RabbitMQConfig,
  RabbitMQConfig$inboundSchema,
  RabbitMQConfig$Outbound,
  RabbitMQConfig$outboundSchema,
} from "./rabbitmqconfig.js";
import {
  RabbitMQCredentials,
  RabbitMQCredentials$inboundSchema,
  RabbitMQCredentials$Outbound,
  RabbitMQCredentials$outboundSchema,
} from "./rabbitmqcredentials.js";
import {
  Topics,
  Topics$inboundSchema,
  Topics$Outbound,
  Topics$outboundSchema,
} from "./topics.js";

export type DestinationUpdateRabbitMQ = {
  /**
   * "*" or an array of enabled topics.
   */
  topics?: Topics | undefined;
  /**
   * Optional JSON schema filter for event matching. Events must match this filter to be delivered to this destination.
   *
   * @remarks
   * Supports operators: $eq, $neq, $gt, $gte, $lt, $lte, $in, $nin, $startsWith, $endsWith, $exist, $or, $and, $not.
   * If null or empty, all events matching the topic filter will be delivered.
   * Uses full-replacement semantics on update: send a new object to replace, null or `{}` to clear, omit for no change.
   */
  filter?: { [k: string]: any } | null | undefined;
  config?: RabbitMQConfig | undefined;
  credentials?: RabbitMQCredentials | undefined;
  /**
   * Static key-value pairs merged into event metadata on every attempt. Uses JSON merge-patch semantics (RFC 7396): send keys to add/update, null values to delete keys, null for entire field to clear all. Omit or send {} for no change.
   */
  deliveryMetadata?: { [k: string]: string | null } | null | undefined;
  /**
   * Arbitrary contextual information stored with the destination. Uses JSON merge-patch semantics (RFC 7396): send keys to add/update, null values to delete keys, null for entire field to clear all. Omit or send {} for no change.
   */
  metadata?: { [k: string]: string | null } | null | undefined;
  /**
   * Update the disabled state of the destination. Send a timestamp (must not be in the future) to disable, null to enable, or omit to leave unchanged.
   */
  disabledAt?: Date | null | undefined;
};

/** @internal */
export const DestinationUpdateRabbitMQ$inboundSchema: z.ZodType<
  DestinationUpdateRabbitMQ,
  z.ZodTypeDef,
  unknown
> = z.object({
  topics: Topics$inboundSchema.optional(),
  filter: z.nullable(z.record(z.any())).optional(),
  config: RabbitMQConfig$inboundSchema.optional(),
  credentials: RabbitMQCredentials$inboundSchema.optional(),
  delivery_metadata: z.nullable(z.record(z.nullable(z.string()))).optional(),
  metadata: z.nullable(z.record(z.nullable(z.string()))).optional(),
  disabled_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "delivery_metadata": "deliveryMetadata",
    "disabled_at": "disabledAt",
  });
});
/** @internal */
export type DestinationUpdateRabbitMQ$Outbound = {
  topics?: Topics$Outbound | undefined;
  filter?: { [k: string]: any } | null | undefined;
  config?: RabbitMQConfig$Outbound | undefined;
  credentials?: RabbitMQCredentials$Outbound | undefined;
  delivery_metadata?: { [k: string]: string | null } | null | undefined;
  metadata?: { [k: string]: string | null } | null | undefined;
  disabled_at?: string | null | undefined;
};

/** @internal */
export const DestinationUpdateRabbitMQ$outboundSchema: z.ZodType<
  DestinationUpdateRabbitMQ$Outbound,
  z.ZodTypeDef,
  DestinationUpdateRabbitMQ
> = z.object({
  topics: Topics$outboundSchema.optional(),
  filter: z.nullable(z.record(z.any())).optional(),
  config: RabbitMQConfig$outboundSchema.optional(),
  credentials: RabbitMQCredentials$outboundSchema.optional(),
  deliveryMetadata: z.nullable(z.record(z.nullable(z.string()))).optional(),
  metadata: z.nullable(z.record(z.nullable(z.string()))).optional(),
  disabledAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
}).transform((v) => {
  return remap$(v, {
    deliveryMetadata: "delivery_metadata",
    disabledAt: "disabled_at",
  });
});

export function destinationUpdateRabbitMQToJSON(
  destinationUpdateRabbitMQ: DestinationUpdateRabbitMQ,
): string {
  return JSON.stringify(
    DestinationUpdateRabbitMQ$outboundSchema.parse(destinationUpdateRabbitMQ),
  );
}
export function destinationUpdateRabbitMQFromJSON(
  jsonString: string,
): SafeParseResult<DestinationUpdateRabbitMQ, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DestinationUpdateRabbitMQ$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DestinationUpdateRabbitMQ' from JSON`,
  );
}
