/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  HookdeckCredentialsUpdate,
  HookdeckCredentialsUpdate$inboundSchema,
  HookdeckCredentialsUpdate$Outbound,
  HookdeckCredentialsUpdate$outboundSchema,
} from "./hookdeckcredentialsupdate.js";
import {
  Topics,
  Topics$inboundSchema,
  Topics$Outbound,
  Topics$outboundSchema,
} from "./topics.js";

export type DestinationUpdateHookdeck = {
  /**
   * Destination type discriminator. Must equal the existing destination's type — type itself cannot be changed via PATCH.
   */
  type: "hookdeck";
  /**
   * "*" or an array of enabled topics. Topic strings can include "*" as a wildcard matching any run of characters. When available topics are configured, wildcard patterns must match at least one available topic.
   */
  topics?: Topics | undefined;
  /**
   * Optional JSON schema filter for event matching. Events must match this filter to be delivered to this destination.
   *
   * @remarks
   * Supports operators: $eq, $neq, $gt, $gte, $lt, $lte, $in, $nin, $startsWith, $endsWith, $exist, $or, $and, $not.
   * If null or empty, all events matching the topic filter will be delivered.
   * Uses full-replacement semantics on update: send a new object to replace, null or `{}` to clear, omit for no change.
   */
  filter?: { [k: string]: any } | null | undefined;
  /**
   * Partial Hookdeck credentials for PATCH updates (RFC 7396 merge-patch).
   */
  credentials?: HookdeckCredentialsUpdate | undefined;
  /**
   * Static key-value pairs merged into event metadata on every attempt. Uses JSON merge-patch semantics (RFC 7396): send keys to add/update, null values to delete keys, null for entire field to clear all. Omit or send {} for no change.
   */
  deliveryMetadata?: { [k: string]: string | null } | null | undefined;
  /**
   * Arbitrary contextual information stored with the destination. Uses JSON merge-patch semantics (RFC 7396): send keys to add/update, null values to delete keys, null for entire field to clear all. Omit or send {} for no change.
   */
  metadata?: { [k: string]: string | null } | null | undefined;
  /**
   * Update the disabled state of the destination. Send a timestamp (must not be in the future) to disable, null to enable, or omit to leave unchanged.
   */
  disabledAt?: Date | null | undefined;
};

/** @internal */
export const DestinationUpdateHookdeck$inboundSchema: z.ZodType<
  DestinationUpdateHookdeck,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("hookdeck"),
  topics: Topics$inboundSchema.optional(),
  filter: z.nullable(z.record(z.any())).optional(),
  credentials: HookdeckCredentialsUpdate$inboundSchema.optional(),
  delivery_metadata: z.nullable(z.record(z.nullable(z.string()))).optional(),
  metadata: z.nullable(z.record(z.nullable(z.string()))).optional(),
  disabled_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "delivery_metadata": "deliveryMetadata",
    "disabled_at": "disabledAt",
  });
});
/** @internal */
export type DestinationUpdateHookdeck$Outbound = {
  type: "hookdeck";
  topics?: Topics$Outbound | undefined;
  filter?: { [k: string]: any } | null | undefined;
  credentials?: HookdeckCredentialsUpdate$Outbound | undefined;
  delivery_metadata?: { [k: string]: string | null } | null | undefined;
  metadata?: { [k: string]: string | null } | null | undefined;
  disabled_at?: string | null | undefined;
};

/** @internal */
export const DestinationUpdateHookdeck$outboundSchema: z.ZodType<
  DestinationUpdateHookdeck$Outbound,
  z.ZodTypeDef,
  DestinationUpdateHookdeck
> = z.object({
  type: z.literal("hookdeck"),
  topics: Topics$outboundSchema.optional(),
  filter: z.nullable(z.record(z.any())).optional(),
  credentials: HookdeckCredentialsUpdate$outboundSchema.optional(),
  deliveryMetadata: z.nullable(z.record(z.nullable(z.string()))).optional(),
  metadata: z.nullable(z.record(z.nullable(z.string()))).optional(),
  disabledAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
}).transform((v) => {
  return remap$(v, {
    deliveryMetadata: "delivery_metadata",
    disabledAt: "disabled_at",
  });
});

export function destinationUpdateHookdeckToJSON(
  destinationUpdateHookdeck: DestinationUpdateHookdeck,
): string {
  return JSON.stringify(
    DestinationUpdateHookdeck$outboundSchema.parse(destinationUpdateHookdeck),
  );
}
export function destinationUpdateHookdeckFromJSON(
  jsonString: string,
): SafeParseResult<DestinationUpdateHookdeck, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DestinationUpdateHookdeck$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DestinationUpdateHookdeck' from JSON`,
  );
}
