/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Full event object with data (returned when include=event.data).
 */
export type EventFull = {
  id?: string | undefined;
  /**
   * The tenant this event belongs to.
   */
  tenantId?: string | undefined;
  /**
   * The destination this event was delivered to.
   */
  destinationId?: string | undefined;
  topic?: string | undefined;
  /**
   * Time the event was received.
   */
  time?: Date | undefined;
  /**
   * Whether this event can be retried.
   */
  eligibleForRetry?: boolean | undefined;
  metadata?: { [k: string]: string } | null | undefined;
  /**
   * The event payload data.
   */
  data?: { [k: string]: any } | undefined;
};

/** @internal */
export const EventFull$inboundSchema: z.ZodType<
  EventFull,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  tenant_id: z.string().optional(),
  destination_id: z.string().optional(),
  topic: z.string().optional(),
  time: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  eligible_for_retry: z.boolean().optional(),
  metadata: z.nullable(z.record(z.string())).optional(),
  data: z.record(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    "tenant_id": "tenantId",
    "destination_id": "destinationId",
    "eligible_for_retry": "eligibleForRetry",
  });
});
/** @internal */
export type EventFull$Outbound = {
  id?: string | undefined;
  tenant_id?: string | undefined;
  destination_id?: string | undefined;
  topic?: string | undefined;
  time?: string | undefined;
  eligible_for_retry?: boolean | undefined;
  metadata?: { [k: string]: string } | null | undefined;
  data?: { [k: string]: any } | undefined;
};

/** @internal */
export const EventFull$outboundSchema: z.ZodType<
  EventFull$Outbound,
  z.ZodTypeDef,
  EventFull
> = z.object({
  id: z.string().optional(),
  tenantId: z.string().optional(),
  destinationId: z.string().optional(),
  topic: z.string().optional(),
  time: z.date().transform(v => v.toISOString()).optional(),
  eligibleForRetry: z.boolean().optional(),
  metadata: z.nullable(z.record(z.string())).optional(),
  data: z.record(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    tenantId: "tenant_id",
    destinationId: "destination_id",
    eligibleForRetry: "eligible_for_retry",
  });
});

export function eventFullToJSON(eventFull: EventFull): string {
  return JSON.stringify(EventFull$outboundSchema.parse(eventFull));
}
export function eventFullFromJSON(
  jsonString: string,
): SafeParseResult<EventFull, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EventFull$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventFull' from JSON`,
  );
}
