/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * SASL authentication mechanism.
 */
export const KafkaConfigUpdateSaslMechanism = {
  Plain: "plain",
  ScramSha256: "scram-sha-256",
  ScramSha512: "scram-sha-512",
} as const;
/**
 * SASL authentication mechanism.
 */
export type KafkaConfigUpdateSaslMechanism = ClosedEnum<
  typeof KafkaConfigUpdateSaslMechanism
>;

/**
 * Whether to enable TLS for the connection.
 */
export const KafkaConfigUpdateTls = {
  True: "true",
  False: "false",
} as const;
/**
 * Whether to enable TLS for the connection.
 */
export type KafkaConfigUpdateTls = ClosedEnum<typeof KafkaConfigUpdateTls>;

/**
 * Partial Kafka config for PATCH updates (RFC 7396 merge-patch).
 */
export type KafkaConfigUpdate = {
  /**
   * Comma-separated list of Kafka broker addresses.
   */
  brokers?: string | undefined;
  /**
   * The Kafka topic to publish messages to.
   */
  topic?: string | undefined;
  /**
   * SASL authentication mechanism.
   */
  saslMechanism?: KafkaConfigUpdateSaslMechanism | undefined;
  /**
   * Whether to enable TLS for the connection.
   */
  tls?: KafkaConfigUpdateTls | undefined;
  /**
   * Optional JMESPath template to extract the partition key from the event payload.
   */
  partitionKeyTemplate?: string | undefined;
};

/** @internal */
export const KafkaConfigUpdateSaslMechanism$inboundSchema: z.ZodNativeEnum<
  typeof KafkaConfigUpdateSaslMechanism
> = z.nativeEnum(KafkaConfigUpdateSaslMechanism);
/** @internal */
export const KafkaConfigUpdateSaslMechanism$outboundSchema: z.ZodNativeEnum<
  typeof KafkaConfigUpdateSaslMechanism
> = KafkaConfigUpdateSaslMechanism$inboundSchema;

/** @internal */
export const KafkaConfigUpdateTls$inboundSchema: z.ZodNativeEnum<
  typeof KafkaConfigUpdateTls
> = z.nativeEnum(KafkaConfigUpdateTls);
/** @internal */
export const KafkaConfigUpdateTls$outboundSchema: z.ZodNativeEnum<
  typeof KafkaConfigUpdateTls
> = KafkaConfigUpdateTls$inboundSchema;

/** @internal */
export const KafkaConfigUpdate$inboundSchema: z.ZodType<
  KafkaConfigUpdate,
  z.ZodTypeDef,
  unknown
> = z.object({
  brokers: z.string().optional(),
  topic: z.string().optional(),
  sasl_mechanism: KafkaConfigUpdateSaslMechanism$inboundSchema.optional(),
  tls: KafkaConfigUpdateTls$inboundSchema.optional(),
  partition_key_template: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "sasl_mechanism": "saslMechanism",
    "partition_key_template": "partitionKeyTemplate",
  });
});
/** @internal */
export type KafkaConfigUpdate$Outbound = {
  brokers?: string | undefined;
  topic?: string | undefined;
  sasl_mechanism?: string | undefined;
  tls?: string | undefined;
  partition_key_template?: string | undefined;
};

/** @internal */
export const KafkaConfigUpdate$outboundSchema: z.ZodType<
  KafkaConfigUpdate$Outbound,
  z.ZodTypeDef,
  KafkaConfigUpdate
> = z.object({
  brokers: z.string().optional(),
  topic: z.string().optional(),
  saslMechanism: KafkaConfigUpdateSaslMechanism$outboundSchema.optional(),
  tls: KafkaConfigUpdateTls$outboundSchema.optional(),
  partitionKeyTemplate: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    saslMechanism: "sasl_mechanism",
    partitionKeyTemplate: "partition_key_template",
  });
});

export function kafkaConfigUpdateToJSON(
  kafkaConfigUpdate: KafkaConfigUpdate,
): string {
  return JSON.stringify(
    KafkaConfigUpdate$outboundSchema.parse(kafkaConfigUpdate),
  );
}
export function kafkaConfigUpdateFromJSON(
  jsonString: string,
): SafeParseResult<KafkaConfigUpdate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KafkaConfigUpdate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KafkaConfigUpdate' from JSON`,
  );
}
