/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * SASL authentication mechanism.
 */
export const SaslMechanism = {
  Plain: "plain",
  ScramSha256: "scram-sha-256",
  ScramSha512: "scram-sha-512",
} as const;
/**
 * SASL authentication mechanism.
 */
export type SaslMechanism = ClosedEnum<typeof SaslMechanism>;

/**
 * Whether to enable TLS for the connection.
 */
export const KafkaConfigTls = {
  True: "true",
  False: "false",
} as const;
/**
 * Whether to enable TLS for the connection.
 */
export type KafkaConfigTls = ClosedEnum<typeof KafkaConfigTls>;

export type KafkaConfig = {
  /**
   * Comma-separated list of Kafka broker addresses.
   */
  brokers: string;
  /**
   * The Kafka topic to publish messages to.
   */
  topic: string;
  /**
   * SASL authentication mechanism.
   */
  saslMechanism: SaslMechanism;
  /**
   * Whether to enable TLS for the connection.
   */
  tls?: KafkaConfigTls | undefined;
  /**
   * Optional JMESPath template to extract the partition key from the event payload. Defaults to the event ID.
   */
  partitionKeyTemplate?: string | undefined;
};

/** @internal */
export const SaslMechanism$inboundSchema: z.ZodNativeEnum<
  typeof SaslMechanism
> = z.nativeEnum(SaslMechanism);
/** @internal */
export const SaslMechanism$outboundSchema: z.ZodNativeEnum<
  typeof SaslMechanism
> = SaslMechanism$inboundSchema;

/** @internal */
export const KafkaConfigTls$inboundSchema: z.ZodNativeEnum<
  typeof KafkaConfigTls
> = z.nativeEnum(KafkaConfigTls);
/** @internal */
export const KafkaConfigTls$outboundSchema: z.ZodNativeEnum<
  typeof KafkaConfigTls
> = KafkaConfigTls$inboundSchema;

/** @internal */
export const KafkaConfig$inboundSchema: z.ZodType<
  KafkaConfig,
  z.ZodTypeDef,
  unknown
> = z.object({
  brokers: z.string(),
  topic: z.string(),
  sasl_mechanism: SaslMechanism$inboundSchema,
  tls: KafkaConfigTls$inboundSchema.default("true"),
  partition_key_template: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "sasl_mechanism": "saslMechanism",
    "partition_key_template": "partitionKeyTemplate",
  });
});
/** @internal */
export type KafkaConfig$Outbound = {
  brokers: string;
  topic: string;
  sasl_mechanism: string;
  tls: string;
  partition_key_template?: string | undefined;
};

/** @internal */
export const KafkaConfig$outboundSchema: z.ZodType<
  KafkaConfig$Outbound,
  z.ZodTypeDef,
  KafkaConfig
> = z.object({
  brokers: z.string(),
  topic: z.string(),
  saslMechanism: SaslMechanism$outboundSchema,
  tls: KafkaConfigTls$outboundSchema.default("true"),
  partitionKeyTemplate: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    saslMechanism: "sasl_mechanism",
    partitionKeyTemplate: "partition_key_template",
  });
});

export function kafkaConfigToJSON(kafkaConfig: KafkaConfig): string {
  return JSON.stringify(KafkaConfig$outboundSchema.parse(kafkaConfig));
}
export function kafkaConfigFromJSON(
  jsonString: string,
): SafeParseResult<KafkaConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KafkaConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KafkaConfig' from JSON`,
  );
}
