/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Managed configuration values for Outpost Cloud.
 *
 * @remarks
 * This API is available only on the managed version.
 * Self-hosted deployments configure these values using environment variables.
 */
export type ManagedConfig = {
  alertAutoDisableDestination?: string | undefined;
  alertCallbackUrl?: string | undefined;
  alertConsecutiveFailureCount?: string | undefined;
  deliveryTimeoutSeconds?: string | undefined;
  destinationsAwsKinesisMetadataInPayload?: string | undefined;
  destinationsIncludeMillisecondTimestamp?: string | undefined;
  destinationsWebhookDisableDefaultEventIdHeader?: string | undefined;
  destinationsWebhookDisableDefaultSignatureHeader?: string | undefined;
  destinationsWebhookDisableDefaultTimestampHeader?: string | undefined;
  destinationsWebhookDisableDefaultTopicHeader?: string | undefined;
  destinationsWebhookHeaderPrefix?: string | undefined;
  destinationsWebhookMode?: string | undefined;
  destinationsWebhookProxyUrl?: string | undefined;
  destinationsWebhookSignatureAlgorithm?: string | undefined;
  destinationsWebhookSignatureContentTemplate?: string | undefined;
  destinationsWebhookSignatureEncoding?: string | undefined;
  destinationsWebhookSignatureHeaderTemplate?: string | undefined;
  destinationsWebhookSigningSecretTemplate?: string | undefined;
  httpUserAgent?: string | undefined;
  idgenAttemptPrefix?: string | undefined;
  idgenDestinationPrefix?: string | undefined;
  idgenEventPrefix?: string | undefined;
  idgenType?: string | undefined;
  maxDestinationsPerTenant?: string | undefined;
  organizationName?: string | undefined;
  portalBrandColor?: string | undefined;
  portalDisableOutpostBranding?: string | undefined;
  portalFaviconUrl?: string | undefined;
  portalForceTheme?: string | undefined;
  portalLogo?: string | undefined;
  portalLogoDark?: string | undefined;
  portalOrganizationName?: string | undefined;
  portalRefererUrl?: string | undefined;
  portalRefreshUrl?: string | undefined;
  portalEnableDestinationFilter?: string | undefined;
  portalEnableWebhookCustomHeaders?: string | undefined;
  retryIntervalSeconds?: string | undefined;
  maxRetryLimit?: string | undefined;
  retrySchedule?: string | undefined;
  otelExporterOtlpEndpoint?: string | undefined;
  otelExporterOtlpHeaders?: string | undefined;
  otelExporterOtlpProtocol?: string | undefined;
  otelExporterOtlpTracesEndpoint?: string | undefined;
  otelExporterOtlpMetricsEndpoint?: string | undefined;
  otelExporterOtlpLogsEndpoint?: string | undefined;
  otelServiceName?: string | undefined;
  publishAwsSqsAccessKeyId?: string | undefined;
  publishAwsSqsEndpoint?: string | undefined;
  publishAwsSqsQueue?: string | undefined;
  publishAwsSqsRegion?: string | undefined;
  publishAwsSqsSecretAccessKey?: string | undefined;
  publishAzureServicebusConnectionString?: string | undefined;
  publishAzureServicebusSubscription?: string | undefined;
  publishAzureServicebusTopic?: string | undefined;
  publishGcpPubsubProject?: string | undefined;
  publishGcpPubsubServiceAccountCredentials?: string | undefined;
  publishGcpPubsubSubscription?: string | undefined;
  publishGcpPubsubTopic?: string | undefined;
  publishRabbitmqExchange?: string | undefined;
  publishRabbitmqQueue?: string | undefined;
  publishRabbitmqServerUrl?: string | undefined;
  topics?: string | undefined;
};

/** @internal */
export const ManagedConfig$inboundSchema: z.ZodType<
  ManagedConfig,
  z.ZodTypeDef,
  unknown
> = z.object({
  ALERT_AUTO_DISABLE_DESTINATION: z.string().optional(),
  ALERT_CALLBACK_URL: z.string().optional(),
  ALERT_CONSECUTIVE_FAILURE_COUNT: z.string().optional(),
  DELIVERY_TIMEOUT_SECONDS: z.string().optional(),
  DESTINATIONS_AWS_KINESIS_METADATA_IN_PAYLOAD: z.string().optional(),
  DESTINATIONS_INCLUDE_MILLISECOND_TIMESTAMP: z.string().optional(),
  DESTINATIONS_WEBHOOK_DISABLE_DEFAULT_EVENT_ID_HEADER: z.string().optional(),
  DESTINATIONS_WEBHOOK_DISABLE_DEFAULT_SIGNATURE_HEADER: z.string().optional(),
  DESTINATIONS_WEBHOOK_DISABLE_DEFAULT_TIMESTAMP_HEADER: z.string().optional(),
  DESTINATIONS_WEBHOOK_DISABLE_DEFAULT_TOPIC_HEADER: z.string().optional(),
  DESTINATIONS_WEBHOOK_HEADER_PREFIX: z.string().optional(),
  DESTINATIONS_WEBHOOK_MODE: z.string().optional(),
  DESTINATIONS_WEBHOOK_PROXY_URL: z.string().optional(),
  DESTINATIONS_WEBHOOK_SIGNATURE_ALGORITHM: z.string().optional(),
  DESTINATIONS_WEBHOOK_SIGNATURE_CONTENT_TEMPLATE: z.string().optional(),
  DESTINATIONS_WEBHOOK_SIGNATURE_ENCODING: z.string().optional(),
  DESTINATIONS_WEBHOOK_SIGNATURE_HEADER_TEMPLATE: z.string().optional(),
  DESTINATIONS_WEBHOOK_SIGNING_SECRET_TEMPLATE: z.string().optional(),
  HTTP_USER_AGENT: z.string().optional(),
  IDGEN_ATTEMPT_PREFIX: z.string().optional(),
  IDGEN_DESTINATION_PREFIX: z.string().optional(),
  IDGEN_EVENT_PREFIX: z.string().optional(),
  IDGEN_TYPE: z.string().optional(),
  MAX_DESTINATIONS_PER_TENANT: z.string().optional(),
  ORGANIZATION_NAME: z.string().optional(),
  PORTAL_BRAND_COLOR: z.string().optional(),
  PORTAL_DISABLE_OUTPOST_BRANDING: z.string().optional(),
  PORTAL_FAVICON_URL: z.string().optional(),
  PORTAL_FORCE_THEME: z.string().optional(),
  PORTAL_LOGO: z.string().optional(),
  PORTAL_LOGO_DARK: z.string().optional(),
  PORTAL_ORGANIZATION_NAME: z.string().optional(),
  PORTAL_REFERER_URL: z.string().optional(),
  PORTAL_REFRESH_URL: z.string().optional(),
  PORTAL_ENABLE_DESTINATION_FILTER: z.string().optional(),
  PORTAL_ENABLE_WEBHOOK_CUSTOM_HEADERS: z.string().optional(),
  RETRY_INTERVAL_SECONDS: z.string().optional(),
  MAX_RETRY_LIMIT: z.string().optional(),
  RETRY_SCHEDULE: z.string().optional(),
  OTEL_EXPORTER_OTLP_ENDPOINT: z.string().optional(),
  OTEL_EXPORTER_OTLP_HEADERS: z.string().optional(),
  OTEL_EXPORTER_OTLP_PROTOCOL: z.string().optional(),
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: z.string().optional(),
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: z.string().optional(),
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: z.string().optional(),
  OTEL_SERVICE_NAME: z.string().optional(),
  PUBLISH_AWS_SQS_ACCESS_KEY_ID: z.string().optional(),
  PUBLISH_AWS_SQS_ENDPOINT: z.string().optional(),
  PUBLISH_AWS_SQS_QUEUE: z.string().optional(),
  PUBLISH_AWS_SQS_REGION: z.string().optional(),
  PUBLISH_AWS_SQS_SECRET_ACCESS_KEY: z.string().optional(),
  PUBLISH_AZURE_SERVICEBUS_CONNECTION_STRING: z.string().optional(),
  PUBLISH_AZURE_SERVICEBUS_SUBSCRIPTION: z.string().optional(),
  PUBLISH_AZURE_SERVICEBUS_TOPIC: z.string().optional(),
  PUBLISH_GCP_PUBSUB_PROJECT: z.string().optional(),
  PUBLISH_GCP_PUBSUB_SERVICE_ACCOUNT_CREDENTIALS: z.string().optional(),
  PUBLISH_GCP_PUBSUB_SUBSCRIPTION: z.string().optional(),
  PUBLISH_GCP_PUBSUB_TOPIC: z.string().optional(),
  PUBLISH_RABBITMQ_EXCHANGE: z.string().optional(),
  PUBLISH_RABBITMQ_QUEUE: z.string().optional(),
  PUBLISH_RABBITMQ_SERVER_URL: z.string().optional(),
  TOPICS: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "ALERT_AUTO_DISABLE_DESTINATION": "alertAutoDisableDestination",
    "ALERT_CALLBACK_URL": "alertCallbackUrl",
    "ALERT_CONSECUTIVE_FAILURE_COUNT": "alertConsecutiveFailureCount",
    "DELIVERY_TIMEOUT_SECONDS": "deliveryTimeoutSeconds",
    "DESTINATIONS_AWS_KINESIS_METADATA_IN_PAYLOAD":
      "destinationsAwsKinesisMetadataInPayload",
    "DESTINATIONS_INCLUDE_MILLISECOND_TIMESTAMP":
      "destinationsIncludeMillisecondTimestamp",
    "DESTINATIONS_WEBHOOK_DISABLE_DEFAULT_EVENT_ID_HEADER":
      "destinationsWebhookDisableDefaultEventIdHeader",
    "DESTINATIONS_WEBHOOK_DISABLE_DEFAULT_SIGNATURE_HEADER":
      "destinationsWebhookDisableDefaultSignatureHeader",
    "DESTINATIONS_WEBHOOK_DISABLE_DEFAULT_TIMESTAMP_HEADER":
      "destinationsWebhookDisableDefaultTimestampHeader",
    "DESTINATIONS_WEBHOOK_DISABLE_DEFAULT_TOPIC_HEADER":
      "destinationsWebhookDisableDefaultTopicHeader",
    "DESTINATIONS_WEBHOOK_HEADER_PREFIX": "destinationsWebhookHeaderPrefix",
    "DESTINATIONS_WEBHOOK_MODE": "destinationsWebhookMode",
    "DESTINATIONS_WEBHOOK_PROXY_URL": "destinationsWebhookProxyUrl",
    "DESTINATIONS_WEBHOOK_SIGNATURE_ALGORITHM":
      "destinationsWebhookSignatureAlgorithm",
    "DESTINATIONS_WEBHOOK_SIGNATURE_CONTENT_TEMPLATE":
      "destinationsWebhookSignatureContentTemplate",
    "DESTINATIONS_WEBHOOK_SIGNATURE_ENCODING":
      "destinationsWebhookSignatureEncoding",
    "DESTINATIONS_WEBHOOK_SIGNATURE_HEADER_TEMPLATE":
      "destinationsWebhookSignatureHeaderTemplate",
    "DESTINATIONS_WEBHOOK_SIGNING_SECRET_TEMPLATE":
      "destinationsWebhookSigningSecretTemplate",
    "HTTP_USER_AGENT": "httpUserAgent",
    "IDGEN_ATTEMPT_PREFIX": "idgenAttemptPrefix",
    "IDGEN_DESTINATION_PREFIX": "idgenDestinationPrefix",
    "IDGEN_EVENT_PREFIX": "idgenEventPrefix",
    "IDGEN_TYPE": "idgenType",
    "MAX_DESTINATIONS_PER_TENANT": "maxDestinationsPerTenant",
    "ORGANIZATION_NAME": "organizationName",
    "PORTAL_BRAND_COLOR": "portalBrandColor",
    "PORTAL_DISABLE_OUTPOST_BRANDING": "portalDisableOutpostBranding",
    "PORTAL_FAVICON_URL": "portalFaviconUrl",
    "PORTAL_FORCE_THEME": "portalForceTheme",
    "PORTAL_LOGO": "portalLogo",
    "PORTAL_LOGO_DARK": "portalLogoDark",
    "PORTAL_ORGANIZATION_NAME": "portalOrganizationName",
    "PORTAL_REFERER_URL": "portalRefererUrl",
    "PORTAL_REFRESH_URL": "portalRefreshUrl",
    "PORTAL_ENABLE_DESTINATION_FILTER": "portalEnableDestinationFilter",
    "PORTAL_ENABLE_WEBHOOK_CUSTOM_HEADERS": "portalEnableWebhookCustomHeaders",
    "RETRY_INTERVAL_SECONDS": "retryIntervalSeconds",
    "MAX_RETRY_LIMIT": "maxRetryLimit",
    "RETRY_SCHEDULE": "retrySchedule",
    "OTEL_EXPORTER_OTLP_ENDPOINT": "otelExporterOtlpEndpoint",
    "OTEL_EXPORTER_OTLP_HEADERS": "otelExporterOtlpHeaders",
    "OTEL_EXPORTER_OTLP_PROTOCOL": "otelExporterOtlpProtocol",
    "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT": "otelExporterOtlpTracesEndpoint",
    "OTEL_EXPORTER_OTLP_METRICS_ENDPOINT": "otelExporterOtlpMetricsEndpoint",
    "OTEL_EXPORTER_OTLP_LOGS_ENDPOINT": "otelExporterOtlpLogsEndpoint",
    "OTEL_SERVICE_NAME": "otelServiceName",
    "PUBLISH_AWS_SQS_ACCESS_KEY_ID": "publishAwsSqsAccessKeyId",
    "PUBLISH_AWS_SQS_ENDPOINT": "publishAwsSqsEndpoint",
    "PUBLISH_AWS_SQS_QUEUE": "publishAwsSqsQueue",
    "PUBLISH_AWS_SQS_REGION": "publishAwsSqsRegion",
    "PUBLISH_AWS_SQS_SECRET_ACCESS_KEY": "publishAwsSqsSecretAccessKey",
    "PUBLISH_AZURE_SERVICEBUS_CONNECTION_STRING":
      "publishAzureServicebusConnectionString",
    "PUBLISH_AZURE_SERVICEBUS_SUBSCRIPTION":
      "publishAzureServicebusSubscription",
    "PUBLISH_AZURE_SERVICEBUS_TOPIC": "publishAzureServicebusTopic",
    "PUBLISH_GCP_PUBSUB_PROJECT": "publishGcpPubsubProject",
    "PUBLISH_GCP_PUBSUB_SERVICE_ACCOUNT_CREDENTIALS":
      "publishGcpPubsubServiceAccountCredentials",
    "PUBLISH_GCP_PUBSUB_SUBSCRIPTION": "publishGcpPubsubSubscription",
    "PUBLISH_GCP_PUBSUB_TOPIC": "publishGcpPubsubTopic",
    "PUBLISH_RABBITMQ_EXCHANGE": "publishRabbitmqExchange",
    "PUBLISH_RABBITMQ_QUEUE": "publishRabbitmqQueue",
    "PUBLISH_RABBITMQ_SERVER_URL": "publishRabbitmqServerUrl",
    "TOPICS": "topics",
  });
});
/** @internal */
export type ManagedConfig$Outbound = {
  ALERT_AUTO_DISABLE_DESTINATION?: string | undefined;
  ALERT_CALLBACK_URL?: string | undefined;
  ALERT_CONSECUTIVE_FAILURE_COUNT?: string | undefined;
  DELIVERY_TIMEOUT_SECONDS?: string | undefined;
  DESTINATIONS_AWS_KINESIS_METADATA_IN_PAYLOAD?: string | undefined;
  DESTINATIONS_INCLUDE_MILLISECOND_TIMESTAMP?: string | undefined;
  DESTINATIONS_WEBHOOK_DISABLE_DEFAULT_EVENT_ID_HEADER?: string | undefined;
  DESTINATIONS_WEBHOOK_DISABLE_DEFAULT_SIGNATURE_HEADER?: string | undefined;
  DESTINATIONS_WEBHOOK_DISABLE_DEFAULT_TIMESTAMP_HEADER?: string | undefined;
  DESTINATIONS_WEBHOOK_DISABLE_DEFAULT_TOPIC_HEADER?: string | undefined;
  DESTINATIONS_WEBHOOK_HEADER_PREFIX?: string | undefined;
  DESTINATIONS_WEBHOOK_MODE?: string | undefined;
  DESTINATIONS_WEBHOOK_PROXY_URL?: string | undefined;
  DESTINATIONS_WEBHOOK_SIGNATURE_ALGORITHM?: string | undefined;
  DESTINATIONS_WEBHOOK_SIGNATURE_CONTENT_TEMPLATE?: string | undefined;
  DESTINATIONS_WEBHOOK_SIGNATURE_ENCODING?: string | undefined;
  DESTINATIONS_WEBHOOK_SIGNATURE_HEADER_TEMPLATE?: string | undefined;
  DESTINATIONS_WEBHOOK_SIGNING_SECRET_TEMPLATE?: string | undefined;
  HTTP_USER_AGENT?: string | undefined;
  IDGEN_ATTEMPT_PREFIX?: string | undefined;
  IDGEN_DESTINATION_PREFIX?: string | undefined;
  IDGEN_EVENT_PREFIX?: string | undefined;
  IDGEN_TYPE?: string | undefined;
  MAX_DESTINATIONS_PER_TENANT?: string | undefined;
  ORGANIZATION_NAME?: string | undefined;
  PORTAL_BRAND_COLOR?: string | undefined;
  PORTAL_DISABLE_OUTPOST_BRANDING?: string | undefined;
  PORTAL_FAVICON_URL?: string | undefined;
  PORTAL_FORCE_THEME?: string | undefined;
  PORTAL_LOGO?: string | undefined;
  PORTAL_LOGO_DARK?: string | undefined;
  PORTAL_ORGANIZATION_NAME?: string | undefined;
  PORTAL_REFERER_URL?: string | undefined;
  PORTAL_REFRESH_URL?: string | undefined;
  PORTAL_ENABLE_DESTINATION_FILTER?: string | undefined;
  PORTAL_ENABLE_WEBHOOK_CUSTOM_HEADERS?: string | undefined;
  RETRY_INTERVAL_SECONDS?: string | undefined;
  MAX_RETRY_LIMIT?: string | undefined;
  RETRY_SCHEDULE?: string | undefined;
  OTEL_EXPORTER_OTLP_ENDPOINT?: string | undefined;
  OTEL_EXPORTER_OTLP_HEADERS?: string | undefined;
  OTEL_EXPORTER_OTLP_PROTOCOL?: string | undefined;
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT?: string | undefined;
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT?: string | undefined;
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT?: string | undefined;
  OTEL_SERVICE_NAME?: string | undefined;
  PUBLISH_AWS_SQS_ACCESS_KEY_ID?: string | undefined;
  PUBLISH_AWS_SQS_ENDPOINT?: string | undefined;
  PUBLISH_AWS_SQS_QUEUE?: string | undefined;
  PUBLISH_AWS_SQS_REGION?: string | undefined;
  PUBLISH_AWS_SQS_SECRET_ACCESS_KEY?: string | undefined;
  PUBLISH_AZURE_SERVICEBUS_CONNECTION_STRING?: string | undefined;
  PUBLISH_AZURE_SERVICEBUS_SUBSCRIPTION?: string | undefined;
  PUBLISH_AZURE_SERVICEBUS_TOPIC?: string | undefined;
  PUBLISH_GCP_PUBSUB_PROJECT?: string | undefined;
  PUBLISH_GCP_PUBSUB_SERVICE_ACCOUNT_CREDENTIALS?: string | undefined;
  PUBLISH_GCP_PUBSUB_SUBSCRIPTION?: string | undefined;
  PUBLISH_GCP_PUBSUB_TOPIC?: string | undefined;
  PUBLISH_RABBITMQ_EXCHANGE?: string | undefined;
  PUBLISH_RABBITMQ_QUEUE?: string | undefined;
  PUBLISH_RABBITMQ_SERVER_URL?: string | undefined;
  TOPICS?: string | undefined;
};

/** @internal */
export const ManagedConfig$outboundSchema: z.ZodType<
  ManagedConfig$Outbound,
  z.ZodTypeDef,
  ManagedConfig
> = z.object({
  alertAutoDisableDestination: z.string().optional(),
  alertCallbackUrl: z.string().optional(),
  alertConsecutiveFailureCount: z.string().optional(),
  deliveryTimeoutSeconds: z.string().optional(),
  destinationsAwsKinesisMetadataInPayload: z.string().optional(),
  destinationsIncludeMillisecondTimestamp: z.string().optional(),
  destinationsWebhookDisableDefaultEventIdHeader: z.string().optional(),
  destinationsWebhookDisableDefaultSignatureHeader: z.string().optional(),
  destinationsWebhookDisableDefaultTimestampHeader: z.string().optional(),
  destinationsWebhookDisableDefaultTopicHeader: z.string().optional(),
  destinationsWebhookHeaderPrefix: z.string().optional(),
  destinationsWebhookMode: z.string().optional(),
  destinationsWebhookProxyUrl: z.string().optional(),
  destinationsWebhookSignatureAlgorithm: z.string().optional(),
  destinationsWebhookSignatureContentTemplate: z.string().optional(),
  destinationsWebhookSignatureEncoding: z.string().optional(),
  destinationsWebhookSignatureHeaderTemplate: z.string().optional(),
  destinationsWebhookSigningSecretTemplate: z.string().optional(),
  httpUserAgent: z.string().optional(),
  idgenAttemptPrefix: z.string().optional(),
  idgenDestinationPrefix: z.string().optional(),
  idgenEventPrefix: z.string().optional(),
  idgenType: z.string().optional(),
  maxDestinationsPerTenant: z.string().optional(),
  organizationName: z.string().optional(),
  portalBrandColor: z.string().optional(),
  portalDisableOutpostBranding: z.string().optional(),
  portalFaviconUrl: z.string().optional(),
  portalForceTheme: z.string().optional(),
  portalLogo: z.string().optional(),
  portalLogoDark: z.string().optional(),
  portalOrganizationName: z.string().optional(),
  portalRefererUrl: z.string().optional(),
  portalRefreshUrl: z.string().optional(),
  portalEnableDestinationFilter: z.string().optional(),
  portalEnableWebhookCustomHeaders: z.string().optional(),
  retryIntervalSeconds: z.string().optional(),
  maxRetryLimit: z.string().optional(),
  retrySchedule: z.string().optional(),
  otelExporterOtlpEndpoint: z.string().optional(),
  otelExporterOtlpHeaders: z.string().optional(),
  otelExporterOtlpProtocol: z.string().optional(),
  otelExporterOtlpTracesEndpoint: z.string().optional(),
  otelExporterOtlpMetricsEndpoint: z.string().optional(),
  otelExporterOtlpLogsEndpoint: z.string().optional(),
  otelServiceName: z.string().optional(),
  publishAwsSqsAccessKeyId: z.string().optional(),
  publishAwsSqsEndpoint: z.string().optional(),
  publishAwsSqsQueue: z.string().optional(),
  publishAwsSqsRegion: z.string().optional(),
  publishAwsSqsSecretAccessKey: z.string().optional(),
  publishAzureServicebusConnectionString: z.string().optional(),
  publishAzureServicebusSubscription: z.string().optional(),
  publishAzureServicebusTopic: z.string().optional(),
  publishGcpPubsubProject: z.string().optional(),
  publishGcpPubsubServiceAccountCredentials: z.string().optional(),
  publishGcpPubsubSubscription: z.string().optional(),
  publishGcpPubsubTopic: z.string().optional(),
  publishRabbitmqExchange: z.string().optional(),
  publishRabbitmqQueue: z.string().optional(),
  publishRabbitmqServerUrl: z.string().optional(),
  topics: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    alertAutoDisableDestination: "ALERT_AUTO_DISABLE_DESTINATION",
    alertCallbackUrl: "ALERT_CALLBACK_URL",
    alertConsecutiveFailureCount: "ALERT_CONSECUTIVE_FAILURE_COUNT",
    deliveryTimeoutSeconds: "DELIVERY_TIMEOUT_SECONDS",
    destinationsAwsKinesisMetadataInPayload:
      "DESTINATIONS_AWS_KINESIS_METADATA_IN_PAYLOAD",
    destinationsIncludeMillisecondTimestamp:
      "DESTINATIONS_INCLUDE_MILLISECOND_TIMESTAMP",
    destinationsWebhookDisableDefaultEventIdHeader:
      "DESTINATIONS_WEBHOOK_DISABLE_DEFAULT_EVENT_ID_HEADER",
    destinationsWebhookDisableDefaultSignatureHeader:
      "DESTINATIONS_WEBHOOK_DISABLE_DEFAULT_SIGNATURE_HEADER",
    destinationsWebhookDisableDefaultTimestampHeader:
      "DESTINATIONS_WEBHOOK_DISABLE_DEFAULT_TIMESTAMP_HEADER",
    destinationsWebhookDisableDefaultTopicHeader:
      "DESTINATIONS_WEBHOOK_DISABLE_DEFAULT_TOPIC_HEADER",
    destinationsWebhookHeaderPrefix: "DESTINATIONS_WEBHOOK_HEADER_PREFIX",
    destinationsWebhookMode: "DESTINATIONS_WEBHOOK_MODE",
    destinationsWebhookProxyUrl: "DESTINATIONS_WEBHOOK_PROXY_URL",
    destinationsWebhookSignatureAlgorithm:
      "DESTINATIONS_WEBHOOK_SIGNATURE_ALGORITHM",
    destinationsWebhookSignatureContentTemplate:
      "DESTINATIONS_WEBHOOK_SIGNATURE_CONTENT_TEMPLATE",
    destinationsWebhookSignatureEncoding:
      "DESTINATIONS_WEBHOOK_SIGNATURE_ENCODING",
    destinationsWebhookSignatureHeaderTemplate:
      "DESTINATIONS_WEBHOOK_SIGNATURE_HEADER_TEMPLATE",
    destinationsWebhookSigningSecretTemplate:
      "DESTINATIONS_WEBHOOK_SIGNING_SECRET_TEMPLATE",
    httpUserAgent: "HTTP_USER_AGENT",
    idgenAttemptPrefix: "IDGEN_ATTEMPT_PREFIX",
    idgenDestinationPrefix: "IDGEN_DESTINATION_PREFIX",
    idgenEventPrefix: "IDGEN_EVENT_PREFIX",
    idgenType: "IDGEN_TYPE",
    maxDestinationsPerTenant: "MAX_DESTINATIONS_PER_TENANT",
    organizationName: "ORGANIZATION_NAME",
    portalBrandColor: "PORTAL_BRAND_COLOR",
    portalDisableOutpostBranding: "PORTAL_DISABLE_OUTPOST_BRANDING",
    portalFaviconUrl: "PORTAL_FAVICON_URL",
    portalForceTheme: "PORTAL_FORCE_THEME",
    portalLogo: "PORTAL_LOGO",
    portalLogoDark: "PORTAL_LOGO_DARK",
    portalOrganizationName: "PORTAL_ORGANIZATION_NAME",
    portalRefererUrl: "PORTAL_REFERER_URL",
    portalRefreshUrl: "PORTAL_REFRESH_URL",
    portalEnableDestinationFilter: "PORTAL_ENABLE_DESTINATION_FILTER",
    portalEnableWebhookCustomHeaders: "PORTAL_ENABLE_WEBHOOK_CUSTOM_HEADERS",
    retryIntervalSeconds: "RETRY_INTERVAL_SECONDS",
    maxRetryLimit: "MAX_RETRY_LIMIT",
    retrySchedule: "RETRY_SCHEDULE",
    otelExporterOtlpEndpoint: "OTEL_EXPORTER_OTLP_ENDPOINT",
    otelExporterOtlpHeaders: "OTEL_EXPORTER_OTLP_HEADERS",
    otelExporterOtlpProtocol: "OTEL_EXPORTER_OTLP_PROTOCOL",
    otelExporterOtlpTracesEndpoint: "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT",
    otelExporterOtlpMetricsEndpoint: "OTEL_EXPORTER_OTLP_METRICS_ENDPOINT",
    otelExporterOtlpLogsEndpoint: "OTEL_EXPORTER_OTLP_LOGS_ENDPOINT",
    otelServiceName: "OTEL_SERVICE_NAME",
    publishAwsSqsAccessKeyId: "PUBLISH_AWS_SQS_ACCESS_KEY_ID",
    publishAwsSqsEndpoint: "PUBLISH_AWS_SQS_ENDPOINT",
    publishAwsSqsQueue: "PUBLISH_AWS_SQS_QUEUE",
    publishAwsSqsRegion: "PUBLISH_AWS_SQS_REGION",
    publishAwsSqsSecretAccessKey: "PUBLISH_AWS_SQS_SECRET_ACCESS_KEY",
    publishAzureServicebusConnectionString:
      "PUBLISH_AZURE_SERVICEBUS_CONNECTION_STRING",
    publishAzureServicebusSubscription: "PUBLISH_AZURE_SERVICEBUS_SUBSCRIPTION",
    publishAzureServicebusTopic: "PUBLISH_AZURE_SERVICEBUS_TOPIC",
    publishGcpPubsubProject: "PUBLISH_GCP_PUBSUB_PROJECT",
    publishGcpPubsubServiceAccountCredentials:
      "PUBLISH_GCP_PUBSUB_SERVICE_ACCOUNT_CREDENTIALS",
    publishGcpPubsubSubscription: "PUBLISH_GCP_PUBSUB_SUBSCRIPTION",
    publishGcpPubsubTopic: "PUBLISH_GCP_PUBSUB_TOPIC",
    publishRabbitmqExchange: "PUBLISH_RABBITMQ_EXCHANGE",
    publishRabbitmqQueue: "PUBLISH_RABBITMQ_QUEUE",
    publishRabbitmqServerUrl: "PUBLISH_RABBITMQ_SERVER_URL",
    topics: "TOPICS",
  });
});

export function managedConfigToJSON(managedConfig: ManagedConfig): string {
  return JSON.stringify(ManagedConfig$outboundSchema.parse(managedConfig));
}
export function managedConfigFromJSON(
  jsonString: string,
): SafeParseResult<ManagedConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ManagedConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ManagedConfig' from JSON`,
  );
}
