/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type EnableOperatorEventDestinationRequest = {
  /**
   * The ID of the operator event destination.
   */
  destinationId: string;
};

/** @internal */
export const EnableOperatorEventDestinationRequest$inboundSchema: z.ZodType<
  EnableOperatorEventDestinationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  destination_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "destination_id": "destinationId",
  });
});
/** @internal */
export type EnableOperatorEventDestinationRequest$Outbound = {
  destination_id: string;
};

/** @internal */
export const EnableOperatorEventDestinationRequest$outboundSchema: z.ZodType<
  EnableOperatorEventDestinationRequest$Outbound,
  z.ZodTypeDef,
  EnableOperatorEventDestinationRequest
> = z.object({
  destinationId: z.string(),
}).transform((v) => {
  return remap$(v, {
    destinationId: "destination_id",
  });
});

export function enableOperatorEventDestinationRequestToJSON(
  enableOperatorEventDestinationRequest: EnableOperatorEventDestinationRequest,
): string {
  return JSON.stringify(
    EnableOperatorEventDestinationRequest$outboundSchema.parse(
      enableOperatorEventDestinationRequest,
    ),
  );
}
export function enableOperatorEventDestinationRequestFromJSON(
  jsonString: string,
): SafeParseResult<EnableOperatorEventDestinationRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EnableOperatorEventDestinationRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnableOperatorEventDestinationRequest' from JSON`,
  );
}
