/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetOperatorEventRequest = {
  /**
   * The ID of the operator event.
   */
  eventId: string;
};

/** @internal */
export const GetOperatorEventRequest$inboundSchema: z.ZodType<
  GetOperatorEventRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  event_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "event_id": "eventId",
  });
});
/** @internal */
export type GetOperatorEventRequest$Outbound = {
  event_id: string;
};

/** @internal */
export const GetOperatorEventRequest$outboundSchema: z.ZodType<
  GetOperatorEventRequest$Outbound,
  z.ZodTypeDef,
  GetOperatorEventRequest
> = z.object({
  eventId: z.string(),
}).transform((v) => {
  return remap$(v, {
    eventId: "event_id",
  });
});

export function getOperatorEventRequestToJSON(
  getOperatorEventRequest: GetOperatorEventRequest,
): string {
  return JSON.stringify(
    GetOperatorEventRequest$outboundSchema.parse(getOperatorEventRequest),
  );
}
export function getOperatorEventRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetOperatorEventRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOperatorEventRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOperatorEventRequest' from JSON`,
  );
}
