// Package mcpevents proxies the MCP Events methods of an MCP server to Outpost.
//
// An MCP server offers MCP Events by answering events/list, events/subscribe
// and events/unsubscribe. Outpost does the work behind three endpoints; this
// package forwards the methods to them:
//
//   - [Client] is a raw-JSON client for the three endpoints. Results are
//     returned as the exact JSON Outpost sent, ready to forward verbatim.
//   - [Handlers] are transport-agnostic handlers taking the authenticated
//     principal and the raw MCP params, returning the MCP result or an
//     [*RPCError] to send back as the JSON-RPC error.
//   - Package mcpsdk registers the handlers on a server built with the
//     official Go MCP SDK (github.com/modelcontextprotocol/go-sdk). It is a
//     module of its own, so only its users depend on that SDK.
//
// The package is hand-written, not generated by Speakeasy: it is not tracked
// in .speakeasy/gen.lock, so it survives SDK regeneration. It depends only on
// the standard library.
package mcpevents
