apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-api"
  labels:
    app: outpost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outpost-api
  template:
    metadata:
      labels:
        app: outpost-api
    spec:
      containers:
        - name: "{{ .Chart.Name }}-api"
          image: "{{ .Values.outpost.image.repository }}:{{ .Values.outpost.image.tag }}"
          imagePullPolicy: {{ .Values.outpost.image.pullPolicy }}
          command: ["/bin/outpost", "--service", "api"]
          env:
{{ include "outpost.env" . | indent 12 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-delivery"
  labels:
    app: outpost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outpost-delivery
  template:
    metadata:
      labels:
        app: outpost-delivery
    spec:
      containers:
        - name: "{{ .Chart.Name }}-delivery"
          image: "{{ .Values.outpost.image.repository }}:{{ .Values.outpost.image.tag }}"
          imagePullPolicy: {{ .Values.outpost.image.pullPolicy }}
          command: ["/bin/outpost", "--service", "delivery"]
          env:
{{ include "outpost.env" . | indent 12 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-log"
  labels:
    app: outpost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outpost-log
  template:
    metadata:
      labels:
        app: outpost-log
    spec:
      containers:
        - name: "{{ .Chart.Name }}-log"
          image: "{{ .Values.outpost.image.repository }}:{{ .Values.outpost.image.tag }}"
          imagePullPolicy: {{ .Values.outpost.image.pullPolicy }}
          command: ["/bin/outpost", "--service", "log"]
          env:
{{ include "outpost.env" . | indent 12 }}
