apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: eventkit
spec:
  type: {{ .Values.eventkit.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.eventkit.service.port }}
  selector:
    app: eventkit-api
