// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/utils"
)

type Awss3Credentials struct {
	// AWS Access Key ID.
	Key string `json:"key"`
	// AWS Secret Access Key.
	Secret string `json:"secret"`
	// Optional AWS Session Token (for temporary credentials).
	Session *string `json:"session,omitempty"`
}

func (a Awss3Credentials) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *Awss3Credentials) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"key", "secret"}); err != nil {
		return err
	}
	return nil
}

func (a *Awss3Credentials) GetKey() string {
	if a == nil {
		return ""
	}
	return a.Key
}

func (a *Awss3Credentials) GetSecret() string {
	if a == nil {
		return ""
	}
	return a.Secret
}

func (a *Awss3Credentials) GetSession() *string {
	if a == nil {
		return nil
	}
	return a.Session
}
