// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/utils"
)

type CloudflareQueuesCredentials struct {
	// Cloudflare API Token with the Account > Queues > Edit (Queues Write) permission, scoped to the target account.
	APIToken string `json:"api_token"`
}

func (c CloudflareQueuesCredentials) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CloudflareQueuesCredentials) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"api_token"}); err != nil {
		return err
	}
	return nil
}

func (c *CloudflareQueuesCredentials) GetAPIToken() string {
	if c == nil {
		return ""
	}
	return c.APIToken
}
