// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/utils"
	"time"
)

// DestinationAWSSQSType - Type of the destination.
type DestinationAWSSQSType string

const (
	DestinationAWSSQSTypeAwsSqs DestinationAWSSQSType = "aws_sqs"
)

func (e DestinationAWSSQSType) ToPointer() *DestinationAWSSQSType {
	return &e
}
func (e *DestinationAWSSQSType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "aws_sqs":
		*e = DestinationAWSSQSType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DestinationAWSSQSType: %v", v)
	}
}

type DestinationAWSSQS struct {
	// Control plane generated ID or user provided ID for the destination.
	ID string `json:"id"`
	// Type of the destination.
	Type DestinationAWSSQSType `json:"type"`
	// "*" or an array of enabled topics.
	Topics Topics `json:"topics"`
	// Optional JSON schema filter for event matching. Events must match this filter to be delivered to this destination.
	// Supports operators: $eq, $neq, $gt, $gte, $lt, $lte, $in, $nin, $startsWith, $endsWith, $exist, $or, $and, $not.
	// If null or empty, all events matching the topic filter will be delivered.
	// To remove an existing filter when updating a destination, set filter to an empty object `{}`.
	//
	Filter map[string]any `json:"filter,omitempty"`
	// ISO Date when the destination was disabled, or null if enabled.
	DisabledAt *time.Time `json:"disabled_at"`
	// ISO Date when the destination was created.
	CreatedAt time.Time `json:"created_at"`
	// ISO Date when the destination was last updated.
	UpdatedAt   time.Time         `json:"updated_at"`
	Config      AWSSQSConfig      `json:"config"`
	Credentials AWSSQSCredentials `json:"credentials"`
	// Static key-value pairs merged into event metadata on every delivery.
	DeliveryMetadata map[string]string `json:"delivery_metadata,omitempty"`
	// Arbitrary contextual information stored with the destination.
	Metadata map[string]string `json:"metadata,omitempty"`
	// A human-readable representation of the destination target (SQS queue name). Read-only.
	Target *string `json:"target,omitempty"`
	// A URL link to the destination target (AWS Console link to the queue). Read-only.
	TargetURL *string `json:"target_url,omitempty"`
}

func (d DestinationAWSSQS) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DestinationAWSSQS) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"id", "type", "topics", "created_at", "updated_at", "config", "credentials"}); err != nil {
		return err
	}
	return nil
}

func (d *DestinationAWSSQS) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DestinationAWSSQS) GetType() DestinationAWSSQSType {
	if d == nil {
		return DestinationAWSSQSType("")
	}
	return d.Type
}

func (d *DestinationAWSSQS) GetTopics() Topics {
	if d == nil {
		return Topics{}
	}
	return d.Topics
}

func (d *DestinationAWSSQS) GetFilter() map[string]any {
	if d == nil {
		return nil
	}
	return d.Filter
}

func (d *DestinationAWSSQS) GetDisabledAt() *time.Time {
	if d == nil {
		return nil
	}
	return d.DisabledAt
}

func (d *DestinationAWSSQS) GetCreatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.CreatedAt
}

func (d *DestinationAWSSQS) GetUpdatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.UpdatedAt
}

func (d *DestinationAWSSQS) GetConfig() AWSSQSConfig {
	if d == nil {
		return AWSSQSConfig{}
	}
	return d.Config
}

func (d *DestinationAWSSQS) GetCredentials() AWSSQSCredentials {
	if d == nil {
		return AWSSQSCredentials{}
	}
	return d.Credentials
}

func (d *DestinationAWSSQS) GetDeliveryMetadata() map[string]string {
	if d == nil {
		return nil
	}
	return d.DeliveryMetadata
}

func (d *DestinationAWSSQS) GetMetadata() map[string]string {
	if d == nil {
		return nil
	}
	return d.Metadata
}

func (d *DestinationAWSSQS) GetTarget() *string {
	if d == nil {
		return nil
	}
	return d.Target
}

func (d *DestinationAWSSQS) GetTargetURL() *string {
	if d == nil {
		return nil
	}
	return d.TargetURL
}
