// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/utils"
	"github.com/hookdeck/outpost/sdks/outpost-go/optionalnullable"
)

type DestinationUpdateAzureServiceBus struct {
	// "*" or an array of enabled topics.
	Topics *Topics `json:"topics,omitempty"`
	// Optional JSON schema filter for event matching. Events must match this filter to be delivered to this destination.
	// Supports operators: $eq, $neq, $gt, $gte, $lt, $lte, $in, $nin, $startsWith, $endsWith, $exist, $or, $and, $not.
	// If null or empty, all events matching the topic filter will be delivered.
	// Uses full-replacement semantics on update: send a new object to replace, null or `{}` to clear, omit for no change.
	//
	Filter      optionalnullable.OptionalNullable[map[string]any] `json:"filter,omitempty"`
	Config      *AzureServiceBusConfig                            `json:"config,omitempty"`
	Credentials *AzureServiceBusCredentials                       `json:"credentials,omitempty"`
	// Static key-value pairs merged into event metadata on every attempt. Uses JSON merge-patch semantics (RFC 7396): send keys to add/update, null values to delete keys, null for entire field to clear all. Omit or send {} for no change.
	DeliveryMetadata optionalnullable.OptionalNullable[map[string]*string] `json:"delivery_metadata,omitempty"`
	// Arbitrary contextual information stored with the destination. Uses JSON merge-patch semantics (RFC 7396): send keys to add/update, null values to delete keys, null for entire field to clear all. Omit or send {} for no change.
	Metadata optionalnullable.OptionalNullable[map[string]*string] `json:"metadata,omitempty"`
}

func (d DestinationUpdateAzureServiceBus) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DestinationUpdateAzureServiceBus) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DestinationUpdateAzureServiceBus) GetTopics() *Topics {
	if d == nil {
		return nil
	}
	return d.Topics
}

func (d *DestinationUpdateAzureServiceBus) GetFilter() optionalnullable.OptionalNullable[map[string]any] {
	if d == nil {
		return nil
	}
	return d.Filter
}

func (d *DestinationUpdateAzureServiceBus) GetConfig() *AzureServiceBusConfig {
	if d == nil {
		return nil
	}
	return d.Config
}

func (d *DestinationUpdateAzureServiceBus) GetCredentials() *AzureServiceBusCredentials {
	if d == nil {
		return nil
	}
	return d.Credentials
}

func (d *DestinationUpdateAzureServiceBus) GetDeliveryMetadata() optionalnullable.OptionalNullable[map[string]*string] {
	if d == nil {
		return nil
	}
	return d.DeliveryMetadata
}

func (d *DestinationUpdateAzureServiceBus) GetMetadata() optionalnullable.OptionalNullable[map[string]*string] {
	if d == nil {
		return nil
	}
	return d.Metadata
}
