// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/utils"
	"github.com/hookdeck/outpost/sdks/outpost-go/optionalnullable"
)

// DestinationCreateAWSSQSType - Type of the destination. Must be 'aws_sqs'.
type DestinationCreateAWSSQSType string

const (
	DestinationCreateAWSSQSTypeAwsSqs DestinationCreateAWSSQSType = "aws_sqs"
)

func (e DestinationCreateAWSSQSType) ToPointer() *DestinationCreateAWSSQSType {
	return &e
}
func (e *DestinationCreateAWSSQSType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "aws_sqs":
		*e = DestinationCreateAWSSQSType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DestinationCreateAWSSQSType: %v", v)
	}
}

type DestinationCreateAWSSQS struct {
	// Optional user-provided ID. An ID will be generated if empty.
	ID *string `json:"id,omitempty"`
	// Type of the destination. Must be 'aws_sqs'.
	Type DestinationCreateAWSSQSType `json:"type"`
	// "*" or an array of enabled topics.
	Topics Topics `json:"topics"`
	// Optional JSON schema filter for event matching. Events must match this filter to be delivered to this destination.
	// Supports operators: $eq, $neq, $gt, $gte, $lt, $lte, $in, $nin, $startsWith, $endsWith, $exist, $or, $and, $not.
	// If null or empty, all events matching the topic filter will be delivered.
	// Uses full-replacement semantics on update: send a new object to replace, null or `{}` to clear, omit for no change.
	//
	Filter      optionalnullable.OptionalNullable[map[string]any] `json:"filter,omitempty"`
	Config      AWSSQSConfig                                      `json:"config"`
	Credentials AWSSQSCredentials                                 `json:"credentials"`
	// Static key-value pairs merged into event metadata on every attempt.
	DeliveryMetadata optionalnullable.OptionalNullable[map[string]string] `json:"delivery_metadata,omitempty"`
	// Arbitrary contextual information stored with the destination.
	Metadata optionalnullable.OptionalNullable[map[string]string] `json:"metadata,omitempty"`
}

func (d DestinationCreateAWSSQS) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DestinationCreateAWSSQS) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"type", "topics", "config", "credentials"}); err != nil {
		return err
	}
	return nil
}

func (d *DestinationCreateAWSSQS) GetID() *string {
	if d == nil {
		return nil
	}
	return d.ID
}

func (d *DestinationCreateAWSSQS) GetType() DestinationCreateAWSSQSType {
	if d == nil {
		return DestinationCreateAWSSQSType("")
	}
	return d.Type
}

func (d *DestinationCreateAWSSQS) GetTopics() Topics {
	if d == nil {
		return Topics{}
	}
	return d.Topics
}

func (d *DestinationCreateAWSSQS) GetFilter() optionalnullable.OptionalNullable[map[string]any] {
	if d == nil {
		return nil
	}
	return d.Filter
}

func (d *DestinationCreateAWSSQS) GetConfig() AWSSQSConfig {
	if d == nil {
		return AWSSQSConfig{}
	}
	return d.Config
}

func (d *DestinationCreateAWSSQS) GetCredentials() AWSSQSCredentials {
	if d == nil {
		return AWSSQSCredentials{}
	}
	return d.Credentials
}

func (d *DestinationCreateAWSSQS) GetDeliveryMetadata() optionalnullable.OptionalNullable[map[string]string] {
	if d == nil {
		return nil
	}
	return d.DeliveryMetadata
}

func (d *DestinationCreateAWSSQS) GetMetadata() optionalnullable.OptionalNullable[map[string]string] {
	if d == nil {
		return nil
	}
	return d.Metadata
}
