// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/utils"
	"github.com/hookdeck/outpost/sdks/outpost-go/optionalnullable"
	"time"
)

// DestinationCloudflareQueuesType - Type of the destination.
type DestinationCloudflareQueuesType string

const (
	DestinationCloudflareQueuesTypeCloudflareQueues DestinationCloudflareQueuesType = "cloudflare_queues"
)

func (e DestinationCloudflareQueuesType) ToPointer() *DestinationCloudflareQueuesType {
	return &e
}
func (e *DestinationCloudflareQueuesType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "cloudflare_queues":
		*e = DestinationCloudflareQueuesType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DestinationCloudflareQueuesType: %v", v)
	}
}

type DestinationCloudflareQueues struct {
	// Control plane generated ID or user provided ID for the destination.
	ID string `json:"id"`
	// Type of the destination.
	Type DestinationCloudflareQueuesType `json:"type"`
	// "*" or an array of enabled topics. Topic strings can include "*" as a wildcard matching any run of characters. When available topics are configured, wildcard patterns must match at least one available topic.
	Topics Topics `json:"topics"`
	// Optional JSON schema filter for event matching. Events must match this filter to be delivered to this destination.
	// Supports operators: $eq, $neq, $gt, $gte, $lt, $lte, $in, $nin, $startsWith, $endsWith, $exist, $or, $and, $not.
	// If null or empty, all events matching the topic filter will be delivered.
	// Uses full-replacement semantics on update: send a new object to replace, null or `{}` to clear, omit for no change.
	//
	Filter optionalnullable.OptionalNullable[map[string]any] `json:"filter,omitempty"`
	// ISO Date when the destination was disabled, or null if enabled.
	DisabledAt *time.Time `json:"disabled_at"`
	// ISO Date when the destination was created.
	CreatedAt time.Time `json:"created_at"`
	// ISO Date when the destination was last updated.
	UpdatedAt   time.Time                   `json:"updated_at"`
	Config      CloudflareQueuesConfig      `json:"config"`
	Credentials CloudflareQueuesCredentials `json:"credentials"`
	// Static key-value pairs merged into event metadata on every attempt.
	DeliveryMetadata optionalnullable.OptionalNullable[map[string]string] `json:"delivery_metadata,omitempty"`
	// Arbitrary contextual information stored with the destination.
	Metadata optionalnullable.OptionalNullable[map[string]string] `json:"metadata,omitempty"`
	// A human-readable representation of the destination target (Cloudflare Queue ID). Read-only.
	Target *string `json:"target,omitempty"`
	// A URL link to the Cloudflare dashboard queues list for the account. Read-only.
	TargetURL optionalnullable.OptionalNullable[string] `json:"target_url,omitempty"`
}

func (d DestinationCloudflareQueues) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DestinationCloudflareQueues) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"id", "type", "topics", "created_at", "updated_at", "config", "credentials"}); err != nil {
		return err
	}
	return nil
}

func (d *DestinationCloudflareQueues) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DestinationCloudflareQueues) GetType() DestinationCloudflareQueuesType {
	if d == nil {
		return DestinationCloudflareQueuesType("")
	}
	return d.Type
}

func (d *DestinationCloudflareQueues) GetTopics() Topics {
	if d == nil {
		return Topics{}
	}
	return d.Topics
}

func (d *DestinationCloudflareQueues) GetFilter() optionalnullable.OptionalNullable[map[string]any] {
	if d == nil {
		return nil
	}
	return d.Filter
}

func (d *DestinationCloudflareQueues) GetDisabledAt() *time.Time {
	if d == nil {
		return nil
	}
	return d.DisabledAt
}

func (d *DestinationCloudflareQueues) GetCreatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.CreatedAt
}

func (d *DestinationCloudflareQueues) GetUpdatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.UpdatedAt
}

func (d *DestinationCloudflareQueues) GetConfig() CloudflareQueuesConfig {
	if d == nil {
		return CloudflareQueuesConfig{}
	}
	return d.Config
}

func (d *DestinationCloudflareQueues) GetCredentials() CloudflareQueuesCredentials {
	if d == nil {
		return CloudflareQueuesCredentials{}
	}
	return d.Credentials
}

func (d *DestinationCloudflareQueues) GetDeliveryMetadata() optionalnullable.OptionalNullable[map[string]string] {
	if d == nil {
		return nil
	}
	return d.DeliveryMetadata
}

func (d *DestinationCloudflareQueues) GetMetadata() optionalnullable.OptionalNullable[map[string]string] {
	if d == nil {
		return nil
	}
	return d.Metadata
}

func (d *DestinationCloudflareQueues) GetTarget() *string {
	if d == nil {
		return nil
	}
	return d.Target
}

func (d *DestinationCloudflareQueues) GetTargetURL() optionalnullable.OptionalNullable[string] {
	if d == nil {
		return nil
	}
	return d.TargetURL
}
