// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/utils"
)

type DestinationUpdateAWSSQS struct {
	// "*" or an array of enabled topics.
	Topics *Topics `json:"topics,omitempty"`
	// Optional JSON schema filter for event matching. Events must match this filter to be delivered to this destination.
	// Supports operators: $eq, $neq, $gt, $gte, $lt, $lte, $in, $nin, $startsWith, $endsWith, $exist, $or, $and, $not.
	// If null or empty, all events matching the topic filter will be delivered.
	// To remove an existing filter when updating a destination, set filter to an empty object `{}`.
	//
	Filter      map[string]any     `json:"filter,omitempty"`
	Config      *AWSSQSConfig      `json:"config,omitempty"`
	Credentials *AWSSQSCredentials `json:"credentials,omitempty"`
	// Static key-value pairs merged into event metadata on every attempt.
	DeliveryMetadata map[string]string `json:"delivery_metadata,omitempty"`
	// Arbitrary contextual information stored with the destination.
	Metadata map[string]string `json:"metadata,omitempty"`
}

func (d DestinationUpdateAWSSQS) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DestinationUpdateAWSSQS) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DestinationUpdateAWSSQS) GetTopics() *Topics {
	if d == nil {
		return nil
	}
	return d.Topics
}

func (d *DestinationUpdateAWSSQS) GetFilter() map[string]any {
	if d == nil {
		return nil
	}
	return d.Filter
}

func (d *DestinationUpdateAWSSQS) GetConfig() *AWSSQSConfig {
	if d == nil {
		return nil
	}
	return d.Config
}

func (d *DestinationUpdateAWSSQS) GetCredentials() *AWSSQSCredentials {
	if d == nil {
		return nil
	}
	return d.Credentials
}

func (d *DestinationUpdateAWSSQS) GetDeliveryMetadata() map[string]string {
	if d == nil {
		return nil
	}
	return d.DeliveryMetadata
}

func (d *DestinationUpdateAWSSQS) GetMetadata() map[string]string {
	if d == nil {
		return nil
	}
	return d.Metadata
}
