// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/utils"
	"github.com/hookdeck/outpost/sdks/outpost-go/optionalnullable"
	"time"
)

// DestinationCreateAwss3Type - Type of the destination. Must be 'aws_s3'.
type DestinationCreateAwss3Type string

const (
	DestinationCreateAwss3TypeAwsS3 DestinationCreateAwss3Type = "aws_s3"
)

func (e DestinationCreateAwss3Type) ToPointer() *DestinationCreateAwss3Type {
	return &e
}
func (e *DestinationCreateAwss3Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "aws_s3":
		*e = DestinationCreateAwss3Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DestinationCreateAwss3Type: %v", v)
	}
}

type DestinationCreateAwss3 struct {
	// Optional user-provided ID. An ID will be generated if empty.
	ID *string `json:"id,omitempty"`
	// Type of the destination. Must be 'aws_s3'.
	Type DestinationCreateAwss3Type `json:"type"`
	// "*" or an array of enabled topics. Topic strings can include "*" as a wildcard matching any run of characters. When available topics are configured, wildcard patterns must match at least one available topic.
	Topics Topics `json:"topics"`
	// Optional JSON schema filter for event matching. Events must match this filter to be delivered to this destination.
	// Supports operators: $eq, $neq, $gt, $gte, $lt, $lte, $in, $nin, $startsWith, $endsWith, $exist, $or, $and, $not.
	// If null or empty, all events matching the topic filter will be delivered.
	// Uses full-replacement semantics on update: send a new object to replace, null or `{}` to clear, omit for no change.
	//
	Filter      optionalnullable.OptionalNullable[map[string]any] `json:"filter,omitempty"`
	Config      Awss3Config                                       `json:"config"`
	Credentials Awss3Credentials                                  `json:"credentials"`
	// Static key-value pairs merged into event metadata on every attempt.
	DeliveryMetadata optionalnullable.OptionalNullable[map[string]string] `json:"delivery_metadata,omitempty"`
	// Arbitrary contextual information stored with the destination.
	Metadata optionalnullable.OptionalNullable[map[string]string] `json:"metadata,omitempty"`
	// Optional override for the creation timestamp. Intended for importing destinations from another system. Must not be in the future. **Admin (API key) auth only — sending this with JWT auth returns 403.** Defaults to the current time when omitted.
	CreatedAt optionalnullable.OptionalNullable[time.Time] `json:"created_at,omitempty"`
	// Optional override for the last-updated timestamp. Intended for importing destinations. Must not be in the future. **Admin (API key) auth only — sending this with JWT auth returns 403.** Defaults to created_at when omitted.
	UpdatedAt optionalnullable.OptionalNullable[time.Time] `json:"updated_at,omitempty"`
	// If set, the destination is created in a disabled state with this timestamp. Must not be in the future. Defaults to null (enabled).
	DisabledAt optionalnullable.OptionalNullable[time.Time] `json:"disabled_at,omitempty"`
}

func (d DestinationCreateAwss3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DestinationCreateAwss3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"type", "topics", "config", "credentials"}); err != nil {
		return err
	}
	return nil
}

func (d *DestinationCreateAwss3) GetID() *string {
	if d == nil {
		return nil
	}
	return d.ID
}

func (d *DestinationCreateAwss3) GetType() DestinationCreateAwss3Type {
	if d == nil {
		return DestinationCreateAwss3Type("")
	}
	return d.Type
}

func (d *DestinationCreateAwss3) GetTopics() Topics {
	if d == nil {
		return Topics{}
	}
	return d.Topics
}

func (d *DestinationCreateAwss3) GetFilter() optionalnullable.OptionalNullable[map[string]any] {
	if d == nil {
		return nil
	}
	return d.Filter
}

func (d *DestinationCreateAwss3) GetConfig() Awss3Config {
	if d == nil {
		return Awss3Config{}
	}
	return d.Config
}

func (d *DestinationCreateAwss3) GetCredentials() Awss3Credentials {
	if d == nil {
		return Awss3Credentials{}
	}
	return d.Credentials
}

func (d *DestinationCreateAwss3) GetDeliveryMetadata() optionalnullable.OptionalNullable[map[string]string] {
	if d == nil {
		return nil
	}
	return d.DeliveryMetadata
}

func (d *DestinationCreateAwss3) GetMetadata() optionalnullable.OptionalNullable[map[string]string] {
	if d == nil {
		return nil
	}
	return d.Metadata
}

func (d *DestinationCreateAwss3) GetCreatedAt() optionalnullable.OptionalNullable[time.Time] {
	if d == nil {
		return nil
	}
	return d.CreatedAt
}

func (d *DestinationCreateAwss3) GetUpdatedAt() optionalnullable.OptionalNullable[time.Time] {
	if d == nil {
		return nil
	}
	return d.UpdatedAt
}

func (d *DestinationCreateAwss3) GetDisabledAt() optionalnullable.OptionalNullable[time.Time] {
	if d == nil {
		return nil
	}
	return d.DisabledAt
}

// #region class-body-destinationcreateawss3
// #endregion class-body-destinationcreateawss3
