// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/utils"
	"github.com/hookdeck/outpost/sdks/outpost-go/optionalnullable"
	"time"
)

// DestinationUpdateRabbitMQType - Destination type discriminator. Must equal the existing destination's type — type itself cannot be changed via PATCH.
type DestinationUpdateRabbitMQType string

const (
	DestinationUpdateRabbitMQTypeRabbitmq DestinationUpdateRabbitMQType = "rabbitmq"
)

func (e DestinationUpdateRabbitMQType) ToPointer() *DestinationUpdateRabbitMQType {
	return &e
}
func (e *DestinationUpdateRabbitMQType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "rabbitmq":
		*e = DestinationUpdateRabbitMQType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DestinationUpdateRabbitMQType: %v", v)
	}
}

type DestinationUpdateRabbitMQ struct {
	// Destination type discriminator. Must equal the existing destination's type — type itself cannot be changed via PATCH.
	Type DestinationUpdateRabbitMQType `json:"type"`
	// "*" or an array of enabled topics. Topic strings can include "*" as a wildcard matching any run of characters. When available topics are configured, wildcard patterns must match at least one available topic.
	Topics *Topics `json:"topics,omitempty"`
	// Optional JSON schema filter for event matching. Events must match this filter to be delivered to this destination.
	// Supports operators: $eq, $neq, $gt, $gte, $lt, $lte, $in, $nin, $startsWith, $endsWith, $exist, $or, $and, $not.
	// If null or empty, all events matching the topic filter will be delivered.
	// Uses full-replacement semantics on update: send a new object to replace, null or `{}` to clear, omit for no change.
	//
	Filter optionalnullable.OptionalNullable[map[string]any] `json:"filter,omitempty"`
	// Partial RabbitMQ config for PATCH updates (RFC 7396 merge-patch).
	Config *RabbitMQConfigUpdate `json:"config,omitempty"`
	// Partial RabbitMQ credentials for PATCH updates (RFC 7396 merge-patch).
	Credentials *RabbitMQCredentialsUpdate `json:"credentials,omitempty"`
	// Static key-value pairs merged into event metadata on every attempt. Uses JSON merge-patch semantics (RFC 7396): send keys to add/update, null values to delete keys, null for entire field to clear all. Omit or send {} for no change.
	DeliveryMetadata optionalnullable.OptionalNullable[map[string]*string] `json:"delivery_metadata,omitempty"`
	// Arbitrary contextual information stored with the destination. Uses JSON merge-patch semantics (RFC 7396): send keys to add/update, null values to delete keys, null for entire field to clear all. Omit or send {} for no change.
	Metadata optionalnullable.OptionalNullable[map[string]*string] `json:"metadata,omitempty"`
	// Update the disabled state of the destination. Send a timestamp (must not be in the future) to disable, null to enable, or omit to leave unchanged.
	DisabledAt optionalnullable.OptionalNullable[time.Time] `json:"disabled_at,omitempty"`
}

func (d DestinationUpdateRabbitMQ) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DestinationUpdateRabbitMQ) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (d *DestinationUpdateRabbitMQ) GetType() DestinationUpdateRabbitMQType {
	if d == nil {
		return DestinationUpdateRabbitMQType("")
	}
	return d.Type
}

func (d *DestinationUpdateRabbitMQ) GetTopics() *Topics {
	if d == nil {
		return nil
	}
	return d.Topics
}

func (d *DestinationUpdateRabbitMQ) GetFilter() optionalnullable.OptionalNullable[map[string]any] {
	if d == nil {
		return nil
	}
	return d.Filter
}

func (d *DestinationUpdateRabbitMQ) GetConfig() *RabbitMQConfigUpdate {
	if d == nil {
		return nil
	}
	return d.Config
}

func (d *DestinationUpdateRabbitMQ) GetCredentials() *RabbitMQCredentialsUpdate {
	if d == nil {
		return nil
	}
	return d.Credentials
}

func (d *DestinationUpdateRabbitMQ) GetDeliveryMetadata() optionalnullable.OptionalNullable[map[string]*string] {
	if d == nil {
		return nil
	}
	return d.DeliveryMetadata
}

func (d *DestinationUpdateRabbitMQ) GetMetadata() optionalnullable.OptionalNullable[map[string]*string] {
	if d == nil {
		return nil
	}
	return d.Metadata
}

func (d *DestinationUpdateRabbitMQ) GetDisabledAt() optionalnullable.OptionalNullable[time.Time] {
	if d == nil {
		return nil
	}
	return d.DisabledAt
}
