// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/utils"
	"github.com/hookdeck/outpost/sdks/outpost-go/optionalnullable"
	"time"
)

// DestinationCreateAWSEventBridgeType - Type of the destination. Must be 'aws_eventbridge'.
type DestinationCreateAWSEventBridgeType string

const (
	DestinationCreateAWSEventBridgeTypeAwsEventbridge DestinationCreateAWSEventBridgeType = "aws_eventbridge"
)

func (e DestinationCreateAWSEventBridgeType) ToPointer() *DestinationCreateAWSEventBridgeType {
	return &e
}
func (e *DestinationCreateAWSEventBridgeType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "aws_eventbridge":
		*e = DestinationCreateAWSEventBridgeType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DestinationCreateAWSEventBridgeType: %v", v)
	}
}

type DestinationCreateAWSEventBridge struct {
	// Optional user-provided ID. An ID will be generated if empty.
	ID *string `json:"id,omitempty"`
	// Type of the destination. Must be 'aws_eventbridge'.
	Type DestinationCreateAWSEventBridgeType `json:"type"`
	// "*" or an array of enabled topics. Topic strings can include "*" as a wildcard matching any run of characters. When available topics are configured, wildcard patterns must match at least one available topic.
	Topics Topics `json:"topics"`
	// Optional JSON schema filter for event matching. Events must match this filter to be delivered to this destination.
	// Supports operators: $eq, $neq, $gt, $gte, $lt, $lte, $in, $nin, $startsWith, $endsWith, $exist, $or, $and, $not.
	// If null or empty, all events matching the topic filter will be delivered.
	// Uses full-replacement semantics on update: send a new object to replace, null or `{}` to clear, omit for no change.
	//
	Filter      optionalnullable.OptionalNullable[map[string]any] `json:"filter,omitempty"`
	Config      AWSEventBridgeConfig                              `json:"config"`
	Credentials AWSEventBridgeCredentials                         `json:"credentials"`
	// Static key-value pairs merged into event metadata on every attempt.
	DeliveryMetadata optionalnullable.OptionalNullable[map[string]string] `json:"delivery_metadata,omitempty"`
	// Arbitrary contextual information stored with the destination.
	Metadata optionalnullable.OptionalNullable[map[string]string] `json:"metadata,omitempty"`
	// Optional override for the creation timestamp. Intended for importing destinations from another system. Must not be in the future. **Admin (API key) auth only — sending this with JWT auth returns 403.** Defaults to the current time when omitted.
	CreatedAt optionalnullable.OptionalNullable[time.Time] `json:"created_at,omitempty"`
	// Optional override for the last-updated timestamp. Intended for importing destinations. Must not be in the future. **Admin (API key) auth only — sending this with JWT auth returns 403.** Defaults to created_at when omitted.
	UpdatedAt optionalnullable.OptionalNullable[time.Time] `json:"updated_at,omitempty"`
	// If set, the destination is created in a disabled state with this timestamp. Must not be in the future. Defaults to null (enabled).
	DisabledAt optionalnullable.OptionalNullable[time.Time] `json:"disabled_at,omitempty"`
}

func (d DestinationCreateAWSEventBridge) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DestinationCreateAWSEventBridge) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"type", "topics", "config", "credentials"}); err != nil {
		return err
	}
	return nil
}

func (d *DestinationCreateAWSEventBridge) GetID() *string {
	if d == nil {
		return nil
	}
	return d.ID
}

func (d *DestinationCreateAWSEventBridge) GetType() DestinationCreateAWSEventBridgeType {
	if d == nil {
		return DestinationCreateAWSEventBridgeType("")
	}
	return d.Type
}

func (d *DestinationCreateAWSEventBridge) GetTopics() Topics {
	if d == nil {
		return Topics{}
	}
	return d.Topics
}

func (d *DestinationCreateAWSEventBridge) GetFilter() optionalnullable.OptionalNullable[map[string]any] {
	if d == nil {
		return nil
	}
	return d.Filter
}

func (d *DestinationCreateAWSEventBridge) GetConfig() AWSEventBridgeConfig {
	if d == nil {
		return AWSEventBridgeConfig{}
	}
	return d.Config
}

func (d *DestinationCreateAWSEventBridge) GetCredentials() AWSEventBridgeCredentials {
	if d == nil {
		return AWSEventBridgeCredentials{}
	}
	return d.Credentials
}

func (d *DestinationCreateAWSEventBridge) GetDeliveryMetadata() optionalnullable.OptionalNullable[map[string]string] {
	if d == nil {
		return nil
	}
	return d.DeliveryMetadata
}

func (d *DestinationCreateAWSEventBridge) GetMetadata() optionalnullable.OptionalNullable[map[string]string] {
	if d == nil {
		return nil
	}
	return d.Metadata
}

func (d *DestinationCreateAWSEventBridge) GetCreatedAt() optionalnullable.OptionalNullable[time.Time] {
	if d == nil {
		return nil
	}
	return d.CreatedAt
}

func (d *DestinationCreateAWSEventBridge) GetUpdatedAt() optionalnullable.OptionalNullable[time.Time] {
	if d == nil {
		return nil
	}
	return d.UpdatedAt
}

func (d *DestinationCreateAWSEventBridge) GetDisabledAt() optionalnullable.OptionalNullable[time.Time] {
	if d == nil {
		return nil
	}
	return d.DisabledAt
}
