// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/utils"
	"time"
)

// EventSummary - Event object without data (returned when include=event).
type EventSummary struct {
	ID *string `json:"id,omitempty"`
	// The tenant this event belongs to.
	TenantID *string `json:"tenant_id,omitempty"`
	// The destination this event was delivered to.
	DestinationID *string `json:"destination_id,omitempty"`
	Topic         *string `json:"topic,omitempty"`
	// Time the event was received.
	Time *time.Time `json:"time,omitempty"`
	// Whether this event can be retried.
	EligibleForRetry *bool             `json:"eligible_for_retry,omitempty"`
	Metadata         map[string]string `json:"metadata,omitempty"`
}

func (e EventSummary) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EventSummary) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EventSummary) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *EventSummary) GetTenantID() *string {
	if e == nil {
		return nil
	}
	return e.TenantID
}

func (e *EventSummary) GetDestinationID() *string {
	if e == nil {
		return nil
	}
	return e.DestinationID
}

func (e *EventSummary) GetTopic() *string {
	if e == nil {
		return nil
	}
	return e.Topic
}

func (e *EventSummary) GetTime() *time.Time {
	if e == nil {
		return nil
	}
	return e.Time
}

func (e *EventSummary) GetEligibleForRetry() *bool {
	if e == nil {
		return nil
	}
	return e.EligibleForRetry
}

func (e *EventSummary) GetMetadata() map[string]string {
	if e == nil {
		return nil
	}
	return e.Metadata
}
