// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/utils"
	"time"
)

type EventStatus string

const (
	EventStatusSuccess EventStatus = "success"
	EventStatusFailed  EventStatus = "failed"
)

func (e EventStatus) ToPointer() *EventStatus {
	return &e
}
func (e *EventStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "success":
		fallthrough
	case "failed":
		*e = EventStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EventStatus: %v", v)
	}
}

type Event struct {
	ID            *string `json:"id,omitempty"`
	DestinationID *string `json:"destination_id,omitempty"`
	Topic         *string `json:"topic,omitempty"`
	// Time the event was received/processed.
	Time *time.Time `json:"time,omitempty"`
	// Time the event was successfully delivered.
	SuccessfulAt *time.Time `json:"successful_at,omitempty"`
	// Key-value string pairs of metadata associated with the event.
	Metadata map[string]string `json:"metadata,omitempty"`
	Status   *EventStatus      `json:"status,omitempty"`
	// Freeform JSON data of the event.
	Data map[string]any `json:"data,omitempty"`
}

func (e Event) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *Event) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *Event) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *Event) GetDestinationID() *string {
	if e == nil {
		return nil
	}
	return e.DestinationID
}

func (e *Event) GetTopic() *string {
	if e == nil {
		return nil
	}
	return e.Topic
}

func (e *Event) GetTime() *time.Time {
	if e == nil {
		return nil
	}
	return e.Time
}

func (e *Event) GetSuccessfulAt() *time.Time {
	if e == nil {
		return nil
	}
	return e.SuccessfulAt
}

func (e *Event) GetMetadata() map[string]string {
	if e == nil {
		return nil
	}
	return e.Metadata
}

func (e *Event) GetStatus() *EventStatus {
	if e == nil {
		return nil
	}
	return e.Status
}

func (e *Event) GetData() map[string]any {
	if e == nil {
		return nil
	}
	return e.Data
}
