// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/utils"
)

// GCPPubSubCredentialsUpdate - Partial GCP Pub/Sub credentials for PATCH updates (RFC 7396 merge-patch).
type GCPPubSubCredentialsUpdate struct {
	// Service account key JSON. The entire JSON key file content as a string.
	ServiceAccountJSON *string `json:"service_account_json,omitempty"`
}

func (g GCPPubSubCredentialsUpdate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GCPPubSubCredentialsUpdate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GCPPubSubCredentialsUpdate) GetServiceAccountJSON() *string {
	if g == nil {
		return nil
	}
	return g.ServiceAccountJSON
}
