// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ManagedConfig - Managed configuration values for Outpost Cloud.
// This API is available only on the managed version.
// Self-hosted deployments configure these values using environment variables.
type ManagedConfig struct {
	AlertAutoDisableDestination                      *string `json:"ALERT_AUTO_DISABLE_DESTINATION,omitempty"`
	AlertCallbackURL                                 *string `json:"ALERT_CALLBACK_URL,omitempty"`
	AlertConsecutiveFailureCount                     *string `json:"ALERT_CONSECUTIVE_FAILURE_COUNT,omitempty"`
	DeliveryTimeoutSeconds                           *string `json:"DELIVERY_TIMEOUT_SECONDS,omitempty"`
	DestinationsAwsKinesisMetadataInPayload          *string `json:"DESTINATIONS_AWS_KINESIS_METADATA_IN_PAYLOAD,omitempty"`
	DestinationsIncludeMillisecondTimestamp          *string `json:"DESTINATIONS_INCLUDE_MILLISECOND_TIMESTAMP,omitempty"`
	DestinationsWebhookDisableDefaultEventIDHeader   *string `json:"DESTINATIONS_WEBHOOK_DISABLE_DEFAULT_EVENT_ID_HEADER,omitempty"`
	DestinationsWebhookDisableDefaultSignatureHeader *string `json:"DESTINATIONS_WEBHOOK_DISABLE_DEFAULT_SIGNATURE_HEADER,omitempty"`
	DestinationsWebhookDisableDefaultTimestampHeader *string `json:"DESTINATIONS_WEBHOOK_DISABLE_DEFAULT_TIMESTAMP_HEADER,omitempty"`
	DestinationsWebhookDisableDefaultTopicHeader     *string `json:"DESTINATIONS_WEBHOOK_DISABLE_DEFAULT_TOPIC_HEADER,omitempty"`
	DestinationsWebhookHeaderPrefix                  *string `json:"DESTINATIONS_WEBHOOK_HEADER_PREFIX,omitempty"`
	DestinationsWebhookMode                          *string `json:"DESTINATIONS_WEBHOOK_MODE,omitempty"`
	DestinationsWebhookProxyURL                      *string `json:"DESTINATIONS_WEBHOOK_PROXY_URL,omitempty"`
	DestinationsWebhookSignatureAlgorithm            *string `json:"DESTINATIONS_WEBHOOK_SIGNATURE_ALGORITHM,omitempty"`
	DestinationsWebhookSignatureContentTemplate      *string `json:"DESTINATIONS_WEBHOOK_SIGNATURE_CONTENT_TEMPLATE,omitempty"`
	DestinationsWebhookSignatureEncoding             *string `json:"DESTINATIONS_WEBHOOK_SIGNATURE_ENCODING,omitempty"`
	DestinationsWebhookSignatureHeaderTemplate       *string `json:"DESTINATIONS_WEBHOOK_SIGNATURE_HEADER_TEMPLATE,omitempty"`
	DestinationsWebhookSigningSecretTemplate         *string `json:"DESTINATIONS_WEBHOOK_SIGNING_SECRET_TEMPLATE,omitempty"`
	HTTPUserAgent                                    *string `json:"HTTP_USER_AGENT,omitempty"`
	IdgenAttemptPrefix                               *string `json:"IDGEN_ATTEMPT_PREFIX,omitempty"`
	IdgenDestinationPrefix                           *string `json:"IDGEN_DESTINATION_PREFIX,omitempty"`
	IdgenEventPrefix                                 *string `json:"IDGEN_EVENT_PREFIX,omitempty"`
	IdgenType                                        *string `json:"IDGEN_TYPE,omitempty"`
	MaxDestinationsPerTenant                         *string `json:"MAX_DESTINATIONS_PER_TENANT,omitempty"`
	OrganizationName                                 *string `json:"ORGANIZATION_NAME,omitempty"`
	PortalBrandColor                                 *string `json:"PORTAL_BRAND_COLOR,omitempty"`
	PortalDisableOutpostBranding                     *string `json:"PORTAL_DISABLE_OUTPOST_BRANDING,omitempty"`
	PortalFaviconURL                                 *string `json:"PORTAL_FAVICON_URL,omitempty"`
	PortalForceTheme                                 *string `json:"PORTAL_FORCE_THEME,omitempty"`
	PortalLogo                                       *string `json:"PORTAL_LOGO,omitempty"`
	PortalLogoDark                                   *string `json:"PORTAL_LOGO_DARK,omitempty"`
	PortalOrganizationName                           *string `json:"PORTAL_ORGANIZATION_NAME,omitempty"`
	PortalRefererURL                                 *string `json:"PORTAL_REFERER_URL,omitempty"`
	PortalRefreshURL                                 *string `json:"PORTAL_REFRESH_URL,omitempty"`
	PortalEnableDestinationFilter                    *string `json:"PORTAL_ENABLE_DESTINATION_FILTER,omitempty"`
	PortalEnableWebhookCustomHeaders                 *string `json:"PORTAL_ENABLE_WEBHOOK_CUSTOM_HEADERS,omitempty"`
	RetryIntervalSeconds                             *string `json:"RETRY_INTERVAL_SECONDS,omitempty"`
	MaxRetryLimit                                    *string `json:"MAX_RETRY_LIMIT,omitempty"`
	RetrySchedule                                    *string `json:"RETRY_SCHEDULE,omitempty"`
	OtelExporterOtlpEndpoint                         *string `json:"OTEL_EXPORTER_OTLP_ENDPOINT,omitempty"`
	OtelExporterOtlpHeaders                          *string `json:"OTEL_EXPORTER_OTLP_HEADERS,omitempty"`
	OtelExporterOtlpProtocol                         *string `json:"OTEL_EXPORTER_OTLP_PROTOCOL,omitempty"`
	OtelExporterOtlpTracesEndpoint                   *string `json:"OTEL_EXPORTER_OTLP_TRACES_ENDPOINT,omitempty"`
	OtelExporterOtlpMetricsEndpoint                  *string `json:"OTEL_EXPORTER_OTLP_METRICS_ENDPOINT,omitempty"`
	OtelExporterOtlpLogsEndpoint                     *string `json:"OTEL_EXPORTER_OTLP_LOGS_ENDPOINT,omitempty"`
	OtelServiceName                                  *string `json:"OTEL_SERVICE_NAME,omitempty"`
	PublishAwsSqsAccessKeyID                         *string `json:"PUBLISH_AWS_SQS_ACCESS_KEY_ID,omitempty"`
	PublishAwsSqsEndpoint                            *string `json:"PUBLISH_AWS_SQS_ENDPOINT,omitempty"`
	PublishAwsSqsQueue                               *string `json:"PUBLISH_AWS_SQS_QUEUE,omitempty"`
	PublishAwsSqsRegion                              *string `json:"PUBLISH_AWS_SQS_REGION,omitempty"`
	PublishAwsSqsSecretAccessKey                     *string `json:"PUBLISH_AWS_SQS_SECRET_ACCESS_KEY,omitempty"`
	PublishAzureServicebusConnectionString           *string `json:"PUBLISH_AZURE_SERVICEBUS_CONNECTION_STRING,omitempty"`
	PublishAzureServicebusSubscription               *string `json:"PUBLISH_AZURE_SERVICEBUS_SUBSCRIPTION,omitempty"`
	PublishAzureServicebusTopic                      *string `json:"PUBLISH_AZURE_SERVICEBUS_TOPIC,omitempty"`
	PublishGcpPubsubProject                          *string `json:"PUBLISH_GCP_PUBSUB_PROJECT,omitempty"`
	PublishGcpPubsubServiceAccountCredentials        *string `json:"PUBLISH_GCP_PUBSUB_SERVICE_ACCOUNT_CREDENTIALS,omitempty"`
	PublishGcpPubsubSubscription                     *string `json:"PUBLISH_GCP_PUBSUB_SUBSCRIPTION,omitempty"`
	PublishGcpPubsubTopic                            *string `json:"PUBLISH_GCP_PUBSUB_TOPIC,omitempty"`
	PublishRabbitmqExchange                          *string `json:"PUBLISH_RABBITMQ_EXCHANGE,omitempty"`
	PublishRabbitmqQueue                             *string `json:"PUBLISH_RABBITMQ_QUEUE,omitempty"`
	PublishRabbitmqServerURL                         *string `json:"PUBLISH_RABBITMQ_SERVER_URL,omitempty"`
	Topics                                           *string `json:"TOPICS,omitempty"`
}

func (m *ManagedConfig) GetAlertAutoDisableDestination() *string {
	if m == nil {
		return nil
	}
	return m.AlertAutoDisableDestination
}

func (m *ManagedConfig) GetAlertCallbackURL() *string {
	if m == nil {
		return nil
	}
	return m.AlertCallbackURL
}

func (m *ManagedConfig) GetAlertConsecutiveFailureCount() *string {
	if m == nil {
		return nil
	}
	return m.AlertConsecutiveFailureCount
}

func (m *ManagedConfig) GetDeliveryTimeoutSeconds() *string {
	if m == nil {
		return nil
	}
	return m.DeliveryTimeoutSeconds
}

func (m *ManagedConfig) GetDestinationsAwsKinesisMetadataInPayload() *string {
	if m == nil {
		return nil
	}
	return m.DestinationsAwsKinesisMetadataInPayload
}

func (m *ManagedConfig) GetDestinationsIncludeMillisecondTimestamp() *string {
	if m == nil {
		return nil
	}
	return m.DestinationsIncludeMillisecondTimestamp
}

func (m *ManagedConfig) GetDestinationsWebhookDisableDefaultEventIDHeader() *string {
	if m == nil {
		return nil
	}
	return m.DestinationsWebhookDisableDefaultEventIDHeader
}

func (m *ManagedConfig) GetDestinationsWebhookDisableDefaultSignatureHeader() *string {
	if m == nil {
		return nil
	}
	return m.DestinationsWebhookDisableDefaultSignatureHeader
}

func (m *ManagedConfig) GetDestinationsWebhookDisableDefaultTimestampHeader() *string {
	if m == nil {
		return nil
	}
	return m.DestinationsWebhookDisableDefaultTimestampHeader
}

func (m *ManagedConfig) GetDestinationsWebhookDisableDefaultTopicHeader() *string {
	if m == nil {
		return nil
	}
	return m.DestinationsWebhookDisableDefaultTopicHeader
}

func (m *ManagedConfig) GetDestinationsWebhookHeaderPrefix() *string {
	if m == nil {
		return nil
	}
	return m.DestinationsWebhookHeaderPrefix
}

func (m *ManagedConfig) GetDestinationsWebhookMode() *string {
	if m == nil {
		return nil
	}
	return m.DestinationsWebhookMode
}

func (m *ManagedConfig) GetDestinationsWebhookProxyURL() *string {
	if m == nil {
		return nil
	}
	return m.DestinationsWebhookProxyURL
}

func (m *ManagedConfig) GetDestinationsWebhookSignatureAlgorithm() *string {
	if m == nil {
		return nil
	}
	return m.DestinationsWebhookSignatureAlgorithm
}

func (m *ManagedConfig) GetDestinationsWebhookSignatureContentTemplate() *string {
	if m == nil {
		return nil
	}
	return m.DestinationsWebhookSignatureContentTemplate
}

func (m *ManagedConfig) GetDestinationsWebhookSignatureEncoding() *string {
	if m == nil {
		return nil
	}
	return m.DestinationsWebhookSignatureEncoding
}

func (m *ManagedConfig) GetDestinationsWebhookSignatureHeaderTemplate() *string {
	if m == nil {
		return nil
	}
	return m.DestinationsWebhookSignatureHeaderTemplate
}

func (m *ManagedConfig) GetDestinationsWebhookSigningSecretTemplate() *string {
	if m == nil {
		return nil
	}
	return m.DestinationsWebhookSigningSecretTemplate
}

func (m *ManagedConfig) GetHTTPUserAgent() *string {
	if m == nil {
		return nil
	}
	return m.HTTPUserAgent
}

func (m *ManagedConfig) GetIdgenAttemptPrefix() *string {
	if m == nil {
		return nil
	}
	return m.IdgenAttemptPrefix
}

func (m *ManagedConfig) GetIdgenDestinationPrefix() *string {
	if m == nil {
		return nil
	}
	return m.IdgenDestinationPrefix
}

func (m *ManagedConfig) GetIdgenEventPrefix() *string {
	if m == nil {
		return nil
	}
	return m.IdgenEventPrefix
}

func (m *ManagedConfig) GetIdgenType() *string {
	if m == nil {
		return nil
	}
	return m.IdgenType
}

func (m *ManagedConfig) GetMaxDestinationsPerTenant() *string {
	if m == nil {
		return nil
	}
	return m.MaxDestinationsPerTenant
}

func (m *ManagedConfig) GetOrganizationName() *string {
	if m == nil {
		return nil
	}
	return m.OrganizationName
}

func (m *ManagedConfig) GetPortalBrandColor() *string {
	if m == nil {
		return nil
	}
	return m.PortalBrandColor
}

func (m *ManagedConfig) GetPortalDisableOutpostBranding() *string {
	if m == nil {
		return nil
	}
	return m.PortalDisableOutpostBranding
}

func (m *ManagedConfig) GetPortalFaviconURL() *string {
	if m == nil {
		return nil
	}
	return m.PortalFaviconURL
}

func (m *ManagedConfig) GetPortalForceTheme() *string {
	if m == nil {
		return nil
	}
	return m.PortalForceTheme
}

func (m *ManagedConfig) GetPortalLogo() *string {
	if m == nil {
		return nil
	}
	return m.PortalLogo
}

func (m *ManagedConfig) GetPortalLogoDark() *string {
	if m == nil {
		return nil
	}
	return m.PortalLogoDark
}

func (m *ManagedConfig) GetPortalOrganizationName() *string {
	if m == nil {
		return nil
	}
	return m.PortalOrganizationName
}

func (m *ManagedConfig) GetPortalRefererURL() *string {
	if m == nil {
		return nil
	}
	return m.PortalRefererURL
}

func (m *ManagedConfig) GetPortalRefreshURL() *string {
	if m == nil {
		return nil
	}
	return m.PortalRefreshURL
}

func (m *ManagedConfig) GetPortalEnableDestinationFilter() *string {
	if m == nil {
		return nil
	}
	return m.PortalEnableDestinationFilter
}

func (m *ManagedConfig) GetPortalEnableWebhookCustomHeaders() *string {
	if m == nil {
		return nil
	}
	return m.PortalEnableWebhookCustomHeaders
}

func (m *ManagedConfig) GetRetryIntervalSeconds() *string {
	if m == nil {
		return nil
	}
	return m.RetryIntervalSeconds
}

func (m *ManagedConfig) GetMaxRetryLimit() *string {
	if m == nil {
		return nil
	}
	return m.MaxRetryLimit
}

func (m *ManagedConfig) GetRetrySchedule() *string {
	if m == nil {
		return nil
	}
	return m.RetrySchedule
}

func (m *ManagedConfig) GetOtelExporterOtlpEndpoint() *string {
	if m == nil {
		return nil
	}
	return m.OtelExporterOtlpEndpoint
}

func (m *ManagedConfig) GetOtelExporterOtlpHeaders() *string {
	if m == nil {
		return nil
	}
	return m.OtelExporterOtlpHeaders
}

func (m *ManagedConfig) GetOtelExporterOtlpProtocol() *string {
	if m == nil {
		return nil
	}
	return m.OtelExporterOtlpProtocol
}

func (m *ManagedConfig) GetOtelExporterOtlpTracesEndpoint() *string {
	if m == nil {
		return nil
	}
	return m.OtelExporterOtlpTracesEndpoint
}

func (m *ManagedConfig) GetOtelExporterOtlpMetricsEndpoint() *string {
	if m == nil {
		return nil
	}
	return m.OtelExporterOtlpMetricsEndpoint
}

func (m *ManagedConfig) GetOtelExporterOtlpLogsEndpoint() *string {
	if m == nil {
		return nil
	}
	return m.OtelExporterOtlpLogsEndpoint
}

func (m *ManagedConfig) GetOtelServiceName() *string {
	if m == nil {
		return nil
	}
	return m.OtelServiceName
}

func (m *ManagedConfig) GetPublishAwsSqsAccessKeyID() *string {
	if m == nil {
		return nil
	}
	return m.PublishAwsSqsAccessKeyID
}

func (m *ManagedConfig) GetPublishAwsSqsEndpoint() *string {
	if m == nil {
		return nil
	}
	return m.PublishAwsSqsEndpoint
}

func (m *ManagedConfig) GetPublishAwsSqsQueue() *string {
	if m == nil {
		return nil
	}
	return m.PublishAwsSqsQueue
}

func (m *ManagedConfig) GetPublishAwsSqsRegion() *string {
	if m == nil {
		return nil
	}
	return m.PublishAwsSqsRegion
}

func (m *ManagedConfig) GetPublishAwsSqsSecretAccessKey() *string {
	if m == nil {
		return nil
	}
	return m.PublishAwsSqsSecretAccessKey
}

func (m *ManagedConfig) GetPublishAzureServicebusConnectionString() *string {
	if m == nil {
		return nil
	}
	return m.PublishAzureServicebusConnectionString
}

func (m *ManagedConfig) GetPublishAzureServicebusSubscription() *string {
	if m == nil {
		return nil
	}
	return m.PublishAzureServicebusSubscription
}

func (m *ManagedConfig) GetPublishAzureServicebusTopic() *string {
	if m == nil {
		return nil
	}
	return m.PublishAzureServicebusTopic
}

func (m *ManagedConfig) GetPublishGcpPubsubProject() *string {
	if m == nil {
		return nil
	}
	return m.PublishGcpPubsubProject
}

func (m *ManagedConfig) GetPublishGcpPubsubServiceAccountCredentials() *string {
	if m == nil {
		return nil
	}
	return m.PublishGcpPubsubServiceAccountCredentials
}

func (m *ManagedConfig) GetPublishGcpPubsubSubscription() *string {
	if m == nil {
		return nil
	}
	return m.PublishGcpPubsubSubscription
}

func (m *ManagedConfig) GetPublishGcpPubsubTopic() *string {
	if m == nil {
		return nil
	}
	return m.PublishGcpPubsubTopic
}

func (m *ManagedConfig) GetPublishRabbitmqExchange() *string {
	if m == nil {
		return nil
	}
	return m.PublishRabbitmqExchange
}

func (m *ManagedConfig) GetPublishRabbitmqQueue() *string {
	if m == nil {
		return nil
	}
	return m.PublishRabbitmqQueue
}

func (m *ManagedConfig) GetPublishRabbitmqServerURL() *string {
	if m == nil {
		return nil
	}
	return m.PublishRabbitmqServerURL
}

func (m *ManagedConfig) GetTopics() *string {
	if m == nil {
		return nil
	}
	return m.Topics
}
