// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PublishResponse struct {
	// The ID of the event that was accepted for publishing. This will be the ID provided in the request's `id` field if present, otherwise it's a server-generated UUID.
	ID string `json:"id"`
	// Whether this event was already processed (idempotency hit). If true, the event was not queued again.
	Duplicate bool `json:"duplicate"`
	// The IDs of destinations that matched this event. Empty array if no destinations matched.
	DestinationIds []string `json:"destination_ids"`
}

func (p *PublishResponse) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PublishResponse) GetDuplicate() bool {
	if p == nil {
		return false
	}
	return p.Duplicate
}

func (p *PublishResponse) GetDestinationIds() []string {
	if p == nil {
		return []string{}
	}
	return p.DestinationIds
}
