// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	AdminAPIKey *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TenantJwt   *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (s *Security) GetAdminAPIKey() *string {
	if s == nil {
		return nil
	}
	return s.AdminAPIKey
}

func (s *Security) GetTenantJwt() *string {
	if s == nil {
		return nil
	}
	return s.TenantJwt
}
