// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/utils"
)

type WebhookConfig struct {
	// The URL to send the webhook events to.
	URL string `json:"url"`
	// JSON string of custom HTTP headers to include with every webhook request. Header names must be valid HTTP header tokens (alphanumeric, hyphens, underscores). Reserved headers (Content-Type, Host, etc.) cannot be overridden.
	CustomHeaders *string `json:"custom_headers,omitempty"`
}

func (w WebhookConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhookConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, []string{"url"}); err != nil {
		return err
	}
	return nil
}

func (w *WebhookConfig) GetURL() string {
	if w == nil {
		return ""
	}
	return w.URL
}

func (w *WebhookConfig) GetCustomHeaders() *string {
	if w == nil {
		return nil
	}
	return w.CustomHeaders
}
