// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/utils"
)

// WebhookConfigUpdate - Partial Webhook config for PATCH updates (RFC 7396 merge-patch).
type WebhookConfigUpdate struct {
	// The URL to send the webhook events to.
	URL *string `json:"url,omitempty"`
	// JSON string of custom HTTP headers to include with every webhook request.
	CustomHeaders *string `json:"custom_headers,omitempty"`
}

func (w WebhookConfigUpdate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhookConfigUpdate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WebhookConfigUpdate) GetURL() *string {
	if w == nil {
		return nil
	}
	return w.URL
}

func (w *WebhookConfigUpdate) GetCustomHeaders() *string {
	if w == nil {
		return nil
	}
	return w.CustomHeaders
}
