"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .eventpaginatedresult import EventPaginatedResult, EventPaginatedResultTypedDict
from datetime import datetime
from enum import Enum
from outpost_sdk.types import BaseModel, UNSET_SENTINEL
from outpost_sdk.utils import FieldMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Callable, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


AdminListEventsTopicTypedDict = TypeAliasType(
    "AdminListEventsTopicTypedDict", Union[str, List[str]]
)
r"""Filter events by topic(s). Can be specified multiple times or comma-separated."""


AdminListEventsTopic = TypeAliasType("AdminListEventsTopic", Union[str, List[str]])
r"""Filter events by topic(s). Can be specified multiple times or comma-separated."""


class AdminListEventsOrderBy(str, Enum):
    r"""Field to sort by."""

    TIME = "time"


class AdminListEventsDir(str, Enum):
    r"""Sort direction."""

    ASC = "asc"
    DESC = "desc"


class AdminListEventsRequestTypedDict(TypedDict):
    tenant_id: NotRequired[str]
    r"""Filter events by tenant ID. If not provided, returns events from all tenants."""
    topic: NotRequired[AdminListEventsTopicTypedDict]
    r"""Filter events by topic(s). Can be specified multiple times or comma-separated."""
    time_gte: NotRequired[datetime]
    r"""Filter events with time >= value (RFC3339 or YYYY-MM-DD format)."""
    time_lte: NotRequired[datetime]
    r"""Filter events with time <= value (RFC3339 or YYYY-MM-DD format)."""
    limit: NotRequired[int]
    r"""Number of items per page (default 100, max 1000)."""
    next_cursor: NotRequired[str]
    r"""Cursor for next page of results."""
    prev_cursor: NotRequired[str]
    r"""Cursor for previous page of results."""
    order_by: NotRequired[AdminListEventsOrderBy]
    r"""Field to sort by."""
    direction: NotRequired[AdminListEventsDir]
    r"""Sort direction."""


class AdminListEventsRequest(BaseModel):
    tenant_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter events by tenant ID. If not provided, returns events from all tenants."""

    topic: Annotated[
        Optional[AdminListEventsTopic],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter events by topic(s). Can be specified multiple times or comma-separated."""

    time_gte: Annotated[
        Optional[datetime],
        pydantic.Field(alias="time[gte]"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter events with time >= value (RFC3339 or YYYY-MM-DD format)."""

    time_lte: Annotated[
        Optional[datetime],
        pydantic.Field(alias="time[lte]"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter events with time <= value (RFC3339 or YYYY-MM-DD format)."""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 100
    r"""Number of items per page (default 100, max 1000)."""

    next_cursor: Annotated[
        Optional[str],
        pydantic.Field(alias="next"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Cursor for next page of results."""

    prev_cursor: Annotated[
        Optional[str],
        pydantic.Field(alias="prev"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Cursor for previous page of results."""

    order_by: Annotated[
        Optional[AdminListEventsOrderBy],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = AdminListEventsOrderBy.TIME
    r"""Field to sort by."""

    direction: Annotated[
        Optional[AdminListEventsDir],
        pydantic.Field(alias="dir"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = AdminListEventsDir.DESC
    r"""Sort direction."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "tenant_id",
                "topic",
                "time[gte]",
                "time[lte]",
                "limit",
                "next_cursor",
                "prev_cursor",
                "order_by",
                "direction",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class AdminListEventsResponseTypedDict(TypedDict):
    result: EventPaginatedResultTypedDict


class AdminListEventsResponse(BaseModel):
    next: Callable[[], Optional[AdminListEventsResponse]]

    result: EventPaginatedResult
