"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .destinationupdateawskinesis import (
    DestinationUpdateAWSKinesis,
    DestinationUpdateAWSKinesisTypedDict,
)
from .destinationupdateawss3 import (
    DestinationUpdateAwss3,
    DestinationUpdateAwss3TypedDict,
)
from .destinationupdateawssqs import (
    DestinationUpdateAWSSQS,
    DestinationUpdateAWSSQSTypedDict,
)
from .destinationupdateazureservicebus import (
    DestinationUpdateAzureServiceBus,
    DestinationUpdateAzureServiceBusTypedDict,
)
from .destinationupdategcppubsub import (
    DestinationUpdateGCPPubSub,
    DestinationUpdateGCPPubSubTypedDict,
)
from .destinationupdatehookdeck import (
    DestinationUpdateHookdeck,
    DestinationUpdateHookdeckTypedDict,
)
from .destinationupdatekafka import (
    DestinationUpdateKafka,
    DestinationUpdateKafkaTypedDict,
)
from .destinationupdaterabbitmq import (
    DestinationUpdateRabbitMQ,
    DestinationUpdateRabbitMQTypedDict,
)
from .destinationupdatewebhook import (
    DestinationUpdateWebhook,
    DestinationUpdateWebhookTypedDict,
)
from typing import Union
from typing_extensions import TypeAliasType


DestinationUpdateTypedDict = TypeAliasType(
    "DestinationUpdateTypedDict",
    Union[
        DestinationUpdateWebhookTypedDict,
        DestinationUpdateHookdeckTypedDict,
        DestinationUpdateAWSSQSTypedDict,
        DestinationUpdateAWSKinesisTypedDict,
        DestinationUpdateAwss3TypedDict,
        DestinationUpdateAzureServiceBusTypedDict,
        DestinationUpdateGCPPubSubTypedDict,
        DestinationUpdateRabbitMQTypedDict,
        DestinationUpdateKafkaTypedDict,
    ],
)


DestinationUpdate = TypeAliasType(
    "DestinationUpdate",
    Union[
        DestinationUpdateWebhook,
        DestinationUpdateHookdeck,
        DestinationUpdateAWSSQS,
        DestinationUpdateAWSKinesis,
        DestinationUpdateAwss3,
        DestinationUpdateAzureServiceBus,
        DestinationUpdateGCPPubSub,
        DestinationUpdateRabbitMQ,
        DestinationUpdateKafka,
    ],
)
