"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from outpost_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class GCPPubSubConfigUpdateTypedDict(TypedDict):
    r"""Partial GCP Pub/Sub config for PATCH updates (RFC 7396 merge-patch)."""

    project_id: NotRequired[str]
    r"""The GCP project ID."""
    topic: NotRequired[str]
    r"""The Pub/Sub topic name."""
    endpoint: NotRequired[str]
    r"""Optional. Custom endpoint URL (e.g., localhost:8085 for emulator)."""


class GCPPubSubConfigUpdate(BaseModel):
    r"""Partial GCP Pub/Sub config for PATCH updates (RFC 7396 merge-patch)."""

    project_id: Optional[str] = None
    r"""The GCP project ID."""

    topic: Optional[str] = None
    r"""The Pub/Sub topic name."""

    endpoint: Optional[str] = None
    r"""Optional. Custom endpoint URL (e.g., localhost:8085 for emulator)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["project_id", "topic", "endpoint"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
