"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from outpost_sdk.types import BaseModel
from outpost_sdk.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetTenantTokenRequestTypedDict(TypedDict):
    tenant_id: str
    r"""The ID of the tenant. Required when using AdminApiKey authentication."""


class GetTenantTokenRequest(BaseModel):
    tenant_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the tenant. Required when using AdminApiKey authentication."""
