"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from outpost_sdk.types import BaseModel, UNSET_SENTINEL
from outpost_sdk.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class GetTenantDestinationAttemptGlobalsTypedDict(TypedDict):
    tenant_id: NotRequired[str]


class GetTenantDestinationAttemptGlobals(BaseModel):
    tenant_id: Annotated[
        Optional[str],
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["tenant_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


GetTenantDestinationAttemptIncludeTypedDict = TypeAliasType(
    "GetTenantDestinationAttemptIncludeTypedDict", Union[str, List[str]]
)
r"""Fields to include in the response. Can be specified multiple times or comma-separated.
- `event`: Include event summary
- `event.data`: Include full event with payload data
- `response_data`: Include response body and headers

"""


GetTenantDestinationAttemptInclude = TypeAliasType(
    "GetTenantDestinationAttemptInclude", Union[str, List[str]]
)
r"""Fields to include in the response. Can be specified multiple times or comma-separated.
- `event`: Include event summary
- `event.data`: Include full event with payload data
- `response_data`: Include response body and headers

"""


class GetTenantDestinationAttemptRequestTypedDict(TypedDict):
    destination_id: str
    r"""The ID of the destination."""
    attempt_id: str
    r"""The ID of the attempt."""
    tenant_id: NotRequired[str]
    r"""The ID of the tenant. Required when using AdminApiKey authentication."""
    include: NotRequired[GetTenantDestinationAttemptIncludeTypedDict]
    r"""Fields to include in the response. Can be specified multiple times or comma-separated.
    - `event`: Include event summary
    - `event.data`: Include full event with payload data
    - `response_data`: Include response body and headers

    """


class GetTenantDestinationAttemptRequest(BaseModel):
    destination_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the destination."""

    attempt_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the attempt."""

    tenant_id: Annotated[
        Optional[str],
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None
    r"""The ID of the tenant. Required when using AdminApiKey authentication."""

    include: Annotated[
        Optional[GetTenantDestinationAttemptInclude],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Fields to include in the response. Can be specified multiple times or comma-separated.
    - `event`: Include event summary
    - `event.data`: Include full event with payload data
    - `response_data`: Include response body and headers

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["tenant_id", "include"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
