"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from outpost_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class KafkaCredentialsUpdateTypedDict(TypedDict):
    r"""Partial Kafka credentials for PATCH updates (RFC 7396 merge-patch)."""

    username: NotRequired[str]
    r"""SASL username for authentication."""
    password: NotRequired[str]
    r"""SASL password for authentication."""


class KafkaCredentialsUpdate(BaseModel):
    r"""Partial Kafka credentials for PATCH updates (RFC 7396 merge-patch)."""

    username: Optional[str] = None
    r"""SASL username for authentication."""

    password: Optional[str] = None
    r"""SASL password for authentication."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["username", "password"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
