"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from outpost_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class KafkaConfigUpdateSaslMechanism(str, Enum):
    r"""SASL authentication mechanism."""

    PLAIN = "plain"
    SCRAM_SHA_256 = "scram-sha-256"
    SCRAM_SHA_512 = "scram-sha-512"


class KafkaConfigUpdateTLS(str, Enum):
    r"""Whether to enable TLS for the connection."""

    TRUE = "true"
    FALSE = "false"


class KafkaConfigUpdateTypedDict(TypedDict):
    r"""Partial Kafka config for PATCH updates (RFC 7396 merge-patch)."""

    brokers: NotRequired[str]
    r"""Comma-separated list of Kafka broker addresses."""
    topic: NotRequired[str]
    r"""The Kafka topic to publish messages to."""
    sasl_mechanism: NotRequired[KafkaConfigUpdateSaslMechanism]
    r"""SASL authentication mechanism."""
    tls: NotRequired[KafkaConfigUpdateTLS]
    r"""Whether to enable TLS for the connection."""
    partition_key_template: NotRequired[str]
    r"""Optional JMESPath template to extract the partition key from the event payload."""


class KafkaConfigUpdate(BaseModel):
    r"""Partial Kafka config for PATCH updates (RFC 7396 merge-patch)."""

    brokers: Optional[str] = None
    r"""Comma-separated list of Kafka broker addresses."""

    topic: Optional[str] = None
    r"""The Kafka topic to publish messages to."""

    sasl_mechanism: Optional[KafkaConfigUpdateSaslMechanism] = None
    r"""SASL authentication mechanism."""

    tls: Optional[KafkaConfigUpdateTLS] = None
    r"""Whether to enable TLS for the connection."""

    partition_key_template: Optional[str] = None
    r"""Optional JMESPath template to extract the partition key from the event payload."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["brokers", "topic", "sasl_mechanism", "tls", "partition_key_template"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
