"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .tenantpaginatedresult import TenantPaginatedResult, TenantPaginatedResultTypedDict
from datetime import datetime
from enum import Enum
from outpost_sdk.types import BaseModel, UNSET_SENTINEL
from outpost_sdk.utils import FieldMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Callable, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ListTenantsOrderBy(str, Enum):
    r"""Field to sort by."""

    CREATED_AT = "created_at"


class ListTenantsDir(str, Enum):
    r"""Sort direction."""

    ASC = "asc"
    DESC = "desc"


class ListTenantsRequestTypedDict(TypedDict):
    limit: NotRequired[int]
    r"""Number of tenants to return per page (1-100, default 20)."""
    order_by: NotRequired[ListTenantsOrderBy]
    r"""Field to sort by."""
    direction: NotRequired[ListTenantsDir]
    r"""Sort direction."""
    created_at_gte: NotRequired[datetime]
    r"""Filter tenants created at or after this time (RFC3339 or YYYY-MM-DD format)."""
    created_at_lte: NotRequired[datetime]
    r"""Filter tenants created at or before this time (RFC3339 or YYYY-MM-DD format)."""
    next_cursor: NotRequired[str]
    r"""Cursor for the next page of results. Mutually exclusive with `prev`."""
    prev_cursor: NotRequired[str]
    r"""Cursor for the previous page of results. Mutually exclusive with `next`."""


class ListTenantsRequest(BaseModel):
    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 20
    r"""Number of tenants to return per page (1-100, default 20)."""

    order_by: Annotated[
        Optional[ListTenantsOrderBy],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = ListTenantsOrderBy.CREATED_AT
    r"""Field to sort by."""

    direction: Annotated[
        Optional[ListTenantsDir],
        pydantic.Field(alias="dir"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = ListTenantsDir.DESC
    r"""Sort direction."""

    created_at_gte: Annotated[
        Optional[datetime],
        pydantic.Field(alias="created_at[gte]"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter tenants created at or after this time (RFC3339 or YYYY-MM-DD format)."""

    created_at_lte: Annotated[
        Optional[datetime],
        pydantic.Field(alias="created_at[lte]"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter tenants created at or before this time (RFC3339 or YYYY-MM-DD format)."""

    next_cursor: Annotated[
        Optional[str],
        pydantic.Field(alias="next"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Cursor for the next page of results. Mutually exclusive with `prev`."""

    prev_cursor: Annotated[
        Optional[str],
        pydantic.Field(alias="prev"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Cursor for the previous page of results. Mutually exclusive with `next`."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "limit",
                "order_by",
                "direction",
                "created_at[gte]",
                "created_at[lte]",
                "next_cursor",
                "prev_cursor",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListTenantsResponseTypedDict(TypedDict):
    result: TenantPaginatedResultTypedDict


class ListTenantsResponse(BaseModel):
    next: Callable[[], Optional[ListTenantsResponse]]

    result: TenantPaginatedResult
