"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .attemptpaginatedresult import (
    AttemptPaginatedResult,
    AttemptPaginatedResultTypedDict,
)
from datetime import datetime
from enum import Enum
from outpost_sdk.types import BaseModel, UNSET_SENTINEL
from outpost_sdk.utils import FieldMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Callable, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class ListAttemptsStatus(str, Enum):
    r"""Filter attempts by status."""

    SUCCESS = "success"
    FAILED = "failed"


ListAttemptsTopicTypedDict = TypeAliasType(
    "ListAttemptsTopicTypedDict", Union[str, List[str]]
)
r"""Filter attempts by event topic(s). Can be specified multiple times or comma-separated."""


ListAttemptsTopic = TypeAliasType("ListAttemptsTopic", Union[str, List[str]])
r"""Filter attempts by event topic(s). Can be specified multiple times or comma-separated."""


ListAttemptsIncludeTypedDict = TypeAliasType(
    "ListAttemptsIncludeTypedDict", Union[str, List[str]]
)
r"""Fields to include in the response. Can be specified multiple times or comma-separated.
- `event`: Include event summary (id, topic, time, eligible_for_retry, metadata)
- `event.data`: Include full event with payload data
- `response_data`: Include response body and headers

"""


ListAttemptsInclude = TypeAliasType("ListAttemptsInclude", Union[str, List[str]])
r"""Fields to include in the response. Can be specified multiple times or comma-separated.
- `event`: Include event summary (id, topic, time, eligible_for_retry, metadata)
- `event.data`: Include full event with payload data
- `response_data`: Include response body and headers

"""


class ListAttemptsOrderBy(str, Enum):
    r"""Field to sort by."""

    TIME = "time"


class ListAttemptsDir(str, Enum):
    r"""Sort direction."""

    ASC = "asc"
    DESC = "desc"


class ListAttemptsRequestTypedDict(TypedDict):
    tenant_id: NotRequired[str]
    r"""Filter attempts by tenant ID. If not provided, returns attempts from all tenants."""
    event_id: NotRequired[str]
    r"""Filter attempts by event ID."""
    destination_id: NotRequired[str]
    r"""Filter attempts by destination ID."""
    status: NotRequired[ListAttemptsStatus]
    r"""Filter attempts by status."""
    topic: NotRequired[ListAttemptsTopicTypedDict]
    r"""Filter attempts by event topic(s). Can be specified multiple times or comma-separated."""
    time_gte: NotRequired[datetime]
    r"""Filter attempts by event time >= value (RFC3339 or YYYY-MM-DD format)."""
    time_lte: NotRequired[datetime]
    r"""Filter attempts by event time <= value (RFC3339 or YYYY-MM-DD format)."""
    limit: NotRequired[int]
    r"""Number of items per page (default 100, max 1000)."""
    next_cursor: NotRequired[str]
    r"""Cursor for next page of results."""
    prev_cursor: NotRequired[str]
    r"""Cursor for previous page of results."""
    include: NotRequired[ListAttemptsIncludeTypedDict]
    r"""Fields to include in the response. Can be specified multiple times or comma-separated.
    - `event`: Include event summary (id, topic, time, eligible_for_retry, metadata)
    - `event.data`: Include full event with payload data
    - `response_data`: Include response body and headers

    """
    order_by: NotRequired[ListAttemptsOrderBy]
    r"""Field to sort by."""
    direction: NotRequired[ListAttemptsDir]
    r"""Sort direction."""


class ListAttemptsRequest(BaseModel):
    tenant_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter attempts by tenant ID. If not provided, returns attempts from all tenants."""

    event_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter attempts by event ID."""

    destination_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter attempts by destination ID."""

    status: Annotated[
        Optional[ListAttemptsStatus],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter attempts by status."""

    topic: Annotated[
        Optional[ListAttemptsTopic],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter attempts by event topic(s). Can be specified multiple times or comma-separated."""

    time_gte: Annotated[
        Optional[datetime],
        pydantic.Field(alias="time[gte]"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter attempts by event time >= value (RFC3339 or YYYY-MM-DD format)."""

    time_lte: Annotated[
        Optional[datetime],
        pydantic.Field(alias="time[lte]"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter attempts by event time <= value (RFC3339 or YYYY-MM-DD format)."""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 100
    r"""Number of items per page (default 100, max 1000)."""

    next_cursor: Annotated[
        Optional[str],
        pydantic.Field(alias="next"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Cursor for next page of results."""

    prev_cursor: Annotated[
        Optional[str],
        pydantic.Field(alias="prev"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Cursor for previous page of results."""

    include: Annotated[
        Optional[ListAttemptsInclude],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Fields to include in the response. Can be specified multiple times or comma-separated.
    - `event`: Include event summary (id, topic, time, eligible_for_retry, metadata)
    - `event.data`: Include full event with payload data
    - `response_data`: Include response body and headers

    """

    order_by: Annotated[
        Optional[ListAttemptsOrderBy],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = ListAttemptsOrderBy.TIME
    r"""Field to sort by."""

    direction: Annotated[
        Optional[ListAttemptsDir],
        pydantic.Field(alias="dir"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = ListAttemptsDir.DESC
    r"""Sort direction."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "tenant_id",
                "event_id",
                "destination_id",
                "status",
                "topic",
                "time[gte]",
                "time[lte]",
                "limit",
                "next_cursor",
                "prev_cursor",
                "include",
                "order_by",
                "direction",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListAttemptsResponseTypedDict(TypedDict):
    result: AttemptPaginatedResultTypedDict


class ListAttemptsResponse(BaseModel):
    next: Callable[[], Optional[ListAttemptsResponse]]

    result: AttemptPaginatedResult
