"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from outpost_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class MetricsDataPointTypedDict(TypedDict):
    time_bucket: NotRequired[datetime]
    r"""Start of the time bucket. Absent when no granularity is specified."""
    dimensions: NotRequired[Dict[str, str]]
    r"""Dimension values for this data point. Empty object when no dimensions are requested."""
    metrics: NotRequired[Dict[str, Any]]
    r"""Requested measure values for this data point."""


class MetricsDataPoint(BaseModel):
    time_bucket: Optional[datetime] = None
    r"""Start of the time bucket. Absent when no granularity is specified."""

    dimensions: Optional[Dict[str, str]] = None
    r"""Dimension values for this data point. Empty object when no dimensions are requested."""

    metrics: Optional[Dict[str, Any]] = None
    r"""Requested measure values for this data point."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["time_bucket", "dimensions", "metrics"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
