"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from typing import List, Union
from typing_extensions import TypeAliasType


class TopicsEnum(str, Enum):
    WILDCARD_ = "*"


TopicsUnionTypedDict = TypeAliasType(
    "TopicsUnionTypedDict", Union[TopicsEnum, List[str]]
)
r"""\"*\" or an array of enabled topics. Topic strings can include \"*\" as a wildcard matching any run of characters. When available topics are configured, wildcard patterns must match at least one available topic."""


TopicsUnion = TypeAliasType("TopicsUnion", Union[TopicsEnum, List[str]])
r"""\"*\" or an array of enabled topics. Topic strings can include \"*\" as a wildcard matching any run of characters. When available topics are configured, wildcard patterns must match at least one available topic."""
