"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .operatoreventdestinationupdate import (
    OperatorEventDestinationUpdate,
    OperatorEventDestinationUpdateTypedDict,
)
from outpost_sdk.types import BaseModel
from outpost_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateOperatorEventDestinationRequestTypedDict(TypedDict):
    destination_id: str
    r"""The ID of the operator event destination."""
    body: OperatorEventDestinationUpdateTypedDict


class UpdateOperatorEventDestinationRequest(BaseModel):
    destination_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the operator event destination."""

    body: Annotated[
        OperatorEventDestinationUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
