services:
  api:
    image: hookdeck/outpost:v0.4.0
    container_name: outpost-api-azure
    env_file: .env.runtime
    environment:
      SERVICE: api
    ports:
      - "3333:3333"

  delivery:
    image: hookdeck/outpost:v0.4.0
    container_name: outpost-delivery-azure
    env_file: .env.runtime
    environment:
      SERVICE: delivery

  log:
    image: hookdeck/outpost:v0.4.0
    container_name: outpost-log-azure
    env_file: .env.runtime
    environment:
      SERVICE: log
