apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "outpost.name" . }}-api
  labels:
    app: outpost
    {{- include "outpost.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.outpost.replicas.api }}
  selector:
    matchLabels:
      app: outpost-api
  template:
    metadata:
      labels:
        app: outpost-api
        {{- include "outpost.labels" . | nindent 8 }}
        {{- with .Values.outpost.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.outpost.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.outpost.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "outpost.name" . }}-api
          image: {{ .Values.outpost.image.repository }}:{{ .Values.outpost.image.tag }}
          imagePullPolicy: {{ .Values.outpost.image.pullPolicy }}
          {{- with .Values.outpost.resources.api }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
          - name: http
            containerPort: 3333
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/v1/healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
          - name: config
            mountPath: /config/outpost
          env:
            - name: SERVICE
              value: api
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{- include "outpost.env" . | nindent 12 }}
          {{- with .Values.outpost.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.outpost.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.outpost.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.outpost.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: "{{ include "outpost.fullname" . }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "outpost.name" . }}-delivery
  labels:
    app: outpost
    {{- include "outpost.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.outpost.replicas.delivery }}
  selector:
    matchLabels:
      app: outpost-delivery
  template:
    metadata:
      labels:
        app: outpost-delivery
        {{- include "outpost.labels" . | nindent 8 }}
        {{- with .Values.outpost.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.outpost.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.outpost.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "outpost.name" . }}-delivery
          image: {{ .Values.outpost.image.repository }}:{{ .Values.outpost.image.tag }}
          imagePullPolicy: {{ .Values.outpost.image.pullPolicy }}
          {{- with .Values.outpost.resources.delivery }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
          - name: http
            containerPort: 3333
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/v1/healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
          - name: config
            mountPath: /config/outpost
          env:
            - name: SERVICE
              value: delivery
            {{- include "outpost.env" . | nindent 12 }}
          {{- with .Values.outpost.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.outpost.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.outpost.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.outpost.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: "{{ include "outpost.fullname" . }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "outpost.name" . }}-log
  labels:
    app: outpost
    {{- include "outpost.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.outpost.replicas.log }}
  selector:
    matchLabels:
      app: outpost-log
  template:
    metadata:
      labels:
        app: outpost-log
        {{- include "outpost.labels" . | nindent 8 }}
        {{- with .Values.outpost.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.outpost.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.outpost.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "outpost.name" . }}-log
          image: {{ .Values.outpost.image.repository }}:{{ .Values.outpost.image.tag }}
          imagePullPolicy: {{ .Values.outpost.image.pullPolicy }}
          {{- with .Values.outpost.resources.log }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
          - name: http
            containerPort: 3333
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/v1/healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
          - name: config
            mountPath: /config/outpost
          env:
            - name: SERVICE
              value: log
            {{- include "outpost.env" . | nindent 12 }}
          {{- with .Values.outpost.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.outpost.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.outpost.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.outpost.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: "{{ include "outpost.fullname" . }}"