apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: outpost
spec:
  type: {{ .Values.outpost.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.outpost.service.port }}
  selector:
    app: outpost-api
