apiVersion: v1
kind: Service
metadata:
  name: {{ include "outpost.fullname" . }}
  labels:
    app: outpost
    {{- include "outpost.labels" . | nindent 4 }}
  {{- if .Values.outpost.service.annotations }}
  annotations:
    {{- toYaml .Values.outpost.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.outpost.service.type }}
  ports:
    - port: {{ .Values.outpost.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: outpost-api
  {{- if and (eq .Values.outpost.service.type "LoadBalancer") (not (empty .Values.outpost.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{- toYaml .Values.outpost.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}