/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { configurationUpdateManagedConfig } from "../../funcs/configurationUpdateManagedConfig.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.ManagedConfig$inboundSchema,
};

export const tool$configurationUpdateManagedConfig: ToolDefinition<
  typeof args
> = {
  name: "configuration-update-managed-config",
  description: `Update Managed Configuration

Updates one or more managed Outpost configuration values. Null values clear the configuration and reverts to Outpost default behavior.

This endpoint is only available for the managed version.
In self-hosted deployments, configuration is controlled through environment variables instead.

Only the supported configuration keys are accepted.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await configurationUpdateManagedConfig(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
