/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { operatorEventsListEvents } from "../../funcs/operatorEventsListEvents.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$operatorEventsListEvents: ToolDefinition = {
  name: "operator-events-list-events",
  description: `List Operator Events

Returns the 100 most recent operator events emitted by this deployment, newest first.
Paging is not available yet: this operation takes no query parameters, so
\`pagination.next\` cannot be passed back.

Each row is an Outpost event whose \`topic\` is the operator event topic, whose
\`matched_destination_ids\` are operator event destinations, and whose \`tenant_id\` is the
ID of your Outpost project. The topic-specific payload is nested under \`data\`, which
carries the same envelope the sink receives: \`id\`, \`topic\`, \`time\`, \`tenant_id\` and a
\`data\` object described on the
[Operator Events](https://hookdeck.com/docs/outpost/features/operator-events) feature page.

This endpoint is only available on managed Outpost.
`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await operatorEventsListEvents(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
