/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { operatorEventsListAttempts } from "../../funcs/operatorEventsListAttempts.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListOperatorEventAttemptsRequest$inboundSchema,
};

export const tool$operatorEventsListAttempts: ToolDefinition<typeof args> = {
  name: "operator-events-list-attempts",
  description: `List Operator Event Attempts

Returns the delivery attempts made to operator event destinations, newest first.

The response holds one page of up to \`limit\` attempts. Paging is not available yet:
\`pagination.next\` cannot be passed back.

This endpoint is only available on managed Outpost.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await operatorEventsListAttempts(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
