/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { operatorEventsListDestinationTypes } from "../../funcs/operatorEventsListDestinationTypes.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$operatorEventsListDestinationTypes: ToolDefinition = {
  name: "operator-events-list-destination-types",
  description: `List Operator Event Destination Type Schemas

Returns the destination types an operator event destination may use, with the \`config\`
and \`credentials\` fields each type takes.

This endpoint is only available on managed Outpost.
`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await operatorEventsListDestinationTypes(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
