/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { operatorEventsUpdateDestination } from "../../funcs/operatorEventsUpdateDestination.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  destinationId: z.string(),
  body: components.OperatorEventDestinationUpdate$inboundSchema,
};

export const tool$operatorEventsUpdateDestination: ToolDefinition<typeof args> =
  {
    name: "operator-events-update-destination",
    description: `Update Operator Event Destination

Updates an operator event destination. \`topics\` uses full-replacement semantics: the list
sent becomes the subscription.

\`config\` and \`credentials\` take the fields of the destination's type; fields that are not
sent keep their value. The type itself cannot be changed.

To change the signing secret of a \`webhook\` destination, set \`credentials.secret\`, or send
\`credentials.rotate_secret: true\` to have Outpost generate a new one. On rotation the
current secret stays valid as \`previous_secret\`, for 24 hours by default.

Returns 404 \`destination not found\` if no operator event destination has this ID, or
404 \`tenant not found\` if the project has never had one.

This endpoint is only available on managed Outpost.
`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await operatorEventsUpdateDestination(
        client,
        args.destinationId,
        args.body,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
