workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Outpost API:
        inputs:
            - location: ./docs/apis/openapi.yaml
        overlays:
            - location: ./sdks/schemas/speakeasy-modifications-overlay.yaml
            - location: ./sdks/schemas/error-types.yaml
        registry:
            location: registry.speakeasyapi.dev/hookdeck-dev/outpost/outpost-api
    Outpost API (Python):
        inputs:
            - location: ./docs/apis/openapi.yaml
        overlays:
            - location: ./sdks/schemas/speakeasy-modifications-overlay.yaml
            - location: ./sdks/schemas/error-types.yaml
            - location: ./sdks/schemas/pagination-fixes-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/hookdeck-dev/outpost/outpost-api
targets:
    outpost-go:
        target: go
        source: Outpost API
        output: ./sdks/outpost-go
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/hookdeck-dev/outpost/outpost-api-go-code-samples
            labelOverride:
                fixedValue: Go (SDK)
            blocking: false
    outpost-python:
        target: python
        source: Outpost API (Python)
        output: ./sdks/outpost-python
        # Speakeasy sets readme = "README-PYPI.md" but does not generate it. We check in
        # README-PYPI.md and list it in .genignore so the file survives generation and build succeeds.
        # prepare_readme.py overwrites it at publish time with link-rewritten content for PyPI.
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/hookdeck-dev/outpost/outpost-api-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
    outpost-ts:
        target: typescript
        source: Outpost API
        output: ./sdks/outpost-typescript
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/hookdeck-dev/outpost/outpost-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
