// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/utils"
	"github.com/hookdeck/outpost/sdks/outpost-go/models/components"
	"time"
)

// AdminListAttemptsStatus - Filter attempts by status.
type AdminListAttemptsStatus string

const (
	AdminListAttemptsStatusSuccess AdminListAttemptsStatus = "success"
	AdminListAttemptsStatusFailed  AdminListAttemptsStatus = "failed"
)

func (e AdminListAttemptsStatus) ToPointer() *AdminListAttemptsStatus {
	return &e
}
func (e *AdminListAttemptsStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "success":
		fallthrough
	case "failed":
		*e = AdminListAttemptsStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AdminListAttemptsStatus: %v", v)
	}
}

type AdminListAttemptsTopicType string

const (
	AdminListAttemptsTopicTypeStr        AdminListAttemptsTopicType = "str"
	AdminListAttemptsTopicTypeArrayOfStr AdminListAttemptsTopicType = "arrayOfStr"
)

// AdminListAttemptsTopic - Filter attempts by event topic(s). Can be specified multiple times or comma-separated.
type AdminListAttemptsTopic struct {
	Str        *string  `queryParam:"inline" union:"member"`
	ArrayOfStr []string `queryParam:"inline" union:"member"`

	Type AdminListAttemptsTopicType
}

func CreateAdminListAttemptsTopicStr(str string) AdminListAttemptsTopic {
	typ := AdminListAttemptsTopicTypeStr

	return AdminListAttemptsTopic{
		Str:  &str,
		Type: typ,
	}
}

func CreateAdminListAttemptsTopicArrayOfStr(arrayOfStr []string) AdminListAttemptsTopic {
	typ := AdminListAttemptsTopicTypeArrayOfStr

	return AdminListAttemptsTopic{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *AdminListAttemptsTopic) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = AdminListAttemptsTopicTypeStr
		return nil
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = AdminListAttemptsTopicTypeArrayOfStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for AdminListAttemptsTopic", string(data))
}

func (u AdminListAttemptsTopic) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type AdminListAttemptsTopic: all fields are null")
}

type AdminListAttemptsIncludeType string

const (
	AdminListAttemptsIncludeTypeStr        AdminListAttemptsIncludeType = "str"
	AdminListAttemptsIncludeTypeArrayOfStr AdminListAttemptsIncludeType = "arrayOfStr"
)

// AdminListAttemptsInclude - Fields to include in the response. Can be specified multiple times or comma-separated.
// - `event`: Include event summary (id, topic, time, eligible_for_retry, metadata)
// - `event.data`: Include full event with payload data
// - `response_data`: Include response body and headers
type AdminListAttemptsInclude struct {
	Str        *string  `queryParam:"inline" union:"member"`
	ArrayOfStr []string `queryParam:"inline" union:"member"`

	Type AdminListAttemptsIncludeType
}

func CreateAdminListAttemptsIncludeStr(str string) AdminListAttemptsInclude {
	typ := AdminListAttemptsIncludeTypeStr

	return AdminListAttemptsInclude{
		Str:  &str,
		Type: typ,
	}
}

func CreateAdminListAttemptsIncludeArrayOfStr(arrayOfStr []string) AdminListAttemptsInclude {
	typ := AdminListAttemptsIncludeTypeArrayOfStr

	return AdminListAttemptsInclude{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *AdminListAttemptsInclude) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = AdminListAttemptsIncludeTypeStr
		return nil
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = AdminListAttemptsIncludeTypeArrayOfStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for AdminListAttemptsInclude", string(data))
}

func (u AdminListAttemptsInclude) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type AdminListAttemptsInclude: all fields are null")
}

// AdminListAttemptsOrderBy - Field to sort by.
type AdminListAttemptsOrderBy string

const (
	AdminListAttemptsOrderByTime AdminListAttemptsOrderBy = "time"
)

func (e AdminListAttemptsOrderBy) ToPointer() *AdminListAttemptsOrderBy {
	return &e
}
func (e *AdminListAttemptsOrderBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "time":
		*e = AdminListAttemptsOrderBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AdminListAttemptsOrderBy: %v", v)
	}
}

// AdminListAttemptsDir - Sort direction.
type AdminListAttemptsDir string

const (
	AdminListAttemptsDirAsc  AdminListAttemptsDir = "asc"
	AdminListAttemptsDirDesc AdminListAttemptsDir = "desc"
)

func (e AdminListAttemptsDir) ToPointer() *AdminListAttemptsDir {
	return &e
}
func (e *AdminListAttemptsDir) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = AdminListAttemptsDir(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AdminListAttemptsDir: %v", v)
	}
}

type AdminListAttemptsRequest struct {
	// Filter attempts by tenant ID. If not provided, returns attempts from all tenants.
	TenantID *string `queryParam:"style=form,explode=true,name=tenant_id"`
	// Filter attempts by event ID.
	EventID *string `queryParam:"style=form,explode=true,name=event_id"`
	// Filter attempts by destination ID.
	DestinationID *string `queryParam:"style=form,explode=true,name=destination_id"`
	// Filter attempts by status.
	Status *AdminListAttemptsStatus `queryParam:"style=form,explode=true,name=status"`
	// Filter attempts by event topic(s). Can be specified multiple times or comma-separated.
	Topic *AdminListAttemptsTopic `queryParam:"style=form,explode=true,name=topic"`
	// Filter attempts by event time >= value (RFC3339 or YYYY-MM-DD format).
	TimeGte *time.Time `queryParam:"style=form,explode=true,name=time[gte]"`
	// Filter attempts by event time <= value (RFC3339 or YYYY-MM-DD format).
	TimeLte *time.Time `queryParam:"style=form,explode=true,name=time[lte]"`
	// Number of items per page (default 100, max 1000).
	Limit *int64 `default:"100" queryParam:"style=form,explode=true,name=limit"`
	// Cursor for next page of results.
	Next *string `queryParam:"style=form,explode=true,name=next"`
	// Cursor for previous page of results.
	Prev *string `queryParam:"style=form,explode=true,name=prev"`
	// Fields to include in the response. Can be specified multiple times or comma-separated.
	// - `event`: Include event summary (id, topic, time, eligible_for_retry, metadata)
	// - `event.data`: Include full event with payload data
	// - `response_data`: Include response body and headers
	//
	Include *AdminListAttemptsInclude `queryParam:"style=form,explode=true,name=include"`
	// Field to sort by.
	OrderBy *AdminListAttemptsOrderBy `default:"time" queryParam:"style=form,explode=true,name=order_by"`
	// Sort direction.
	Dir *AdminListAttemptsDir `default:"desc" queryParam:"style=form,explode=true,name=dir"`
}

func (a AdminListAttemptsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AdminListAttemptsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AdminListAttemptsRequest) GetTenantID() *string {
	if a == nil {
		return nil
	}
	return a.TenantID
}

func (a *AdminListAttemptsRequest) GetEventID() *string {
	if a == nil {
		return nil
	}
	return a.EventID
}

func (a *AdminListAttemptsRequest) GetDestinationID() *string {
	if a == nil {
		return nil
	}
	return a.DestinationID
}

func (a *AdminListAttemptsRequest) GetStatus() *AdminListAttemptsStatus {
	if a == nil {
		return nil
	}
	return a.Status
}

func (a *AdminListAttemptsRequest) GetTopic() *AdminListAttemptsTopic {
	if a == nil {
		return nil
	}
	return a.Topic
}

func (a *AdminListAttemptsRequest) GetTimeGte() *time.Time {
	if a == nil {
		return nil
	}
	return a.TimeGte
}

func (a *AdminListAttemptsRequest) GetTimeLte() *time.Time {
	if a == nil {
		return nil
	}
	return a.TimeLte
}

func (a *AdminListAttemptsRequest) GetLimit() *int64 {
	if a == nil {
		return nil
	}
	return a.Limit
}

func (a *AdminListAttemptsRequest) GetNext() *string {
	if a == nil {
		return nil
	}
	return a.Next
}

func (a *AdminListAttemptsRequest) GetPrev() *string {
	if a == nil {
		return nil
	}
	return a.Prev
}

func (a *AdminListAttemptsRequest) GetInclude() *AdminListAttemptsInclude {
	if a == nil {
		return nil
	}
	return a.Include
}

func (a *AdminListAttemptsRequest) GetOrderBy() *AdminListAttemptsOrderBy {
	if a == nil {
		return nil
	}
	return a.OrderBy
}

func (a *AdminListAttemptsRequest) GetDir() *AdminListAttemptsDir {
	if a == nil {
		return nil
	}
	return a.Dir
}

type AdminListAttemptsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A paginated list of attempts.
	AttemptPaginatedResult *components.AttemptPaginatedResult
}

func (a *AdminListAttemptsResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AdminListAttemptsResponse) GetAttemptPaginatedResult() *components.AttemptPaginatedResult {
	if a == nil {
		return nil
	}
	return a.AttemptPaginatedResult
}
