// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/utils"
	"github.com/hookdeck/outpost/sdks/outpost-go/models/components"
	"time"
)

// GetAttemptMetricsTime - Time range for the metrics query.
type GetAttemptMetricsTime struct {
	// Start of the time range (inclusive). ISO 8601 timestamp.
	Start time.Time `queryParam:"name=start"`
	// End of the time range (exclusive). ISO 8601 timestamp.
	End time.Time `queryParam:"name=end"`
}

func (g GetAttemptMetricsTime) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAttemptMetricsTime) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAttemptMetricsTime) GetStart() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.Start
}

func (g *GetAttemptMetricsTime) GetEnd() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.End
}

type GetAttemptMetricsMeasuresEnum2 string

const (
	GetAttemptMetricsMeasuresEnum2Count             GetAttemptMetricsMeasuresEnum2 = "count"
	GetAttemptMetricsMeasuresEnum2SuccessfulCount   GetAttemptMetricsMeasuresEnum2 = "successful_count"
	GetAttemptMetricsMeasuresEnum2FailedCount       GetAttemptMetricsMeasuresEnum2 = "failed_count"
	GetAttemptMetricsMeasuresEnum2ErrorRate         GetAttemptMetricsMeasuresEnum2 = "error_rate"
	GetAttemptMetricsMeasuresEnum2FirstAttemptCount GetAttemptMetricsMeasuresEnum2 = "first_attempt_count"
	GetAttemptMetricsMeasuresEnum2RetryCount        GetAttemptMetricsMeasuresEnum2 = "retry_count"
	GetAttemptMetricsMeasuresEnum2ManualRetryCount  GetAttemptMetricsMeasuresEnum2 = "manual_retry_count"
	GetAttemptMetricsMeasuresEnum2AvgAttemptNumber  GetAttemptMetricsMeasuresEnum2 = "avg_attempt_number"
	GetAttemptMetricsMeasuresEnum2Rate              GetAttemptMetricsMeasuresEnum2 = "rate"
	GetAttemptMetricsMeasuresEnum2SuccessfulRate    GetAttemptMetricsMeasuresEnum2 = "successful_rate"
	GetAttemptMetricsMeasuresEnum2FailedRate        GetAttemptMetricsMeasuresEnum2 = "failed_rate"
)

func (e GetAttemptMetricsMeasuresEnum2) ToPointer() *GetAttemptMetricsMeasuresEnum2 {
	return &e
}
func (e *GetAttemptMetricsMeasuresEnum2) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "count":
		fallthrough
	case "successful_count":
		fallthrough
	case "failed_count":
		fallthrough
	case "error_rate":
		fallthrough
	case "first_attempt_count":
		fallthrough
	case "retry_count":
		fallthrough
	case "manual_retry_count":
		fallthrough
	case "avg_attempt_number":
		fallthrough
	case "rate":
		fallthrough
	case "successful_rate":
		fallthrough
	case "failed_rate":
		*e = GetAttemptMetricsMeasuresEnum2(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetAttemptMetricsMeasuresEnum2: %v", v)
	}
}

type GetAttemptMetricsMeasuresEnum1 string

const (
	GetAttemptMetricsMeasuresEnum1Count             GetAttemptMetricsMeasuresEnum1 = "count"
	GetAttemptMetricsMeasuresEnum1SuccessfulCount   GetAttemptMetricsMeasuresEnum1 = "successful_count"
	GetAttemptMetricsMeasuresEnum1FailedCount       GetAttemptMetricsMeasuresEnum1 = "failed_count"
	GetAttemptMetricsMeasuresEnum1ErrorRate         GetAttemptMetricsMeasuresEnum1 = "error_rate"
	GetAttemptMetricsMeasuresEnum1FirstAttemptCount GetAttemptMetricsMeasuresEnum1 = "first_attempt_count"
	GetAttemptMetricsMeasuresEnum1RetryCount        GetAttemptMetricsMeasuresEnum1 = "retry_count"
	GetAttemptMetricsMeasuresEnum1ManualRetryCount  GetAttemptMetricsMeasuresEnum1 = "manual_retry_count"
	GetAttemptMetricsMeasuresEnum1AvgAttemptNumber  GetAttemptMetricsMeasuresEnum1 = "avg_attempt_number"
	GetAttemptMetricsMeasuresEnum1Rate              GetAttemptMetricsMeasuresEnum1 = "rate"
	GetAttemptMetricsMeasuresEnum1SuccessfulRate    GetAttemptMetricsMeasuresEnum1 = "successful_rate"
	GetAttemptMetricsMeasuresEnum1FailedRate        GetAttemptMetricsMeasuresEnum1 = "failed_rate"
)

func (e GetAttemptMetricsMeasuresEnum1) ToPointer() *GetAttemptMetricsMeasuresEnum1 {
	return &e
}
func (e *GetAttemptMetricsMeasuresEnum1) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "count":
		fallthrough
	case "successful_count":
		fallthrough
	case "failed_count":
		fallthrough
	case "error_rate":
		fallthrough
	case "first_attempt_count":
		fallthrough
	case "retry_count":
		fallthrough
	case "manual_retry_count":
		fallthrough
	case "avg_attempt_number":
		fallthrough
	case "rate":
		fallthrough
	case "successful_rate":
		fallthrough
	case "failed_rate":
		*e = GetAttemptMetricsMeasuresEnum1(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetAttemptMetricsMeasuresEnum1: %v", v)
	}
}

type GetAttemptMetricsMeasuresUnionType string

const (
	GetAttemptMetricsMeasuresUnionTypeGetAttemptMetricsMeasuresEnum1        GetAttemptMetricsMeasuresUnionType = "getAttemptMetrics_measures_enum_1"
	GetAttemptMetricsMeasuresUnionTypeArrayOfGetAttemptMetricsMeasuresEnum2 GetAttemptMetricsMeasuresUnionType = "arrayOfGetAttemptMetricsMeasuresEnum2"
)

// GetAttemptMetricsMeasuresUnion - Measures to compute. At least one required. Rate measures (`rate`, `successful_rate`, `failed_rate`) are throughput in events/second. Use bracket notation for multiple values (e.g., `measures[0]=count&measures[1]=error_rate`).
type GetAttemptMetricsMeasuresUnion struct {
	GetAttemptMetricsMeasuresEnum1        *GetAttemptMetricsMeasuresEnum1  `queryParam:"inline" union:"member"`
	ArrayOfGetAttemptMetricsMeasuresEnum2 []GetAttemptMetricsMeasuresEnum2 `queryParam:"inline" union:"member"`

	Type GetAttemptMetricsMeasuresUnionType
}

func CreateGetAttemptMetricsMeasuresUnionGetAttemptMetricsMeasuresEnum1(getAttemptMetricsMeasuresEnum1 GetAttemptMetricsMeasuresEnum1) GetAttemptMetricsMeasuresUnion {
	typ := GetAttemptMetricsMeasuresUnionTypeGetAttemptMetricsMeasuresEnum1

	return GetAttemptMetricsMeasuresUnion{
		GetAttemptMetricsMeasuresEnum1: &getAttemptMetricsMeasuresEnum1,
		Type:                           typ,
	}
}

func CreateGetAttemptMetricsMeasuresUnionArrayOfGetAttemptMetricsMeasuresEnum2(arrayOfGetAttemptMetricsMeasuresEnum2 []GetAttemptMetricsMeasuresEnum2) GetAttemptMetricsMeasuresUnion {
	typ := GetAttemptMetricsMeasuresUnionTypeArrayOfGetAttemptMetricsMeasuresEnum2

	return GetAttemptMetricsMeasuresUnion{
		ArrayOfGetAttemptMetricsMeasuresEnum2: arrayOfGetAttemptMetricsMeasuresEnum2,
		Type:                                  typ,
	}
}

func (u *GetAttemptMetricsMeasuresUnion) UnmarshalJSON(data []byte) error {

	var getAttemptMetricsMeasuresEnum1 GetAttemptMetricsMeasuresEnum1 = GetAttemptMetricsMeasuresEnum1("")
	if err := utils.UnmarshalJSON(data, &getAttemptMetricsMeasuresEnum1, "", true, nil); err == nil {
		u.GetAttemptMetricsMeasuresEnum1 = &getAttemptMetricsMeasuresEnum1
		u.Type = GetAttemptMetricsMeasuresUnionTypeGetAttemptMetricsMeasuresEnum1
		return nil
	}

	var arrayOfGetAttemptMetricsMeasuresEnum2 []GetAttemptMetricsMeasuresEnum2 = []GetAttemptMetricsMeasuresEnum2{}
	if err := utils.UnmarshalJSON(data, &arrayOfGetAttemptMetricsMeasuresEnum2, "", true, nil); err == nil {
		u.ArrayOfGetAttemptMetricsMeasuresEnum2 = arrayOfGetAttemptMetricsMeasuresEnum2
		u.Type = GetAttemptMetricsMeasuresUnionTypeArrayOfGetAttemptMetricsMeasuresEnum2
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetAttemptMetricsMeasuresUnion", string(data))
}

func (u GetAttemptMetricsMeasuresUnion) MarshalJSON() ([]byte, error) {
	if u.GetAttemptMetricsMeasuresEnum1 != nil {
		return utils.MarshalJSON(u.GetAttemptMetricsMeasuresEnum1, "", true)
	}

	if u.ArrayOfGetAttemptMetricsMeasuresEnum2 != nil {
		return utils.MarshalJSON(u.ArrayOfGetAttemptMetricsMeasuresEnum2, "", true)
	}

	return nil, errors.New("could not marshal union type GetAttemptMetricsMeasuresUnion: all fields are null")
}

type GetAttemptMetricsDimensionsEnum2 string

const (
	GetAttemptMetricsDimensionsEnum2TenantID        GetAttemptMetricsDimensionsEnum2 = "tenant_id"
	GetAttemptMetricsDimensionsEnum2DestinationID   GetAttemptMetricsDimensionsEnum2 = "destination_id"
	GetAttemptMetricsDimensionsEnum2DestinationType GetAttemptMetricsDimensionsEnum2 = "destination_type"
	GetAttemptMetricsDimensionsEnum2Topic           GetAttemptMetricsDimensionsEnum2 = "topic"
	GetAttemptMetricsDimensionsEnum2Status          GetAttemptMetricsDimensionsEnum2 = "status"
	GetAttemptMetricsDimensionsEnum2Code            GetAttemptMetricsDimensionsEnum2 = "code"
	GetAttemptMetricsDimensionsEnum2Manual          GetAttemptMetricsDimensionsEnum2 = "manual"
	GetAttemptMetricsDimensionsEnum2AttemptNumber   GetAttemptMetricsDimensionsEnum2 = "attempt_number"
)

func (e GetAttemptMetricsDimensionsEnum2) ToPointer() *GetAttemptMetricsDimensionsEnum2 {
	return &e
}
func (e *GetAttemptMetricsDimensionsEnum2) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "tenant_id":
		fallthrough
	case "destination_id":
		fallthrough
	case "destination_type":
		fallthrough
	case "topic":
		fallthrough
	case "status":
		fallthrough
	case "code":
		fallthrough
	case "manual":
		fallthrough
	case "attempt_number":
		*e = GetAttemptMetricsDimensionsEnum2(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetAttemptMetricsDimensionsEnum2: %v", v)
	}
}

type GetAttemptMetricsDimensionsEnum1 string

const (
	GetAttemptMetricsDimensionsEnum1TenantID        GetAttemptMetricsDimensionsEnum1 = "tenant_id"
	GetAttemptMetricsDimensionsEnum1DestinationID   GetAttemptMetricsDimensionsEnum1 = "destination_id"
	GetAttemptMetricsDimensionsEnum1DestinationType GetAttemptMetricsDimensionsEnum1 = "destination_type"
	GetAttemptMetricsDimensionsEnum1Topic           GetAttemptMetricsDimensionsEnum1 = "topic"
	GetAttemptMetricsDimensionsEnum1Status          GetAttemptMetricsDimensionsEnum1 = "status"
	GetAttemptMetricsDimensionsEnum1Code            GetAttemptMetricsDimensionsEnum1 = "code"
	GetAttemptMetricsDimensionsEnum1Manual          GetAttemptMetricsDimensionsEnum1 = "manual"
	GetAttemptMetricsDimensionsEnum1AttemptNumber   GetAttemptMetricsDimensionsEnum1 = "attempt_number"
)

func (e GetAttemptMetricsDimensionsEnum1) ToPointer() *GetAttemptMetricsDimensionsEnum1 {
	return &e
}
func (e *GetAttemptMetricsDimensionsEnum1) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "tenant_id":
		fallthrough
	case "destination_id":
		fallthrough
	case "destination_type":
		fallthrough
	case "topic":
		fallthrough
	case "status":
		fallthrough
	case "code":
		fallthrough
	case "manual":
		fallthrough
	case "attempt_number":
		*e = GetAttemptMetricsDimensionsEnum1(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetAttemptMetricsDimensionsEnum1: %v", v)
	}
}

type GetAttemptMetricsDimensionsUnionType string

const (
	GetAttemptMetricsDimensionsUnionTypeGetAttemptMetricsDimensionsEnum1        GetAttemptMetricsDimensionsUnionType = "getAttemptMetrics_dimensions_enum_1"
	GetAttemptMetricsDimensionsUnionTypeArrayOfGetAttemptMetricsDimensionsEnum2 GetAttemptMetricsDimensionsUnionType = "arrayOfGetAttemptMetricsDimensionsEnum2"
)

// GetAttemptMetricsDimensionsUnion - Dimensions to group results by. Use bracket notation for multiple values (e.g., `dimensions[0]=status&dimensions[1]=destination_id`).
type GetAttemptMetricsDimensionsUnion struct {
	GetAttemptMetricsDimensionsEnum1        *GetAttemptMetricsDimensionsEnum1  `queryParam:"inline" union:"member"`
	ArrayOfGetAttemptMetricsDimensionsEnum2 []GetAttemptMetricsDimensionsEnum2 `queryParam:"inline" union:"member"`

	Type GetAttemptMetricsDimensionsUnionType
}

func CreateGetAttemptMetricsDimensionsUnionGetAttemptMetricsDimensionsEnum1(getAttemptMetricsDimensionsEnum1 GetAttemptMetricsDimensionsEnum1) GetAttemptMetricsDimensionsUnion {
	typ := GetAttemptMetricsDimensionsUnionTypeGetAttemptMetricsDimensionsEnum1

	return GetAttemptMetricsDimensionsUnion{
		GetAttemptMetricsDimensionsEnum1: &getAttemptMetricsDimensionsEnum1,
		Type:                             typ,
	}
}

func CreateGetAttemptMetricsDimensionsUnionArrayOfGetAttemptMetricsDimensionsEnum2(arrayOfGetAttemptMetricsDimensionsEnum2 []GetAttemptMetricsDimensionsEnum2) GetAttemptMetricsDimensionsUnion {
	typ := GetAttemptMetricsDimensionsUnionTypeArrayOfGetAttemptMetricsDimensionsEnum2

	return GetAttemptMetricsDimensionsUnion{
		ArrayOfGetAttemptMetricsDimensionsEnum2: arrayOfGetAttemptMetricsDimensionsEnum2,
		Type:                                    typ,
	}
}

func (u *GetAttemptMetricsDimensionsUnion) UnmarshalJSON(data []byte) error {

	var getAttemptMetricsDimensionsEnum1 GetAttemptMetricsDimensionsEnum1 = GetAttemptMetricsDimensionsEnum1("")
	if err := utils.UnmarshalJSON(data, &getAttemptMetricsDimensionsEnum1, "", true, nil); err == nil {
		u.GetAttemptMetricsDimensionsEnum1 = &getAttemptMetricsDimensionsEnum1
		u.Type = GetAttemptMetricsDimensionsUnionTypeGetAttemptMetricsDimensionsEnum1
		return nil
	}

	var arrayOfGetAttemptMetricsDimensionsEnum2 []GetAttemptMetricsDimensionsEnum2 = []GetAttemptMetricsDimensionsEnum2{}
	if err := utils.UnmarshalJSON(data, &arrayOfGetAttemptMetricsDimensionsEnum2, "", true, nil); err == nil {
		u.ArrayOfGetAttemptMetricsDimensionsEnum2 = arrayOfGetAttemptMetricsDimensionsEnum2
		u.Type = GetAttemptMetricsDimensionsUnionTypeArrayOfGetAttemptMetricsDimensionsEnum2
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetAttemptMetricsDimensionsUnion", string(data))
}

func (u GetAttemptMetricsDimensionsUnion) MarshalJSON() ([]byte, error) {
	if u.GetAttemptMetricsDimensionsEnum1 != nil {
		return utils.MarshalJSON(u.GetAttemptMetricsDimensionsEnum1, "", true)
	}

	if u.ArrayOfGetAttemptMetricsDimensionsEnum2 != nil {
		return utils.MarshalJSON(u.ArrayOfGetAttemptMetricsDimensionsEnum2, "", true)
	}

	return nil, errors.New("could not marshal union type GetAttemptMetricsDimensionsUnion: all fields are null")
}

type GetAttemptMetricsFiltersDestinationIDType string

const (
	GetAttemptMetricsFiltersDestinationIDTypeStr        GetAttemptMetricsFiltersDestinationIDType = "str"
	GetAttemptMetricsFiltersDestinationIDTypeArrayOfStr GetAttemptMetricsFiltersDestinationIDType = "arrayOfStr"
)

// GetAttemptMetricsFiltersDestinationID - Filter by destination ID(s). Use bracket notation for multiple values (e.g., `filters[destination_id][0]=d1&filters[destination_id][1]=d2`).
type GetAttemptMetricsFiltersDestinationID struct {
	Str        *string  `queryParam:"inline" union:"member"`
	ArrayOfStr []string `queryParam:"inline" union:"member"`

	Type GetAttemptMetricsFiltersDestinationIDType
}

func CreateGetAttemptMetricsFiltersDestinationIDStr(str string) GetAttemptMetricsFiltersDestinationID {
	typ := GetAttemptMetricsFiltersDestinationIDTypeStr

	return GetAttemptMetricsFiltersDestinationID{
		Str:  &str,
		Type: typ,
	}
}

func CreateGetAttemptMetricsFiltersDestinationIDArrayOfStr(arrayOfStr []string) GetAttemptMetricsFiltersDestinationID {
	typ := GetAttemptMetricsFiltersDestinationIDTypeArrayOfStr

	return GetAttemptMetricsFiltersDestinationID{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *GetAttemptMetricsFiltersDestinationID) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = GetAttemptMetricsFiltersDestinationIDTypeStr
		return nil
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = GetAttemptMetricsFiltersDestinationIDTypeArrayOfStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetAttemptMetricsFiltersDestinationID", string(data))
}

func (u GetAttemptMetricsFiltersDestinationID) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type GetAttemptMetricsFiltersDestinationID: all fields are null")
}

type FiltersDestinationTypeType string

const (
	FiltersDestinationTypeTypeDestinationType        FiltersDestinationTypeType = "DestinationType"
	FiltersDestinationTypeTypeArrayOfDestinationType FiltersDestinationTypeType = "arrayOfDestinationType"
)

// FiltersDestinationType - Filter by destination type(s). Use bracket notation for multiple values (e.g., `filters[destination_type][0]=webhook&filters[destination_type][1]=aws_sqs`).
type FiltersDestinationType struct {
	DestinationType        *components.DestinationType  `queryParam:"inline" union:"member"`
	ArrayOfDestinationType []components.DestinationType `queryParam:"inline" union:"member"`

	Type FiltersDestinationTypeType
}

func CreateFiltersDestinationTypeDestinationType(destinationType components.DestinationType) FiltersDestinationType {
	typ := FiltersDestinationTypeTypeDestinationType

	return FiltersDestinationType{
		DestinationType: &destinationType,
		Type:            typ,
	}
}

func CreateFiltersDestinationTypeArrayOfDestinationType(arrayOfDestinationType []components.DestinationType) FiltersDestinationType {
	typ := FiltersDestinationTypeTypeArrayOfDestinationType

	return FiltersDestinationType{
		ArrayOfDestinationType: arrayOfDestinationType,
		Type:                   typ,
	}
}

func (u *FiltersDestinationType) UnmarshalJSON(data []byte) error {

	var destinationType components.DestinationType = components.DestinationType("")
	if err := utils.UnmarshalJSON(data, &destinationType, "", true, nil); err == nil {
		u.DestinationType = &destinationType
		u.Type = FiltersDestinationTypeTypeDestinationType
		return nil
	}

	var arrayOfDestinationType []components.DestinationType = []components.DestinationType{}
	if err := utils.UnmarshalJSON(data, &arrayOfDestinationType, "", true, nil); err == nil {
		u.ArrayOfDestinationType = arrayOfDestinationType
		u.Type = FiltersDestinationTypeTypeArrayOfDestinationType
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for FiltersDestinationType", string(data))
}

func (u FiltersDestinationType) MarshalJSON() ([]byte, error) {
	if u.DestinationType != nil {
		return utils.MarshalJSON(u.DestinationType, "", true)
	}

	if u.ArrayOfDestinationType != nil {
		return utils.MarshalJSON(u.ArrayOfDestinationType, "", true)
	}

	return nil, errors.New("could not marshal union type FiltersDestinationType: all fields are null")
}

type GetAttemptMetricsFiltersTopicType string

const (
	GetAttemptMetricsFiltersTopicTypeStr        GetAttemptMetricsFiltersTopicType = "str"
	GetAttemptMetricsFiltersTopicTypeArrayOfStr GetAttemptMetricsFiltersTopicType = "arrayOfStr"
)

// GetAttemptMetricsFiltersTopic - Filter by topic name(s). Use bracket notation for multiple values (e.g., `filters[topic][0]=user.created&filters[topic][1]=user.updated`).
type GetAttemptMetricsFiltersTopic struct {
	Str        *string  `queryParam:"inline" union:"member"`
	ArrayOfStr []string `queryParam:"inline" union:"member"`

	Type GetAttemptMetricsFiltersTopicType
}

func CreateGetAttemptMetricsFiltersTopicStr(str string) GetAttemptMetricsFiltersTopic {
	typ := GetAttemptMetricsFiltersTopicTypeStr

	return GetAttemptMetricsFiltersTopic{
		Str:  &str,
		Type: typ,
	}
}

func CreateGetAttemptMetricsFiltersTopicArrayOfStr(arrayOfStr []string) GetAttemptMetricsFiltersTopic {
	typ := GetAttemptMetricsFiltersTopicTypeArrayOfStr

	return GetAttemptMetricsFiltersTopic{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *GetAttemptMetricsFiltersTopic) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = GetAttemptMetricsFiltersTopicTypeStr
		return nil
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = GetAttemptMetricsFiltersTopicTypeArrayOfStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetAttemptMetricsFiltersTopic", string(data))
}

func (u GetAttemptMetricsFiltersTopic) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type GetAttemptMetricsFiltersTopic: all fields are null")
}

type FiltersStatusEnum2 string

const (
	FiltersStatusEnum2Success FiltersStatusEnum2 = "success"
	FiltersStatusEnum2Failed  FiltersStatusEnum2 = "failed"
)

func (e FiltersStatusEnum2) ToPointer() *FiltersStatusEnum2 {
	return &e
}
func (e *FiltersStatusEnum2) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "success":
		fallthrough
	case "failed":
		*e = FiltersStatusEnum2(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FiltersStatusEnum2: %v", v)
	}
}

type FiltersStatusEnum1 string

const (
	FiltersStatusEnum1Success FiltersStatusEnum1 = "success"
	FiltersStatusEnum1Failed  FiltersStatusEnum1 = "failed"
)

func (e FiltersStatusEnum1) ToPointer() *FiltersStatusEnum1 {
	return &e
}
func (e *FiltersStatusEnum1) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "success":
		fallthrough
	case "failed":
		*e = FiltersStatusEnum1(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FiltersStatusEnum1: %v", v)
	}
}

type FiltersStatusType string

const (
	FiltersStatusTypeFiltersStatusEnum1        FiltersStatusType = "filters[status]_enum_1"
	FiltersStatusTypeArrayOfFiltersStatusEnum2 FiltersStatusType = "arrayOfFilters[status]Enum2"
)

// FiltersStatus - Filter by attempt status(es). Use bracket notation for multiple values (e.g., `filters[status][0]=success&filters[status][1]=failed`).
type FiltersStatus struct {
	FiltersStatusEnum1        *FiltersStatusEnum1  `queryParam:"inline" union:"member"`
	ArrayOfFiltersStatusEnum2 []FiltersStatusEnum2 `queryParam:"inline" union:"member"`

	Type FiltersStatusType
}

func CreateFiltersStatusFiltersStatusEnum1(filtersStatusEnum1 FiltersStatusEnum1) FiltersStatus {
	typ := FiltersStatusTypeFiltersStatusEnum1

	return FiltersStatus{
		FiltersStatusEnum1: &filtersStatusEnum1,
		Type:               typ,
	}
}

func CreateFiltersStatusArrayOfFiltersStatusEnum2(arrayOfFiltersStatusEnum2 []FiltersStatusEnum2) FiltersStatus {
	typ := FiltersStatusTypeArrayOfFiltersStatusEnum2

	return FiltersStatus{
		ArrayOfFiltersStatusEnum2: arrayOfFiltersStatusEnum2,
		Type:                      typ,
	}
}

func (u *FiltersStatus) UnmarshalJSON(data []byte) error {

	var filtersStatusEnum1 FiltersStatusEnum1 = FiltersStatusEnum1("")
	if err := utils.UnmarshalJSON(data, &filtersStatusEnum1, "", true, nil); err == nil {
		u.FiltersStatusEnum1 = &filtersStatusEnum1
		u.Type = FiltersStatusTypeFiltersStatusEnum1
		return nil
	}

	var arrayOfFiltersStatusEnum2 []FiltersStatusEnum2 = []FiltersStatusEnum2{}
	if err := utils.UnmarshalJSON(data, &arrayOfFiltersStatusEnum2, "", true, nil); err == nil {
		u.ArrayOfFiltersStatusEnum2 = arrayOfFiltersStatusEnum2
		u.Type = FiltersStatusTypeArrayOfFiltersStatusEnum2
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for FiltersStatus", string(data))
}

func (u FiltersStatus) MarshalJSON() ([]byte, error) {
	if u.FiltersStatusEnum1 != nil {
		return utils.MarshalJSON(u.FiltersStatusEnum1, "", true)
	}

	if u.ArrayOfFiltersStatusEnum2 != nil {
		return utils.MarshalJSON(u.ArrayOfFiltersStatusEnum2, "", true)
	}

	return nil, errors.New("could not marshal union type FiltersStatus: all fields are null")
}

type FiltersCodeType string

const (
	FiltersCodeTypeStr        FiltersCodeType = "str"
	FiltersCodeTypeArrayOfStr FiltersCodeType = "arrayOfStr"
)

// FiltersCode - Filter by HTTP status code(s). Use bracket notation for multiple values (e.g., `filters[code][0]=200&filters[code][1]=500`).
type FiltersCode struct {
	Str        *string  `queryParam:"inline" union:"member"`
	ArrayOfStr []string `queryParam:"inline" union:"member"`

	Type FiltersCodeType
}

func CreateFiltersCodeStr(str string) FiltersCode {
	typ := FiltersCodeTypeStr

	return FiltersCode{
		Str:  &str,
		Type: typ,
	}
}

func CreateFiltersCodeArrayOfStr(arrayOfStr []string) FiltersCode {
	typ := FiltersCodeTypeArrayOfStr

	return FiltersCode{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *FiltersCode) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = FiltersCodeTypeStr
		return nil
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = FiltersCodeTypeArrayOfStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for FiltersCode", string(data))
}

func (u FiltersCode) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type FiltersCode: all fields are null")
}

// FiltersManual - Filter by manual retry flag.
type FiltersManual string

const (
	FiltersManualTrue  FiltersManual = "true"
	FiltersManualFalse FiltersManual = "false"
)

func (e FiltersManual) ToPointer() *FiltersManual {
	return &e
}
func (e *FiltersManual) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "true":
		fallthrough
	case "false":
		*e = FiltersManual(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FiltersManual: %v", v)
	}
}

type FiltersAttemptNumberType string

const (
	FiltersAttemptNumberTypeStr        FiltersAttemptNumberType = "str"
	FiltersAttemptNumberTypeArrayOfStr FiltersAttemptNumberType = "arrayOfStr"
)

// FiltersAttemptNumber - Filter by attempt number(s). Use bracket notation for multiple values (e.g., `filters[attempt_number][0]=1&filters[attempt_number][1]=2`).
type FiltersAttemptNumber struct {
	Str        *string  `queryParam:"inline" union:"member"`
	ArrayOfStr []string `queryParam:"inline" union:"member"`

	Type FiltersAttemptNumberType
}

func CreateFiltersAttemptNumberStr(str string) FiltersAttemptNumber {
	typ := FiltersAttemptNumberTypeStr

	return FiltersAttemptNumber{
		Str:  &str,
		Type: typ,
	}
}

func CreateFiltersAttemptNumberArrayOfStr(arrayOfStr []string) FiltersAttemptNumber {
	typ := FiltersAttemptNumberTypeArrayOfStr

	return FiltersAttemptNumber{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *FiltersAttemptNumber) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = FiltersAttemptNumberTypeStr
		return nil
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = FiltersAttemptNumberTypeArrayOfStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for FiltersAttemptNumber", string(data))
}

func (u FiltersAttemptNumber) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type FiltersAttemptNumber: all fields are null")
}

type GetAttemptMetricsFiltersTenantIDType string

const (
	GetAttemptMetricsFiltersTenantIDTypeStr        GetAttemptMetricsFiltersTenantIDType = "str"
	GetAttemptMetricsFiltersTenantIDTypeArrayOfStr GetAttemptMetricsFiltersTenantIDType = "arrayOfStr"
)

// GetAttemptMetricsFiltersTenantID - Filter by tenant ID(s). Admin-only — rejected with 403 for JWT callers. Use bracket notation for multiple values (e.g., `filters[tenant_id][0]=t1&filters[tenant_id][1]=t2`).
type GetAttemptMetricsFiltersTenantID struct {
	Str        *string  `queryParam:"inline" union:"member"`
	ArrayOfStr []string `queryParam:"inline" union:"member"`

	Type GetAttemptMetricsFiltersTenantIDType
}

func CreateGetAttemptMetricsFiltersTenantIDStr(str string) GetAttemptMetricsFiltersTenantID {
	typ := GetAttemptMetricsFiltersTenantIDTypeStr

	return GetAttemptMetricsFiltersTenantID{
		Str:  &str,
		Type: typ,
	}
}

func CreateGetAttemptMetricsFiltersTenantIDArrayOfStr(arrayOfStr []string) GetAttemptMetricsFiltersTenantID {
	typ := GetAttemptMetricsFiltersTenantIDTypeArrayOfStr

	return GetAttemptMetricsFiltersTenantID{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *GetAttemptMetricsFiltersTenantID) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = GetAttemptMetricsFiltersTenantIDTypeStr
		return nil
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = GetAttemptMetricsFiltersTenantIDTypeArrayOfStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetAttemptMetricsFiltersTenantID", string(data))
}

func (u GetAttemptMetricsFiltersTenantID) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type GetAttemptMetricsFiltersTenantID: all fields are null")
}

type GetAttemptMetricsRequest struct {
	// Time range for the metrics query.
	Time GetAttemptMetricsTime `queryParam:"style=deepObject,explode=true,name=time"`
	// Time bucketing granularity. Pattern: `<number><unit>`.
	// Units: `s` (1-60), `m` (1-60), `h` (1-24), `d` (1-31), `w` (1-4), `M` (1-12).
	// When omitted, returns a single aggregate row per dimension combination.
	//
	Granularity *string `queryParam:"style=form,explode=true,name=granularity"`
	// Measures to compute. At least one required. Rate measures (`rate`, `successful_rate`, `failed_rate`) are throughput in events/second. Use bracket notation for multiple values (e.g., `measures[0]=count&measures[1]=error_rate`).
	Measures GetAttemptMetricsMeasuresUnion `queryParam:"style=form,explode=true,name=measures"`
	// Dimensions to group results by. Use bracket notation for multiple values (e.g., `dimensions[0]=status&dimensions[1]=destination_id`).
	Dimensions *GetAttemptMetricsDimensionsUnion `queryParam:"style=form,explode=true,name=dimensions"`
	// Filter by destination ID(s). Use bracket notation for multiple values (e.g., `filters[destination_id][0]=d1&filters[destination_id][1]=d2`).
	FiltersDestinationID *GetAttemptMetricsFiltersDestinationID `queryParam:"style=form,explode=true,name=filters[destination_id]"`
	// Filter by destination type(s). Use bracket notation for multiple values (e.g., `filters[destination_type][0]=webhook&filters[destination_type][1]=aws_sqs`).
	FiltersDestinationType *FiltersDestinationType `queryParam:"style=form,explode=true,name=filters[destination_type]"`
	// Filter by topic name(s). Use bracket notation for multiple values (e.g., `filters[topic][0]=user.created&filters[topic][1]=user.updated`).
	FiltersTopic *GetAttemptMetricsFiltersTopic `queryParam:"style=form,explode=true,name=filters[topic]"`
	// Filter by attempt status(es). Use bracket notation for multiple values (e.g., `filters[status][0]=success&filters[status][1]=failed`).
	FiltersStatus *FiltersStatus `queryParam:"style=form,explode=true,name=filters[status]"`
	// Filter by HTTP status code(s). Use bracket notation for multiple values (e.g., `filters[code][0]=200&filters[code][1]=500`).
	FiltersCode *FiltersCode `queryParam:"style=form,explode=true,name=filters[code]"`
	// Filter by manual retry flag.
	FiltersManual *FiltersManual `queryParam:"style=form,explode=true,name=filters[manual]"`
	// Filter by attempt number(s). Use bracket notation for multiple values (e.g., `filters[attempt_number][0]=1&filters[attempt_number][1]=2`).
	FiltersAttemptNumber *FiltersAttemptNumber `queryParam:"style=form,explode=true,name=filters[attempt_number]"`
	// Filter by tenant ID(s). Admin-only — rejected with 403 for JWT callers. Use bracket notation for multiple values (e.g., `filters[tenant_id][0]=t1&filters[tenant_id][1]=t2`).
	FiltersTenantID *GetAttemptMetricsFiltersTenantID `queryParam:"style=form,explode=true,name=filters[tenant_id]"`
}

func (g *GetAttemptMetricsRequest) GetTime() GetAttemptMetricsTime {
	if g == nil {
		return GetAttemptMetricsTime{}
	}
	return g.Time
}

func (g *GetAttemptMetricsRequest) GetGranularity() *string {
	if g == nil {
		return nil
	}
	return g.Granularity
}

func (g *GetAttemptMetricsRequest) GetMeasures() GetAttemptMetricsMeasuresUnion {
	if g == nil {
		return GetAttemptMetricsMeasuresUnion{}
	}
	return g.Measures
}

func (g *GetAttemptMetricsRequest) GetDimensions() *GetAttemptMetricsDimensionsUnion {
	if g == nil {
		return nil
	}
	return g.Dimensions
}

func (g *GetAttemptMetricsRequest) GetFiltersDestinationID() *GetAttemptMetricsFiltersDestinationID {
	if g == nil {
		return nil
	}
	return g.FiltersDestinationID
}

func (g *GetAttemptMetricsRequest) GetFiltersDestinationType() *FiltersDestinationType {
	if g == nil {
		return nil
	}
	return g.FiltersDestinationType
}

func (g *GetAttemptMetricsRequest) GetFiltersTopic() *GetAttemptMetricsFiltersTopic {
	if g == nil {
		return nil
	}
	return g.FiltersTopic
}

func (g *GetAttemptMetricsRequest) GetFiltersStatus() *FiltersStatus {
	if g == nil {
		return nil
	}
	return g.FiltersStatus
}

func (g *GetAttemptMetricsRequest) GetFiltersCode() *FiltersCode {
	if g == nil {
		return nil
	}
	return g.FiltersCode
}

func (g *GetAttemptMetricsRequest) GetFiltersManual() *FiltersManual {
	if g == nil {
		return nil
	}
	return g.FiltersManual
}

func (g *GetAttemptMetricsRequest) GetFiltersAttemptNumber() *FiltersAttemptNumber {
	if g == nil {
		return nil
	}
	return g.FiltersAttemptNumber
}

func (g *GetAttemptMetricsRequest) GetFiltersTenantID() *GetAttemptMetricsFiltersTenantID {
	if g == nil {
		return nil
	}
	return g.FiltersTenantID
}

type GetAttemptMetricsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Aggregated attempt metrics.
	MetricsResponse *components.MetricsResponse
}

func (g *GetAttemptMetricsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAttemptMetricsResponse) GetMetricsResponse() *components.MetricsResponse {
	if g == nil {
		return nil
	}
	return g.MetricsResponse
}
