// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/hookdeck/outpost/sdks/outpost-go/models/components"
)

// Type - The type of the destination.
type Type string

const (
	TypeWebhook         Type = "webhook"
	TypeAwsSqs          Type = "aws_sqs"
	TypeRabbitmq        Type = "rabbitmq"
	TypeHookdeck        Type = "hookdeck"
	TypeAwsKinesis      Type = "aws_kinesis"
	TypeAzureServicebus Type = "azure_servicebus"
	TypeAwsS3           Type = "aws_s3"
	TypeGcpPubsub       Type = "gcp_pubsub"
	TypeKafka           Type = "kafka"
)

func (e Type) ToPointer() *Type {
	return &e
}
func (e *Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "webhook":
		fallthrough
	case "aws_sqs":
		fallthrough
	case "rabbitmq":
		fallthrough
	case "hookdeck":
		fallthrough
	case "aws_kinesis":
		fallthrough
	case "azure_servicebus":
		fallthrough
	case "aws_s3":
		fallthrough
	case "gcp_pubsub":
		fallthrough
	case "kafka":
		*e = Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Type: %v", v)
	}
}

type GetDestinationTypeSchemaRequest struct {
	// The type of the destination.
	Type Type `pathParam:"style=simple,explode=false,name=type"`
}

func (g *GetDestinationTypeSchemaRequest) GetType() Type {
	if g == nil {
		return Type("")
	}
	return g.Type
}

type GetDestinationTypeSchemaResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The schema for the specified destination type.
	DestinationTypeSchema *components.DestinationTypeSchema
}

func (g *GetDestinationTypeSchemaResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetDestinationTypeSchemaResponse) GetDestinationTypeSchema() *components.DestinationTypeSchema {
	if g == nil {
		return nil
	}
	return g.DestinationTypeSchema
}
