// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/utils"
	"github.com/hookdeck/outpost/sdks/outpost-go/models/components"
	"time"
)

type GetEventMetricsMeasuresEnum2 string

const (
	GetEventMetricsMeasuresEnum2Count GetEventMetricsMeasuresEnum2 = "count"
	GetEventMetricsMeasuresEnum2Rate  GetEventMetricsMeasuresEnum2 = "rate"
)

func (e GetEventMetricsMeasuresEnum2) ToPointer() *GetEventMetricsMeasuresEnum2 {
	return &e
}
func (e *GetEventMetricsMeasuresEnum2) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "count":
		fallthrough
	case "rate":
		*e = GetEventMetricsMeasuresEnum2(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetEventMetricsMeasuresEnum2: %v", v)
	}
}

type GetEventMetricsMeasuresEnum1 string

const (
	GetEventMetricsMeasuresEnum1Count GetEventMetricsMeasuresEnum1 = "count"
	GetEventMetricsMeasuresEnum1Rate  GetEventMetricsMeasuresEnum1 = "rate"
)

func (e GetEventMetricsMeasuresEnum1) ToPointer() *GetEventMetricsMeasuresEnum1 {
	return &e
}
func (e *GetEventMetricsMeasuresEnum1) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "count":
		fallthrough
	case "rate":
		*e = GetEventMetricsMeasuresEnum1(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetEventMetricsMeasuresEnum1: %v", v)
	}
}

type GetEventMetricsMeasuresUnionType string

const (
	GetEventMetricsMeasuresUnionTypeGetEventMetricsMeasuresEnum1        GetEventMetricsMeasuresUnionType = "getEventMetrics_measures_enum_1"
	GetEventMetricsMeasuresUnionTypeArrayOfGetEventMetricsMeasuresEnum2 GetEventMetricsMeasuresUnionType = "arrayOfGetEventMetricsMeasuresEnum2"
)

// GetEventMetricsMeasuresUnion - Measures to compute. At least one required. `rate` is events/second throughput. Use bracket notation for multiple values (e.g., `measures[0]=count`).
type GetEventMetricsMeasuresUnion struct {
	GetEventMetricsMeasuresEnum1        *GetEventMetricsMeasuresEnum1  `queryParam:"inline" union:"member"`
	ArrayOfGetEventMetricsMeasuresEnum2 []GetEventMetricsMeasuresEnum2 `queryParam:"inline" union:"member"`

	Type GetEventMetricsMeasuresUnionType
}

func CreateGetEventMetricsMeasuresUnionGetEventMetricsMeasuresEnum1(getEventMetricsMeasuresEnum1 GetEventMetricsMeasuresEnum1) GetEventMetricsMeasuresUnion {
	typ := GetEventMetricsMeasuresUnionTypeGetEventMetricsMeasuresEnum1

	return GetEventMetricsMeasuresUnion{
		GetEventMetricsMeasuresEnum1: &getEventMetricsMeasuresEnum1,
		Type:                         typ,
	}
}

func CreateGetEventMetricsMeasuresUnionArrayOfGetEventMetricsMeasuresEnum2(arrayOfGetEventMetricsMeasuresEnum2 []GetEventMetricsMeasuresEnum2) GetEventMetricsMeasuresUnion {
	typ := GetEventMetricsMeasuresUnionTypeArrayOfGetEventMetricsMeasuresEnum2

	return GetEventMetricsMeasuresUnion{
		ArrayOfGetEventMetricsMeasuresEnum2: arrayOfGetEventMetricsMeasuresEnum2,
		Type:                                typ,
	}
}

func (u *GetEventMetricsMeasuresUnion) UnmarshalJSON(data []byte) error {

	var getEventMetricsMeasuresEnum1 GetEventMetricsMeasuresEnum1 = GetEventMetricsMeasuresEnum1("")
	if err := utils.UnmarshalJSON(data, &getEventMetricsMeasuresEnum1, "", true, nil); err == nil {
		u.GetEventMetricsMeasuresEnum1 = &getEventMetricsMeasuresEnum1
		u.Type = GetEventMetricsMeasuresUnionTypeGetEventMetricsMeasuresEnum1
		return nil
	}

	var arrayOfGetEventMetricsMeasuresEnum2 []GetEventMetricsMeasuresEnum2 = []GetEventMetricsMeasuresEnum2{}
	if err := utils.UnmarshalJSON(data, &arrayOfGetEventMetricsMeasuresEnum2, "", true, nil); err == nil {
		u.ArrayOfGetEventMetricsMeasuresEnum2 = arrayOfGetEventMetricsMeasuresEnum2
		u.Type = GetEventMetricsMeasuresUnionTypeArrayOfGetEventMetricsMeasuresEnum2
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetEventMetricsMeasuresUnion", string(data))
}

func (u GetEventMetricsMeasuresUnion) MarshalJSON() ([]byte, error) {
	if u.GetEventMetricsMeasuresEnum1 != nil {
		return utils.MarshalJSON(u.GetEventMetricsMeasuresEnum1, "", true)
	}

	if u.ArrayOfGetEventMetricsMeasuresEnum2 != nil {
		return utils.MarshalJSON(u.ArrayOfGetEventMetricsMeasuresEnum2, "", true)
	}

	return nil, errors.New("could not marshal union type GetEventMetricsMeasuresUnion: all fields are null")
}

type GetEventMetricsDimensionsEnum2 string

const (
	GetEventMetricsDimensionsEnum2TenantID      GetEventMetricsDimensionsEnum2 = "tenant_id"
	GetEventMetricsDimensionsEnum2Topic         GetEventMetricsDimensionsEnum2 = "topic"
	GetEventMetricsDimensionsEnum2DestinationID GetEventMetricsDimensionsEnum2 = "destination_id"
)

func (e GetEventMetricsDimensionsEnum2) ToPointer() *GetEventMetricsDimensionsEnum2 {
	return &e
}
func (e *GetEventMetricsDimensionsEnum2) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "tenant_id":
		fallthrough
	case "topic":
		fallthrough
	case "destination_id":
		*e = GetEventMetricsDimensionsEnum2(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetEventMetricsDimensionsEnum2: %v", v)
	}
}

type GetEventMetricsDimensionsEnum1 string

const (
	GetEventMetricsDimensionsEnum1TenantID      GetEventMetricsDimensionsEnum1 = "tenant_id"
	GetEventMetricsDimensionsEnum1Topic         GetEventMetricsDimensionsEnum1 = "topic"
	GetEventMetricsDimensionsEnum1DestinationID GetEventMetricsDimensionsEnum1 = "destination_id"
)

func (e GetEventMetricsDimensionsEnum1) ToPointer() *GetEventMetricsDimensionsEnum1 {
	return &e
}
func (e *GetEventMetricsDimensionsEnum1) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "tenant_id":
		fallthrough
	case "topic":
		fallthrough
	case "destination_id":
		*e = GetEventMetricsDimensionsEnum1(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetEventMetricsDimensionsEnum1: %v", v)
	}
}

type GetEventMetricsDimensionsUnionType string

const (
	GetEventMetricsDimensionsUnionTypeGetEventMetricsDimensionsEnum1        GetEventMetricsDimensionsUnionType = "getEventMetrics_dimensions_enum_1"
	GetEventMetricsDimensionsUnionTypeArrayOfGetEventMetricsDimensionsEnum2 GetEventMetricsDimensionsUnionType = "arrayOfGetEventMetricsDimensionsEnum2"
)

// GetEventMetricsDimensionsUnion - Dimensions to group results by. Use bracket notation for multiple values (e.g., `dimensions[0]=topic&dimensions[1]=destination_id`).
type GetEventMetricsDimensionsUnion struct {
	GetEventMetricsDimensionsEnum1        *GetEventMetricsDimensionsEnum1  `queryParam:"inline" union:"member"`
	ArrayOfGetEventMetricsDimensionsEnum2 []GetEventMetricsDimensionsEnum2 `queryParam:"inline" union:"member"`

	Type GetEventMetricsDimensionsUnionType
}

func CreateGetEventMetricsDimensionsUnionGetEventMetricsDimensionsEnum1(getEventMetricsDimensionsEnum1 GetEventMetricsDimensionsEnum1) GetEventMetricsDimensionsUnion {
	typ := GetEventMetricsDimensionsUnionTypeGetEventMetricsDimensionsEnum1

	return GetEventMetricsDimensionsUnion{
		GetEventMetricsDimensionsEnum1: &getEventMetricsDimensionsEnum1,
		Type:                           typ,
	}
}

func CreateGetEventMetricsDimensionsUnionArrayOfGetEventMetricsDimensionsEnum2(arrayOfGetEventMetricsDimensionsEnum2 []GetEventMetricsDimensionsEnum2) GetEventMetricsDimensionsUnion {
	typ := GetEventMetricsDimensionsUnionTypeArrayOfGetEventMetricsDimensionsEnum2

	return GetEventMetricsDimensionsUnion{
		ArrayOfGetEventMetricsDimensionsEnum2: arrayOfGetEventMetricsDimensionsEnum2,
		Type:                                  typ,
	}
}

func (u *GetEventMetricsDimensionsUnion) UnmarshalJSON(data []byte) error {

	var getEventMetricsDimensionsEnum1 GetEventMetricsDimensionsEnum1 = GetEventMetricsDimensionsEnum1("")
	if err := utils.UnmarshalJSON(data, &getEventMetricsDimensionsEnum1, "", true, nil); err == nil {
		u.GetEventMetricsDimensionsEnum1 = &getEventMetricsDimensionsEnum1
		u.Type = GetEventMetricsDimensionsUnionTypeGetEventMetricsDimensionsEnum1
		return nil
	}

	var arrayOfGetEventMetricsDimensionsEnum2 []GetEventMetricsDimensionsEnum2 = []GetEventMetricsDimensionsEnum2{}
	if err := utils.UnmarshalJSON(data, &arrayOfGetEventMetricsDimensionsEnum2, "", true, nil); err == nil {
		u.ArrayOfGetEventMetricsDimensionsEnum2 = arrayOfGetEventMetricsDimensionsEnum2
		u.Type = GetEventMetricsDimensionsUnionTypeArrayOfGetEventMetricsDimensionsEnum2
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetEventMetricsDimensionsUnion", string(data))
}

func (u GetEventMetricsDimensionsUnion) MarshalJSON() ([]byte, error) {
	if u.GetEventMetricsDimensionsEnum1 != nil {
		return utils.MarshalJSON(u.GetEventMetricsDimensionsEnum1, "", true)
	}

	if u.ArrayOfGetEventMetricsDimensionsEnum2 != nil {
		return utils.MarshalJSON(u.ArrayOfGetEventMetricsDimensionsEnum2, "", true)
	}

	return nil, errors.New("could not marshal union type GetEventMetricsDimensionsUnion: all fields are null")
}

type GetEventMetricsFiltersTopicType string

const (
	GetEventMetricsFiltersTopicTypeStr        GetEventMetricsFiltersTopicType = "str"
	GetEventMetricsFiltersTopicTypeArrayOfStr GetEventMetricsFiltersTopicType = "arrayOfStr"
)

// GetEventMetricsFiltersTopic - Filter by topic name(s). Use bracket notation for multiple values (e.g., `filters[topic][0]=user.created&filters[topic][1]=user.updated`).
type GetEventMetricsFiltersTopic struct {
	Str        *string  `queryParam:"inline" union:"member"`
	ArrayOfStr []string `queryParam:"inline" union:"member"`

	Type GetEventMetricsFiltersTopicType
}

func CreateGetEventMetricsFiltersTopicStr(str string) GetEventMetricsFiltersTopic {
	typ := GetEventMetricsFiltersTopicTypeStr

	return GetEventMetricsFiltersTopic{
		Str:  &str,
		Type: typ,
	}
}

func CreateGetEventMetricsFiltersTopicArrayOfStr(arrayOfStr []string) GetEventMetricsFiltersTopic {
	typ := GetEventMetricsFiltersTopicTypeArrayOfStr

	return GetEventMetricsFiltersTopic{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *GetEventMetricsFiltersTopic) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = GetEventMetricsFiltersTopicTypeStr
		return nil
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = GetEventMetricsFiltersTopicTypeArrayOfStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetEventMetricsFiltersTopic", string(data))
}

func (u GetEventMetricsFiltersTopic) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type GetEventMetricsFiltersTopic: all fields are null")
}

type GetEventMetricsFiltersDestinationIDType string

const (
	GetEventMetricsFiltersDestinationIDTypeStr        GetEventMetricsFiltersDestinationIDType = "str"
	GetEventMetricsFiltersDestinationIDTypeArrayOfStr GetEventMetricsFiltersDestinationIDType = "arrayOfStr"
)

// GetEventMetricsFiltersDestinationID - Filter by destination ID(s). Use bracket notation for multiple values (e.g., `filters[destination_id][0]=d1&filters[destination_id][1]=d2`).
type GetEventMetricsFiltersDestinationID struct {
	Str        *string  `queryParam:"inline" union:"member"`
	ArrayOfStr []string `queryParam:"inline" union:"member"`

	Type GetEventMetricsFiltersDestinationIDType
}

func CreateGetEventMetricsFiltersDestinationIDStr(str string) GetEventMetricsFiltersDestinationID {
	typ := GetEventMetricsFiltersDestinationIDTypeStr

	return GetEventMetricsFiltersDestinationID{
		Str:  &str,
		Type: typ,
	}
}

func CreateGetEventMetricsFiltersDestinationIDArrayOfStr(arrayOfStr []string) GetEventMetricsFiltersDestinationID {
	typ := GetEventMetricsFiltersDestinationIDTypeArrayOfStr

	return GetEventMetricsFiltersDestinationID{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *GetEventMetricsFiltersDestinationID) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = GetEventMetricsFiltersDestinationIDTypeStr
		return nil
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = GetEventMetricsFiltersDestinationIDTypeArrayOfStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetEventMetricsFiltersDestinationID", string(data))
}

func (u GetEventMetricsFiltersDestinationID) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type GetEventMetricsFiltersDestinationID: all fields are null")
}

type GetEventMetricsFiltersTenantIDType string

const (
	GetEventMetricsFiltersTenantIDTypeStr        GetEventMetricsFiltersTenantIDType = "str"
	GetEventMetricsFiltersTenantIDTypeArrayOfStr GetEventMetricsFiltersTenantIDType = "arrayOfStr"
)

// GetEventMetricsFiltersTenantID - Filter by tenant ID(s). Admin-only — rejected with 403 for JWT callers. Use bracket notation for multiple values (e.g., `filters[tenant_id][0]=t1&filters[tenant_id][1]=t2`).
type GetEventMetricsFiltersTenantID struct {
	Str        *string  `queryParam:"inline" union:"member"`
	ArrayOfStr []string `queryParam:"inline" union:"member"`

	Type GetEventMetricsFiltersTenantIDType
}

func CreateGetEventMetricsFiltersTenantIDStr(str string) GetEventMetricsFiltersTenantID {
	typ := GetEventMetricsFiltersTenantIDTypeStr

	return GetEventMetricsFiltersTenantID{
		Str:  &str,
		Type: typ,
	}
}

func CreateGetEventMetricsFiltersTenantIDArrayOfStr(arrayOfStr []string) GetEventMetricsFiltersTenantID {
	typ := GetEventMetricsFiltersTenantIDTypeArrayOfStr

	return GetEventMetricsFiltersTenantID{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *GetEventMetricsFiltersTenantID) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = GetEventMetricsFiltersTenantIDTypeStr
		return nil
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = GetEventMetricsFiltersTenantIDTypeArrayOfStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetEventMetricsFiltersTenantID", string(data))
}

func (u GetEventMetricsFiltersTenantID) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type GetEventMetricsFiltersTenantID: all fields are null")
}

type GetEventMetricsRequest struct {
	// Start of the time range (inclusive). ISO 8601 timestamp.
	TimeStart time.Time `queryParam:"style=form,explode=true,name=time[start]"`
	// End of the time range (exclusive). ISO 8601 timestamp.
	TimeEnd time.Time `queryParam:"style=form,explode=true,name=time[end]"`
	// Time bucketing granularity. Pattern: `<number><unit>`.
	// Units: `s` (1-60), `m` (1-60), `h` (1-24), `d` (1-31), `w` (1-4), `M` (1-12).
	// When omitted, returns a single aggregate row per dimension combination.
	//
	Granularity *string `queryParam:"style=form,explode=true,name=granularity"`
	// Measures to compute. At least one required. `rate` is events/second throughput. Use bracket notation for multiple values (e.g., `measures[0]=count`).
	Measures GetEventMetricsMeasuresUnion `queryParam:"style=form,explode=true,name=measures"`
	// Dimensions to group results by. Use bracket notation for multiple values (e.g., `dimensions[0]=topic&dimensions[1]=destination_id`).
	Dimensions *GetEventMetricsDimensionsUnion `queryParam:"style=form,explode=true,name=dimensions"`
	// Filter by topic name(s). Use bracket notation for multiple values (e.g., `filters[topic][0]=user.created&filters[topic][1]=user.updated`).
	FiltersTopic *GetEventMetricsFiltersTopic `queryParam:"style=form,explode=true,name=filters[topic]"`
	// Filter by destination ID(s). Use bracket notation for multiple values (e.g., `filters[destination_id][0]=d1&filters[destination_id][1]=d2`).
	FiltersDestinationID *GetEventMetricsFiltersDestinationID `queryParam:"style=form,explode=true,name=filters[destination_id]"`
	// Filter by tenant ID(s). Admin-only — rejected with 403 for JWT callers. Use bracket notation for multiple values (e.g., `filters[tenant_id][0]=t1&filters[tenant_id][1]=t2`).
	FiltersTenantID *GetEventMetricsFiltersTenantID `queryParam:"style=form,explode=true,name=filters[tenant_id]"`
}

func (g GetEventMetricsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetEventMetricsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetEventMetricsRequest) GetTimeStart() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.TimeStart
}

func (g *GetEventMetricsRequest) GetTimeEnd() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.TimeEnd
}

func (g *GetEventMetricsRequest) GetGranularity() *string {
	if g == nil {
		return nil
	}
	return g.Granularity
}

func (g *GetEventMetricsRequest) GetMeasures() GetEventMetricsMeasuresUnion {
	if g == nil {
		return GetEventMetricsMeasuresUnion{}
	}
	return g.Measures
}

func (g *GetEventMetricsRequest) GetDimensions() *GetEventMetricsDimensionsUnion {
	if g == nil {
		return nil
	}
	return g.Dimensions
}

func (g *GetEventMetricsRequest) GetFiltersTopic() *GetEventMetricsFiltersTopic {
	if g == nil {
		return nil
	}
	return g.FiltersTopic
}

func (g *GetEventMetricsRequest) GetFiltersDestinationID() *GetEventMetricsFiltersDestinationID {
	if g == nil {
		return nil
	}
	return g.FiltersDestinationID
}

func (g *GetEventMetricsRequest) GetFiltersTenantID() *GetEventMetricsFiltersTenantID {
	if g == nil {
		return nil
	}
	return g.FiltersTenantID
}

type GetEventMetricsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Aggregated event metrics.
	MetricsResponse *components.MetricsResponse
}

func (g *GetEventMetricsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetEventMetricsResponse) GetMetricsResponse() *components.MetricsResponse {
	if g == nil {
		return nil
	}
	return g.MetricsResponse
}
