// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hookdeck/outpost/sdks/outpost-go/models/components"
)

type ListTenantTopicsGlobals struct {
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
}

func (l *ListTenantTopicsGlobals) GetTenantID() *string {
	if l == nil {
		return nil
	}
	return l.TenantID
}

type ListTenantTopicsRequest struct {
	// The ID of the tenant. Required when using AdminApiKey authentication.
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
}

func (l *ListTenantTopicsRequest) GetTenantID() *string {
	if l == nil {
		return nil
	}
	return l.TenantID
}

type ListTenantTopicsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A list of topic names.
	Strings []string
}

func (l *ListTenantTopicsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListTenantTopicsResponse) GetStrings() []string {
	if l == nil {
		return nil
	}
	return l.Strings
}
