// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hookdeck/outpost/sdks/outpost-go/models/components"
)

type ListTopicsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A list of topic names.
	Strings []string
}

func (l *ListTopicsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListTopicsResponse) GetStrings() []string {
	if l == nil {
		return nil
	}
	return l.Strings
}
