// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hookdeck/outpost/sdks/outpost-go/models/components"
)

type ListOperatorEventDestinationTypeSchemasResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A list of destination type schemas.
	DestinationTypeSchemas []components.DestinationTypeSchema
}

func (l *ListOperatorEventDestinationTypeSchemasResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListOperatorEventDestinationTypeSchemasResponse) GetDestinationTypeSchemas() []components.DestinationTypeSchema {
	if l == nil {
		return nil
	}
	return l.DestinationTypeSchemas
}
