// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hookdeck/outpost/sdks/outpost-go/models/components"
)

type ListTenantDestinationTypeSchemasGlobals struct {
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
}

func (l *ListTenantDestinationTypeSchemasGlobals) GetTenantID() *string {
	if l == nil {
		return nil
	}
	return l.TenantID
}

type ListTenantDestinationTypeSchemasRequest struct {
	// The ID of the tenant. Required when using AdminApiKey authentication.
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
}

func (l *ListTenantDestinationTypeSchemasRequest) GetTenantID() *string {
	if l == nil {
		return nil
	}
	return l.TenantID
}

type ListTenantDestinationTypeSchemasResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A list of destination type schemas.
	DestinationTypeSchemas []components.DestinationTypeSchema
}

func (l *ListTenantDestinationTypeSchemasResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListTenantDestinationTypeSchemasResponse) GetDestinationTypeSchemas() []components.DestinationTypeSchema {
	if l == nil {
		return nil
	}
	return l.DestinationTypeSchemas
}
