// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/utils"
)

type DataType string

const (
	DataTypeArrayOfStr DataType = "arrayOfStr"
	DataTypeMapOfAny   DataType = "mapOfAny"
)

// Data - Additional error details. For validation errors, this is an array of human-readable messages.
type Data struct {
	ArrayOfStr []string       `queryParam:"inline" union:"member"`
	MapOfAny   map[string]any `queryParam:"inline" union:"member"`

	Type DataType
}

var _ error = &Data{}

func CreateDataArrayOfStr(arrayOfStr []string) Data {
	typ := DataTypeArrayOfStr

	return Data{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func CreateDataMapOfAny(mapOfAny map[string]any) Data {
	typ := DataTypeMapOfAny

	return Data{
		MapOfAny: mapOfAny,
		Type:     typ,
	}
}

func (u *Data) UnmarshalJSON(data []byte) error {

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = DataTypeArrayOfStr
		return nil
	}

	var mapOfAny map[string]any = map[string]any{}
	if err := utils.UnmarshalJSON(data, &mapOfAny, "", true, nil); err == nil {
		u.MapOfAny = mapOfAny
		u.Type = DataTypeMapOfAny
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Data", string(data))
}

func (u Data) MarshalJSON() ([]byte, error) {
	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	if u.MapOfAny != nil {
		return utils.MarshalJSON(u.MapOfAny, "", true)
	}

	return nil, errors.New("could not marshal union type Data: all fields are null")
}

func (u Data) Error() string {
	switch u.Type {
	case DataTypeArrayOfStr:
		data, _ := json.Marshal(u.ArrayOfStr)
		return string(data)
	case DataTypeMapOfAny:
		data, _ := json.Marshal(u.MapOfAny)
		return string(data)
	default:
		return "unknown error"
	}
}

// APIErrorResponse - Standard error response format.
type APIErrorResponse struct {
	// HTTP status code.
	Status *int64 `json:"status,omitempty"`
	// Human-readable error message.
	Message *string `json:"message,omitempty"`
	// Additional error details. For validation errors, this is an array of human-readable messages.
	Data *Data `json:"data,omitempty"`
}

var _ error = &APIErrorResponse{}

func (e *APIErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
