"""MCP Events helpers for Outpost.

Hand-written, not generated by Speakeasy: this module is not tracked in
.speakeasy/gen.lock, so it survives SDK regeneration.

An MCP server offers MCP Events by answering ``events/list``,
``events/subscribe`` and ``events/unsubscribe``. Outpost does the work behind
three endpoints; this module proxies the methods to them:

- ``MCPEventsClient``: a raw-JSON client for the three endpoints. Results are
  forwarded verbatim, never re-shaped by a model.
- ``MCPEventsHandlers``: transport-agnostic async handlers taking the
  authenticated principal and the raw MCP params.
- ``register()``: wires the handlers into a server built with the ``mcp``
  package (version 2 or later).
"""

from __future__ import annotations

import inspect
import json
from dataclasses import dataclass
from types import MappingProxyType
from typing import Any, Awaitable, Callable, Literal, Mapping, Optional, Protocol, Sequence, Union, cast
from urllib.parse import quote, urlsplit, urlunsplit

import anyio
import httpx
from pydantic import BaseModel, ConfigDict

__all__ = [
    "DEFAULT_MAX_RESPONSE_BYTES",
    "DEFAULT_TIMEOUT_MS",
    "ERROR_CODE_PROFILES",
    "EXTENSION_ID",
    "ErrorCodes",
    "JSONRPCError",
    "MCPError",
    "MCPEventsAPI",
    "MCPEventsClient",
    "MCPEventsHandlers",
    "MCPEventsRequestError",
    "create_client",
    "mcp_error_from",
    "register",
]

DEFAULT_TIMEOUT_MS = 30_000
"""Per-call timeout. Above Outpost's own 20s subscribe deadline: subscribe
verifies the callback synchronously."""

DEFAULT_MAX_RESPONSE_BYTES = 8 * 1024 * 1024

EXTENSION_ID = "io.modelcontextprotocol/events"
"""The extension identifier SEP-3415 advertises under ``capabilities.extensions``."""

_MAX_ERROR_BODY_CHARS = 1024
# Bounds the body parsed out of a duck-typed error; real mcp_error bodies are
# a few hundred bytes.
_MAX_DUCK_BODY_CHARS = 64 * 1024

Method = Literal["events/list", "events/subscribe", "events/unsubscribe"]


@dataclass(frozen=True)
class ErrorCodes:
    """JSON-RPC codes for the MCP Events error kinds.

    Outpost fills ``code`` itself in every ``mcp_error`` it returns (its
    ``MCP_ERROR_CODES`` setting). These codes only cover the errors raised
    locally (a missing principal, a topic outside the allowlist, malformed
    params), so pick the profile matching the Outpost setting.
    """

    invalid_params: int
    not_found: int
    forbidden: int
    resource_exhausted: int
    unsupported: int
    callback_endpoint_error: int
    internal_error: int = -32603


ERROR_CODE_PROFILES: Mapping[str, ErrorCodes] = MappingProxyType(
    {
        # The MCP Events design sketch numbering, which ChatGPT follows.
        "sketch": ErrorCodes(-32602, -32011, -32012, -32013, -32014, -32015),
        # The provisional SEP-3415 numbering.
        "sep-3415": ErrorCodes(-32602, -32023, -32024, -32025, -32026, -32027),
    }
)


def _resolve_codes(codes: Union[str, ErrorCodes, None]) -> ErrorCodes:
    if codes is None:
        return ERROR_CODE_PROFILES["sketch"]
    if isinstance(codes, ErrorCodes):
        return codes
    profile = ERROR_CODE_PROFILES.get(codes)
    if profile is None:
        raise ValueError(f"unknown MCP Events error code profile: {codes!r}")
    return profile


class MCPError(Exception):
    """Outpost rejected an MCP call with an ``mcp_error`` (HTTP 422).

    ``code``, ``message`` and ``data`` are the JSON-RPC error to send back.
    """

    def __init__(self, mcp_error: dict[str, Any], status_code: int = 422) -> None:
        super().__init__(mcp_error["message"])
        self.mcp_error = mcp_error
        self.status_code = status_code
        self.kind: str = mcp_error.get("kind", "")
        self.code: int = mcp_error["code"]
        self.message: str = mcp_error["message"]
        self.data: Any = mcp_error.get("data")


class MCPEventsRequestError(Exception):
    """Any other failure of an MCP endpoint call: a non-422 status, a network
    error, a timeout or a malformed response. ``body`` holds at most the first
    KiB of the response, for logs. Never forward it to MCP clients."""

    def __init__(
        self,
        message: str,
        *,
        status_code: Optional[int] = None,
        body: Optional[str] = None,
    ) -> None:
        super().__init__(message)
        self.status_code = status_code
        self.body = body


class JSONRPCError(Exception):
    """A JSON-RPC error raised by the handlers, to send back as is.

    Raise it from ``resolve_tenant``, ``allowed_topics`` or
    ``resolve_principal`` to answer with your own error; any other exception
    from them becomes a generic internal error.
    """

    def __init__(self, code: int, message: str, data: Any = None) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.data = data


def _field(value: Any, key: str) -> Any:
    return value.get(key) if isinstance(value, Mapping) else getattr(value, key, None)


def _as_mcp_error(value: Any) -> Optional[dict[str, Any]]:
    """Validates an mcp_error object (a mapping, or a model with attributes)."""
    if value is None:
        return None
    code, message, kind = _field(value, "code"), _field(value, "message"), _field(value, "kind")
    if not isinstance(code, int) or isinstance(code, bool) or not isinstance(message, str):
        return None
    out: dict[str, Any] = {"kind": kind if isinstance(kind, str) else "", "code": code, "message": message}
    data = _field(value, "data")
    if data is not None:
        out["data"] = data.model_dump(mode="json", by_alias=True) if isinstance(data, BaseModel) else data
    return out


def mcp_error_from(err: BaseException) -> Optional[dict[str, Any]]:
    """Returns the ``mcp_error`` an exception carries, by duck typing.

    Recognises this module's MCPError, any exception with an ``mcp_error``
    attribute, one whose ``data`` has an ``mcp_error`` (generated SDK error
    classes), and an Outpost HTTP error with status 422 and a JSON ``body``.
    Returns None for anything else, including malformed objects.
    """
    if isinstance(err, MCPError):
        return err.mcp_error
    found = _as_mcp_error(getattr(err, "mcp_error", None))
    if found is None:
        found = _as_mcp_error(getattr(getattr(err, "data", None), "mcp_error", None))
    if found is not None:
        return found
    body = getattr(err, "body", None)
    if getattr(err, "status_code", None) == 422 and isinstance(body, str) and len(body) <= _MAX_DUCK_BODY_CHARS:
        try:
            parsed = json.loads(body)
        except ValueError:
            return None
        if isinstance(parsed, dict):
            return _as_mcp_error(parsed.get("mcp_error"))
    return None


class MCPEventsAPI(Protocol):
    """The three Outpost calls the handlers use. MCP failures raise MCPError."""

    async def list_events(
        self,
        tenant_id: str,
        *,
        cursor: Optional[str] = None,
        topics: Optional[Sequence[str]] = None,
        limit: Optional[int] = None,
    ) -> dict[str, Any]: ...

    async def subscribe(self, tenant_id: str, body: Mapping[str, Any]) -> dict[str, Any]: ...

    async def unsubscribe(self, tenant_id: str, body: Mapping[str, Any]) -> dict[str, Any]: ...


ApiKey = Union[str, Callable[[], Union[Optional[str], Awaitable[Optional[str]]]], None]


class MCPEventsClient:
    """A raw-JSON client for the Outpost MCP endpoints.

    ``server_url`` is the Outpost API base URL, for example
    ``http://localhost:3333/api/v2``. The MCP endpoints exist in API v2 only,
    so a URL ending in ``/api/v1`` is rewritten to ``/api/v2``.
    """

    def __init__(
        self,
        server_url: str,
        api_key: ApiKey = None,
        *,
        async_client: Optional[Any] = None,
        timeout_ms: Optional[int] = None,
        max_response_bytes: Optional[int] = None,
    ) -> None:
        self._base_url = _normalize_base_url(server_url)
        self._api_key = api_key
        self._client = async_client
        self._owns_client = async_client is None
        self._timeout = (timeout_ms if timeout_ms and timeout_ms > 0 else DEFAULT_TIMEOUT_MS) / 1000
        self._max_response_bytes = (
            max_response_bytes if max_response_bytes and max_response_bytes > 0 else DEFAULT_MAX_RESPONSE_BYTES
        )

    @classmethod
    def from_outpost(cls, outpost: Any, **kwargs: Any) -> MCPEventsClient:
        """Builds a client from an ``outpost_sdk.Outpost`` instance: its server
        URL, API key, async HTTP client and timeout."""
        config = outpost.sdk_configuration
        server_url, _ = config.get_server_details()
        security = config.security

        def api_key() -> Optional[str]:
            sec = security() if callable(security) else security
            return getattr(sec, "api_key", None)

        kwargs.setdefault("async_client", config.async_client)
        kwargs.setdefault("timeout_ms", config.timeout_ms)
        return cls(server_url, api_key if security is not None else None, **kwargs)

    @property
    def base_url(self) -> str:
        """The base URL the endpoints are resolved against (always API v2)."""
        return self._base_url

    async def __aenter__(self) -> MCPEventsClient:
        return self

    async def __aexit__(self, *exc: Any) -> None:
        await self.aclose()

    async def aclose(self) -> None:
        """Closes the HTTP client this instance created (never a supplied one)."""
        if self._owns_client and self._client is not None:
            await self._client.aclose()
            self._client = None

    async def list_events(
        self,
        tenant_id: str,
        *,
        cursor: Optional[str] = None,
        topics: Optional[Sequence[str]] = None,
        limit: Optional[int] = None,
    ) -> dict[str, Any]:
        """GET /tenants/{tenant_id}/mcp/events, the ``events/list`` result.

        ``topics=None`` means no filter; an empty list means no topics.
        """
        query: list[tuple[str, str]] = []
        if cursor is not None:
            query.append(("cursor", cursor))
        if topics is not None:
            # Present but empty means "no topics" to Outpost.
            query.append(("topics", ",".join(topics)))
        if limit is not None:
            query.append(("limit", str(int(limit))))
        return await self._call("GET", tenant_id, "mcp/events", None, query)

    async def subscribe(self, tenant_id: str, body: Mapping[str, Any]) -> dict[str, Any]:
        """PUT /tenants/{tenant_id}/mcp/subscriptions, the ``events/subscribe`` result.

        ``body`` is ``{"principal", "params"}`` plus the optional ``filter``,
        ``metadata`` and ``allowed_topics``.
        """
        return await self._call("PUT", tenant_id, "mcp/subscriptions", body, None)

    async def unsubscribe(self, tenant_id: str, body: Mapping[str, Any]) -> dict[str, Any]:
        """POST /tenants/{tenant_id}/mcp/subscriptions/unsubscribe, always ``{}``."""
        return await self._call("POST", tenant_id, "mcp/subscriptions/unsubscribe", body, None)

    async def _call(
        self,
        method: str,
        tenant_id: str,
        path: str,
        body: Optional[Mapping[str, Any]],
        query: Optional[list[tuple[str, str]]],
    ) -> dict[str, Any]:
        url = f"{self._base_url}tenants/{_encode_tenant_id(tenant_id)}/{path}"
        # identity: the size cap then applies to what is actually buffered.
        headers = {"Accept": "application/json", "Accept-Encoding": "identity"}
        api_key = self._api_key() if callable(self._api_key) else self._api_key
        if inspect.isawaitable(api_key):
            api_key = await api_key
        if api_key:
            headers["Authorization"] = api_key if api_key[:7].lower() == "bearer " else f"Bearer {api_key}"
        content: Optional[bytes] = None
        if body is not None:
            headers["Content-Type"] = "application/json"
            try:
                content = json.dumps(body, separators=(",", ":"), ensure_ascii=False, allow_nan=False).encode()
            except (TypeError, ValueError) as err:
                raise MCPEventsRequestError("request body is not JSON serializable") from err

        if self._client is None:
            self._client = httpx.AsyncClient()
        client = self._client
        try:
            with anyio.fail_after(self._timeout):
                request = client.build_request(
                    method, url, params=query or None, content=content, headers=headers, timeout=self._timeout
                )
                # Outpost never redirects; following one would replay the API key.
                response = await client.send(request, stream=True, follow_redirects=False)
                try:
                    text = await _read_capped(response, self._max_response_bytes)
                finally:
                    # Release the connection even when the timeout cancelled us.
                    with anyio.CancelScope(shield=True):
                        await response.aclose()
        except TimeoutError as err:
            raise MCPEventsRequestError("Outpost request timed out") from err
        except httpx.HTTPError as err:
            raise MCPEventsRequestError("Outpost request failed") from err
        return _parse_response(response.status_code, text)


def create_client(source: Any) -> MCPEventsAPI:
    """Builds the client for any accepted source: an ``outpost_sdk.Outpost``
    instance, an object already implementing the three calls, or a mapping
    ``{"server_url": ..., "api_key": ...}`` (plus any MCPEventsClient option)."""
    if all(callable(getattr(source, name, None)) for name in ("list_events", "subscribe", "unsubscribe")):
        return cast(MCPEventsAPI, source)
    if hasattr(source, "sdk_configuration"):
        return MCPEventsClient.from_outpost(source)
    if isinstance(source, Mapping) and "server_url" in source:
        return MCPEventsClient(**source)
    raise TypeError("expected an Outpost instance, a {'server_url', 'api_key'} mapping or an MCP Events client")


def _normalize_base_url(server_url: str) -> str:
    parts = urlsplit(server_url)
    # The API key is the only credential: drop any userinfo.
    host = parts.netloc.rpartition("@")[2]
    if parts.scheme not in ("http", "https") or not host:
        raise ValueError("the Outpost server URL must be an absolute http or https URL")
    path = parts.path.rstrip("/")
    if path.endswith("/api/v1"):
        path = path[: -len("/api/v1")] + "/api/v2"
    return urlunsplit((parts.scheme, host, path + "/", "", ""))


def _encode_tenant_id(tenant_id: str) -> str:
    """Percent-encodes a tenant ID as one path segment. "." and ".." are
    rejected: URL normalization would resolve them as dot segments."""
    if not isinstance(tenant_id, str) or tenant_id in ("", ".", ".."):
        raise ValueError("invalid tenant ID")
    return quote(tenant_id, safe="")


async def _read_capped(response: httpx.Response, max_bytes: int) -> str:
    declared = response.headers.get("content-length")
    if declared is not None and declared.isdigit() and int(declared) > max_bytes:
        raise MCPEventsRequestError("Outpost response is too large", status_code=response.status_code)
    chunks: list[bytes] = []
    total = 0
    # Decoded bytes, so a compressed body can't expand past the cap either.
    async for chunk in response.aiter_bytes():
        total += len(chunk)
        if total > max_bytes:
            raise MCPEventsRequestError("Outpost response is too large", status_code=response.status_code)
        chunks.append(chunk)
    return b"".join(chunks).decode("utf-8", errors="replace")


def _parse_response(status: int, text: str) -> dict[str, Any]:
    try:
        parsed: Any = json.loads(text) if text else None
    except ValueError:
        parsed = None
    if 200 <= status < 300:
        if isinstance(parsed, dict):
            return parsed
        raise MCPEventsRequestError(
            "Outpost returned a malformed MCP result", status_code=status, body=text[:_MAX_ERROR_BODY_CHARS]
        )
    if status == 422 and isinstance(parsed, dict):
        mcp_error = _as_mcp_error(parsed.get("mcp_error"))
        if mcp_error is not None:
            raise MCPError(mcp_error, status)
    raise MCPEventsRequestError(
        f"Outpost responded with status {status}", status_code=status, body=text[:_MAX_ERROR_BODY_CHARS]
    )


async def _maybe_await(value: Any) -> Any:
    return await value if inspect.isawaitable(value) else value


ResolveTenant = Callable[[str, Any], Union[Optional[str], Awaitable[Optional[str]]]]
AllowedTopics = Callable[[str, Any], Union[Sequence[str], Awaitable[Sequence[str]]]]
OnError = Callable[[BaseException, Method], None]


class MCPEventsHandlers:
    """Transport-agnostic ``events/*`` handlers on top of the Outpost endpoints.

    Each handler takes the authenticated principal, the raw MCP params and an
    optional request context (passed to the resolvers), and returns the MCP
    result or raises JSONRPCError.

    - ``resolve_tenant(principal, context)``: the Outpost tenant whose events the
      principal may subscribe to. ``None`` or ``""`` answers Forbidden.
    - ``allowed_topics(principal, context)``: optional. ``events/list`` only
      returns these topics (an empty list answers ``{"events": []}`` without
      calling Outpost) and ``events/subscribe`` answers NotFound for any other
      name, the same error as an unknown topic. ``events/unsubscribe`` is never
      filtered, so cleanup always works.
    - ``codes``: ``"sketch"`` (default), ``"sep-3415"`` or ErrorCodes, for the
      errors raised locally. Match Outpost's ``MCP_ERROR_CODES``.
    - ``on_error(error, method)``: called with every failure answered as a
      generic internal error, for logging. MCP clients never see the details.

    Requests without a principal are rejected with Forbidden.
    """

    def __init__(
        self,
        source: Any,
        *,
        resolve_tenant: ResolveTenant,
        allowed_topics: Optional[AllowedTopics] = None,
        codes: Union[str, ErrorCodes, None] = None,
        on_error: Optional[OnError] = None,
    ) -> None:
        if not callable(resolve_tenant):
            raise TypeError("resolve_tenant is required")
        self.client = create_client(source)
        self.codes = _resolve_codes(codes)
        self._resolve_tenant = resolve_tenant
        self._allowed_topics = allowed_topics
        self._on_error = on_error

    async def handle_list(self, principal: Optional[str], params: Any, context: Any = None) -> dict[str, Any]:
        """``events/list``."""

        async def call() -> dict[str, Any]:
            tenant_id, params_ = await self._prepare(principal, params, context)
            cursor = params_.get("cursor")
            if cursor is not None and not isinstance(cursor, str):
                raise self._invalid_params("cursor")
            topics = await self._allowlist(principal, context)
            if topics is not None and not topics:
                return {"events": []}
            return await self.client.list_events(tenant_id, cursor=cursor, topics=topics)

        return await self._run("events/list", call)

    async def handle_subscribe(self, principal: Optional[str], params: Any, context: Any = None) -> dict[str, Any]:
        """``events/subscribe``."""

        async def call() -> dict[str, Any]:
            tenant_id, params_ = await self._prepare(principal, params, context)
            topics = await self._allowlist(principal, context)
            body: dict[str, Any] = {"principal": principal, "params": params_}
            if topics is not None:
                # Every member a server could read as "name": Outpost is written
                # in Go, whose JSON decoding matches member names
                # case-insensitively, so {"name": "allowed", "Name": "hidden"}
                # must not pass as "allowed".
                for key, name in params_.items():
                    if isinstance(key, str) and key.lower() == "name" and isinstance(name, str) and name not in topics:
                        raise JSONRPCError(self.codes.not_found, "NotFound", {"kind": "event"})
                # Outpost enforces the same list, covering names that are not
                # strings and any client that bypasses this check.
                body["allowed_topics"] = topics
            return await self.client.subscribe(tenant_id, body)

        return await self._run("events/subscribe", call)

    async def handle_unsubscribe(self, principal: Optional[str], params: Any, context: Any = None) -> dict[str, Any]:
        """``events/unsubscribe``. Never filtered by ``allowed_topics``."""

        async def call() -> dict[str, Any]:
            tenant_id, params_ = await self._prepare(principal, params, context)
            return await self.client.unsubscribe(tenant_id, {"principal": principal, "params": params_})

        return await self._run("events/unsubscribe", call)

    def _forbidden(self) -> JSONRPCError:
        return JSONRPCError(self.codes.forbidden, "Forbidden")

    def _invalid_params(self, field: str) -> JSONRPCError:
        return JSONRPCError(self.codes.invalid_params, "InvalidParams", {"field": field, "reason": "invalid"})

    async def _prepare(self, principal: Any, params: Any, context: Any) -> tuple[str, dict[str, Any]]:
        if not isinstance(principal, str) or not principal:
            raise self._forbidden()
        if params is None:
            params = {}
        if not isinstance(params, Mapping):
            raise self._invalid_params("params")
        tenant_id = await _maybe_await(self._resolve_tenant(principal, context))
        if not isinstance(tenant_id, str) or not tenant_id:
            raise self._forbidden()
        return tenant_id, dict(params)

    async def _allowlist(self, principal: Any, context: Any) -> Optional[list[str]]:
        if self._allowed_topics is None:
            return None
        topics = await _maybe_await(self._allowed_topics(principal, context))
        if isinstance(topics, (str, bytes)) or not isinstance(topics, Sequence):
            raise TypeError("allowed_topics must return a sequence of topic names")
        # Topic names are never empty and never contain commas (the list is
        # sent comma-separated), so such entries can only fail to match;
        # dropping them keeps the allowlist from widening.
        return [t for t in topics if isinstance(t, str) and t and "," not in t]

    async def _run(self, method: Method, call: Callable[[], Awaitable[dict[str, Any]]]) -> dict[str, Any]:
        try:
            result = await call()
            if not isinstance(result, dict):
                raise TypeError(f"{method} result is not an object")
            return result
        except JSONRPCError:
            raise
        except Exception as err:  # pylint: disable=broad-exception-caught
            mcp_error = mcp_error_from(err)
            if mcp_error is not None:
                raise JSONRPCError(mcp_error["code"], mcp_error["message"], mcp_error.get("data")) from None
            self._report(err, method)
            raise JSONRPCError(self.codes.internal_error, "Internal error") from None

    def _report(self, err: BaseException, method: Method) -> None:
        if self._on_error is not None:
            try:
                self._on_error(err, method)
            except Exception:  # pylint: disable=broad-exception-caught
                pass  # A logging hook must not change the answer.


class _AnyParams(BaseModel):
    """Accepts any params object; Outpost validates them."""

    model_config = ConfigDict(extra="allow")


_EVENTS_CAPABILITY_MARK = "_outpost_events_capability"


async def _advertise_events(ctx: Any, call_next: Callable[[Any], Awaitable[Any]]) -> Any:
    """Adds the design-sketch ``events: {}`` capability, the one ChatGPT reads,
    to ``initialize`` and ``server/discover`` results. The SDK's capabilities
    model has no such field, so it is added to the wire result."""
    result = await call_next(ctx)
    if getattr(ctx, "method", None) in ("initialize", "server/discover") and isinstance(result, dict):
        capabilities = result.get("capabilities")
        if isinstance(capabilities, dict) and "events" not in capabilities:
            result = {**result, "capabilities": {**capabilities, "events": {}}}
    return result


setattr(_advertise_events, _EVENTS_CAPABILITY_MARK, True)


def _lowlevel_server(server: Any) -> Any:
    if callable(getattr(server, "add_request_handler", None)) and isinstance(getattr(server, "middleware", None), list):
        return server
    inner = getattr(server, "_lowlevel_server", None)  # mcp.server.mcpserver.MCPServer
    if inner is not None and callable(getattr(inner, "add_request_handler", None)):
        return inner
    raise TypeError(
        "expected a Server or MCPServer from the mcp package (version 2 or later); "
        "older versions reject custom methods such as events/list before any handler runs"
    )


def register(
    source: Any,
    server: Any,
    *,
    resolve_principal: Callable[[Any], Union[Optional[str], Awaitable[Optional[str]]]],
    resolve_tenant: ResolveTenant,
    allowed_topics: Optional[AllowedTopics] = None,
    codes: Union[str, ErrorCodes, None] = None,
    on_error: Optional[OnError] = None,
) -> MCPEventsHandlers:
    """Registers ``events/list``, ``events/subscribe`` and ``events/unsubscribe``
    on an ``mcp`` server (version 2 or later), proxied to Outpost, and
    advertises the ``events`` capability.

    ``server`` is a low-level ``mcp.server.Server`` or an
    ``mcp.server.mcpserver.MCPServer``. Call it before the server starts
    serving. ``source`` is an ``outpost_sdk.Outpost`` instance, a
    ``{"server_url": ..., "api_key": ...}`` mapping or an MCP Events client.

    ``resolve_principal(ctx)`` returns the authenticated subject of the
    request, for example ``get_access_token().subject`` from
    ``mcp.server.auth.middleware.auth_context``. Never use the OAuth client ID:
    every user of one MCP client shares it. A missing principal is Forbidden.
    See MCPEventsHandlers for the other options.
    """
    if not callable(resolve_principal):
        raise TypeError("resolve_principal is required")
    lowlevel = _lowlevel_server(server)
    try:
        # pylint: disable-next=import-outside-toplevel
        from mcp.shared.exceptions import MCPError as ProtocolError  # type: ignore[import-not-found,unused-ignore]
    except ImportError as err:
        raise RuntimeError("register() needs the mcp package, version 2 or later") from err

    handlers = MCPEventsHandlers(
        source, resolve_tenant=resolve_tenant, allowed_topics=allowed_topics, codes=codes, on_error=on_error
    )

    def bind(method: Method, handle: Callable[[Optional[str], Any, Any], Awaitable[dict[str, Any]]]) -> Any:
        async def handler(ctx: Any, params: _AnyParams) -> dict[str, Any]:
            raw = ctx.params if isinstance(getattr(ctx, "params", None), Mapping) else (params.model_extra or {})
            try:
                try:
                    principal = await _maybe_await(resolve_principal(ctx))
                except JSONRPCError:
                    raise
                except Exception as err:  # pylint: disable=broad-exception-caught
                    handlers._report(err, method)  # pylint: disable=protected-access
                    raise JSONRPCError(handlers.codes.internal_error, "Internal error") from None
                return await handle(principal, raw, ctx)
            except JSONRPCError as err:
                raise ProtocolError(err.code, err.message, err.data) from None

        return handler

    lowlevel.add_request_handler("events/list", _AnyParams, bind("events/list", handlers.handle_list))
    lowlevel.add_request_handler("events/subscribe", _AnyParams, bind("events/subscribe", handlers.handle_subscribe))
    lowlevel.add_request_handler(
        "events/unsubscribe", _AnyParams, bind("events/unsubscribe", handlers.handle_unsubscribe)
    )
    # SEP-3415 form, read by the SDK when it builds capabilities.
    lowlevel.extensions[EXTENSION_ID] = {}
    if not any(getattr(m, _EVENTS_CAPABILITY_MARK, False) for m in lowlevel.middleware):
        lowlevel.middleware.append(_advertise_events)
    return handlers
