# Default values for Outpost.

outpost:
  imagePullSecrets: []
  image:
    repository: outpost
    tag: latest
    ## Should be 'Always' for 'latest' image tag, otherwise 'IfNotPresent'
    ## Currently set to local image during development process
    pullPolicy: Never

  service:
    type: NodePort
    port: "3333"

  config:
    redis:
      host: "redis"
      port: "6379"
      password: ""
      database: "0"
