name: outpost-example
services:
  api:
    image: hookdeck/outpost:v0.1.0-alpha.6
    env_file: .env
    depends_on:
      redis:
        condition: service_started
    volumes:
      - ./config/outpost:/config/outpost
    environment:
      SERVICE: api
    ports:
      - 3333:3333

  delivery:
    image: hookdeck/outpost:v0.1.0-alpha.6
    env_file: .env
    depends_on:
      redis:
        condition: service_started
    volumes:
      - ./config/outpost:/config/outpost
    environment:
      SERVICE: delivery

  log:
    image: hookdeck/outpost:v0.1.0-alpha.6
    env_file: .env
    depends_on:
      redis:
        condition: service_started
    volumes:
      - ./config/outpost:/config/outpost
    environment:
      SERVICE: log

  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: >
      redis-server
        --save 20 1
        --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./data/redis:/data
