services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 1s
      retries: 30

  api:
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - "RABBITMQ_SERVER_URL=amqp://guest:guest@rabbitmq:5672"
  delivery:
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - "RABBITMQ_SERVER_URL=amqp://guest:guest@rabbitmq:5672"
  log:
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - "RABBITMQ_SERVER_URL=amqp://guest:guest@rabbitmq:5672"
